### ISSUE TITLE
Intermittent 500 errors when creating the same project release

### ISSUE THREAD

**Issue by wyeung** [getsentry/self-hosted#3195] opened 2024-07-10 19:55 UTC
### Self-Hosted Version

23.7.2

### CPU Architecture

x86_64

### Docker Version

20.10.8

### Docker Compose Version

Kubernetes

### Steps to Reproduce

After creating a project release via the API `/api/0/projects/org/team/releases/`, subsequent calls to the same endpoint with same data result in either `208 Already Reported` or `500 Internal Server Error`.

Our postgres cluster utilizes pgpool-4.2.6 for HA.

```
$ curl -XPOST -H "Content-Type: application/json" -H 'Authorization':'Bearer ' "https://sentry.company.com/api/0/projects/org/team/releases/" --data '{"version":"my-first-release-1","projects":["team"]}'
{"id":189244,"version":"my-first-release-1","status":"open","shortVersion":"my-first-release-1","versionInfo":{"package":null,"version":{"raw":"my-first-release-1"},"description":"my-first-release-1","buildHash":null},"ref":null,"url":null,"dateReleased":null,"dateCreated":"2024-07-08T22:17:12.609873Z","data":{},"newGroups":0,"owner":null,"commitCount":0,"lastCommit":null,"deployCount":0,"lastDeploy":null,"authors":[],"projects":[{"id":901,"slug":"team","name":"team","newGroups":0,"platform":"other","platforms":[],"hasHealthData":false}],"firstEvent":null,"lastEvent":null,"currentProjectMeta":{},"userAgent":"python-requests/2.31.0"}

$ curl -XPOST -H "Content-Type: application/json" -H 'Authorization':'Bearer ' "https://sentry.company.com/api/0/projects/org/team/releases/" --data '{"version":"my-first-release-1","projects":["team"]}'
{"detail":"Internal Error","errorId":"8885d2d57daa4d14a5848ac659e168d2"}
```

### Expected Result

For every subsequent call to the project releases endpoint with the same data to return back 2XX responses.

### Actual Result

```
19:17:04 [ERROR] django.request: Internal Server Error: /api/0/projects/org/team/releases/ (status_code=500 request=<WSGIRequest: POST '/api/0/projects/org/team/releases/'>)
10.233.79.72 - - [10/Jul/2024:19:17:01 +0000] "POST /api/0/projects/org/team/releases/ HTTP/1.1" 500 663 "-" "python-requests/2.31.0"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
psycopg2.DatabaseError: message contents do not agree with length in message type "N"
ERROR:  duplicate key value violates unique constraint "sentry_release_organization_id_version_65da5843_uniq"
DETAIL:  Key (organization_id, version)=(2, my-first-release-1) already exists.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
psycopg2.DatabaseError: DatabaseError('message contents do not agree with length in message type "N"\nERROR:  duplicate key value violates unique constraint "sentry_release_organization_id_version_65da5843_uniq"\nDETAIL:  Key (organization_id, version)=(2, my-first-release-1) already exists.\n')
SQL: INSERT INTO "sentry_release" ("organization_id", "status", "project_id", "version", "ref", "url", "date_added", "date_started", "date_released", "data", "new_groups", "owner_id", "commit_count", "last_commit_id", "authors", "total_deploys", "last_deploy_id", "package", "major", "minor", "patch", "revision", "prerelease", "build_code", "build_number", "user_agent") VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING "sentry_release"."id"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 239, in handle_exception
    response = super().handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 362, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/api/endpoints/project_releases.py", line 130, in post
    Release.objects.create(
  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 147, in override
    return original_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 147, in override
    return original_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 147, in override
    return original_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/django/__init__.py", line 616, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
django.db.utils.DatabaseError: DatabaseError('message contents do not agree with length in message type "N"\nERROR:  duplicate key value violates unique constraint "sentry_release_organization_id_version_65da5843_uniq"\nDETAIL:  Key (organization_id, version)=(2, my-first-release-1) already exists.\n')
SQL: INSERT INTO "sentry_release" ("organization_id", "status", "project_id", "version", "ref", "url", "date_added", "date_started", "date_released", "data", "new_groups", "owner_id", "commit_count", "last_commit_id", "authors", "total_deploys", "last_deploy_id", "package", "major", "minor", "patch", "revision", "prerelease", "build_code", "build_number", "user_agent") VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING "sentry_release"."id"
19:18:04 [ERROR] django.request: Internal Server Error: /api/0/projects/org/team/releases/ (status_code=500 request=<WSGIRequest: POST '/api/0/projects/org/team/releases/'>)
10.233.79.72 - - [10/Jul/2024:19:18:00 +0000] "POST /api/0/projects/org/team/releases/ HTTP/1.1" 500 663 "-" "python-requests/2.31.0"
```

**Comment by hubertdeng123** [comment] 2024-07-12 16:49
What image of postgres are you using? This might be related:
https://github.com/getsentry/self-hosted/issues/3167

**Comment by wyeung** [comment] 2024-07-12 17:31
> What image of postgres are you using? This might be related: #3167

We are using the following images for postgresql and pgpool:

- bitnami/postgresql-repmgr:12.16.0-debian-11-r51
- bitnami/pgpool:4.2.6-debian-10-r12

We restarted pgpool and that seemed to have resolved the issue so I'm trying to reproduce it by updating connection pooling configurations.

**Comment by MrKoopie** [comment] 2024-08-05 07:16
I can confirm this issue on Sentry 24.5.0. The constraint seems to be odd, why is a release tied to only ethe organization and not the project_id too?

```
        | django.db.utils.IntegrityError: UniqueViolation('duplicate key value violates unique constraint "sentry_release_organization_id_version_65da5843_uniq"\nDETAIL:  Key (organization_id, version)=(1, testing_63) already exists.\n')
web-1                                           | SQL: INSERT INTO "sentry_release" ("organization_id", "status", "project_id", "version", "ref", "url", "date_added", "date_started", "date_released", "data", "new_groups", "owner_id", "commit_count", "last_commit_id", "authors", "total_deploys", "last_deploy_id", "package", "major", "minor", "patch", "revision", "prerelease", "build_code", "build_number", "user_agent") VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING "sentry_release"."id"
```

**Comment by hubertdeng123** [comment] 2024-08-06 23:25
Going to close this as a duplicate of https://github.com/getsentry/self-hosted/issues/3167

**Closed by hubertdeng123** 2024-08-06 23:25 UTC
Labels: Waiting for: Product Owner
