### ISSUE TITLE
Clickhouse generating stack trace in logs

### ISSUE THREAD

**Issue by christopherowen** [getsentry/self-hosted#3124] opened 2024-06-10 11:31 UTC
### Self-Hosted Version

24.5.1

### CPU Architecture

x86_64

### Docker Version

20.10.25

### Docker Compose Version

v2.20.2

### Steps to Reproduce

- run `docker-compose logs -f -n10`

### Expected Result

no errors

### Actual Result

errors in the clickhouse logs include:

```
sentry-self-hosted-clickhouse-1                                    | 2024.06.10 11:23:25.353592 [ 48 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):
sentry-self-hosted-clickhouse-1                                    | 
sentry-self-hosted-clickhouse-1                                    | 
sentry-self-hosted-clickhouse-1                                    | 0. Poco::Net::SocketImpl::error(int, String const&) @ 0x0000000015b3dbf2 in /usr/bin/clickhouse
sentry-self-hosted-clickhouse-1                                    | 1. Poco::Net::SocketImpl::peerAddress() @ 0x0000000015b40376 in /usr/bin/clickhouse
sentry-self-hosted-clickhouse-1                                    | 2. DB::HTTPServerRequest::HTTPServerRequest(std::shared_ptr<DB::IHTTPContext>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x0000000013154417 in /usr/bin/clickhouse
sentry-self-hosted-clickhouse-1                                    | 3. DB::HTTPServerConnection::run() @ 0x0000000013152ba4 in /usr/bin/clickhouse
sentry-self-hosted-clickhouse-1                                    | 4. Poco::Net::TCPServerConnection::start() @ 0x0000000015b42834 in /usr/bin/clickhouse
sentry-self-hosted-clickhouse-1                                    | 5. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015b43a31 in /usr/bin/clickhouse
sentry-self-hosted-clickhouse-1                                    | 6. Poco::PooledThread::run() @ 0x0000000015c7a667 in /usr/bin/clickhouse
sentry-self-hosted-clickhouse-1                                    | 7. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015c7893c in /usr/bin/clickhouse
sentry-self-hosted-clickhouse-1                                    | 8. ? @ 0x00007fe3ee1a7609 in ?
sentry-self-hosted-clickhouse-1                                    | 9. ? @ 0x00007fe3ee0cc353 in ?
sentry-self-hosted-clickhouse-1                                    |  (version 23.8.11.29.altinitystable (altinity build))
```

**Comment by liukch** [comment] 2024-06-11 02:32
I think it is very similar with https://github.com/getsentry/snuba/issues/5707

**Comment by theneva** [comment] 2024-06-11 08:09
It also overlaps a little bit with https://github.com/getsentry/self-hosted/issues/2876, so I'm just linking that in here

**Comment by hubertdeng123** [comment] 2024-06-11 22:25
This does seem like a duplicate of https://github.com/getsentry/snuba/issues/5707, so I will close it in favor of the issue there.

**Closed by hubertdeng123** 2024-06-11 22:25 UTC
Labels: Waiting for: Product Owner
