### ISSUE TITLE
Error checking minimum Docker Compose version

### ISSUE THREAD

**Issue by thenets** [getsentry/self-hosted#1176] opened 2021-11-30 07:12 UTC
### Version

master branch

### Steps to Reproduce

1. Clone the repo
2. Run the installer:
   - `./install.sh`
3. Got error at "Checking minimum requirements"
   - Probably is an issue related to a regex to check the min version that now has a `v` at the beginning.

### Expected Result

Installation should work, cause I have the minimum required version.

#### Error message

```
[luiz@fedora self-hosted]$ ./install.sh 
▶ Parsing command line ...

▶ Setting up error handling ...

▶ Checking minimum requirements ...
FAIL: Expected minimum docker-compose version to be 1.28.0 but found Docker Compose version v2.0.1
```

#### Docker Compose version

I installed from the official GitHub project:
- https://github.com/docker/compose

```
[luiz@fedora self-hosted]$ docker-compose -v
Docker Compose version v2.0.1
```

**Comment by aminvakil** [comment] 2021-11-30 07:47
I thought something has been changed since https://github.com/getsentry/self-hosted/pull/1116, but this takes `v` prefix into account before checking already.

**Comment by BYK** [comment] 2021-11-30 11:36
So the issue here is we expect version `< 2` when `docker-compose` exists and use `docker compose` if we get an error or something. Can you confirm that you cannot run `docker compose` but can run `docker-compose`?

**Comment by aminvakil** [comment] 2021-11-30 13:20
Maybe the issue here is `/usr/local/bin/docker-compose` which is `< 2` and `/usr/libexec/docker/cli-plugins/docker-compose` which is `> 2` both exist.

**Comment by BYK** [comment] 2021-11-30 13:22
@aminvakil yeah that might be the issue but in that case, we should just be using `docker compose`. At least what I think the code does.

**Comment by aminvakil** [comment] 2021-11-30 13:33
> @aminvakil yeah that might be the issue but in that case, we should just be using `docker compose`. At least what I think the code does.

Yes, it appears so.

I just downgraded `docker-compose` to 2.0.1 and tested this:
```
docker compose version --short | sed 's/v\{0,1\}\(.\{1,\}\)/\1/'
2.0.1
```
So probably `2.0.1` specifically does not have problem.

**Comment by chadwhitacre** [comment] 2021-11-30 13:33
This is a dupe of https://github.com/getsentry/self-hosted/issues/1132, right?

**Comment by chadwhitacre** [comment] 2021-11-30 15:57
Gonna take that as a yes. 😛

**Closed by chadwhitacre** 2021-11-30 15:57 UTC
Labels: Status: Untriaged
