### ISSUE TITLE
fresh install failed to solve: executor failed running

### ISSUE THREAD

**Issue by Trepliev** [getsentry/self-hosted#1933] opened 2023-01-25 15:16 UTC
### Self-Hosted Version

23.1.0

### CPU Architecture

x86_64

### Docker Version

20.10.23

### Docker Compose Version

2.15.1

### Steps to Reproduce

- fresh install self-hosted
- ubuntu 22.04.1 LTS
- run install.sh

### Expected Result

Succesfull fresh install.

### Actual Result

#8 8.337 Adding group `crontab' (GID 101) ...
#8 8.457 Done.
#8 8.558 invoke-rc.d: could not determine current runlevel
#8 8.565 invoke-rc.d: policy-rc.d denied execution of start.
#8 DONE 10.4s
#6 writing image sha256:0a551680a740cc89631775de8f25a722d6240eed855ef44aa20210fac884a33d
#6 writing image sha256:0a551680a740cc89631775de8f25a722d6240eed855ef44aa20210fac884a33d 0.1s done
#6 naming to docker.io/library/sentry-self-hosted-local 0.0s done
#6 DONE 5.9s
failed to solve: executor failed running [/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*]: exit code: 100
Error in build-docker-images.sh:8.
'$dcb --force-rm $service' exited with status 17
-> ./install.sh:main:29
--> build-docker-images.sh:source:8

Cleaning up...

**Comment by Sebi94nbg** [comment] 2023-01-25 19:56
Looks like as a duplicate of #1932, which is already fixed in https://github.com/getsentry/self-hosted/issues/1932.

**Closed** 2023-01-27 17:24 UTC
Labels: Status: Untriaged
