### ISSUE TITLE
Error 500 when creating a release via CLI (duplicated release ID)

### ISSUE THREAD

**Issue by moroine** [getsentry/self-hosted#3357] opened 2024-10-01 11:09 UTC
### Self-Hosted Version

24.7.1

### CPU Architecture

x86_64

### Docker Version

27.3.0

### Docker Compose Version

2.29.6

### Steps to Reproduce

I have a repository https://github.com/mission-apprentissage/api-apprentissage/actions/runs/11122789320/job/30904805111 which is failing when I try to create a release via sentry. 

![Image](https://github.com/user-attachments/assets/faa1325d-1b76-43d4-8df0-4598e1a63def)

I cannot find out the eventId in my sentry to have better info about the issue.

Looks like the release is duplicated. ![Image](https://github.com/user-attachments/assets/a505a1cd-712b-4e6d-ab5b-6a5864b821d1)

And here is what I have when I try to click on view in one of them ![Image](https://github.com/user-attachments/assets/908db21b-85ec-4f23-88af-a3b42a366ba9)

### Expected Result

Not having duplicated releases

### Actual Result

Releases are duplicated and cannot be used

### Event ID

c25a6f4f18f045e4b0810bc98b518b75

**Comment by bc-sentry** [comment] 2024-11-11 20:18
Duplicate of https://github.com/getsentry/self-hosted/issues/3359

**Closed by bc-sentry** 2024-11-11 20:18 UTC
Labels: Waiting for: Product Owner
