### ISSUE TITLE
Import sentry_export.json doest work

### ISSUE THREAD

**Issue by miraslav** [getsentry/self-hosted#1428] opened 2022-04-19 06:01 UTC
### Version

22.4.0

### Steps to Reproduce

1. sentry export > /data/files/sentry_export.json  or docker-compose run --rm web export > sentry_export.json
2. sentry import sentry_export.json

### Expected Result

Import done.

### Actual Result

/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py:551: DeprecatedSettingWarning: The SENTRY_URL_PREFIX setting is deprecated. Please use SENTRY_OPTIONS['system.url-prefix'] instead.
  warnings.warn(DeprecatedSettingWarning(old, "SENTRY_OPTIONS['%s']" % new))
04:49:07 [INFO] sentry.plugins.github: apps-not-configured
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/serializers/json.py", line 68, in Deserializer
    objects = json.loads(stream_or_string)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 188, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/backup.py", line 19, in import_
    for obj in serializers.deserialize("json", src, stream=True, use_natural_keys=True):
  File "/usr/local/lib/python3.8/site-packages/django/core/serializers/json.py", line 73, in Deserializer
    raise DeserializationError() from exc
django.core.serializers.base.DeserializationError

**Comment by miraslav** [comment] 2022-04-19 06:04
I want to import all the data in the file into another sentry. But an interesting problem is that a sentry that has exported its settings cannot import its own file, not to mention in another sentry that is no different.

**Comment by aminvakil** [comment] 2022-04-19 08:39
@miraslav Is your issue fixed?

**Comment by miraslav** [comment] 2022-04-19 09:45
No. I tried replacing the volume as solved. But this doesn't solve my problem. I need to change the ROOT URL. This, as I understand it, is impossible. Because of this, I reinstalled Sentry. But there is another problem. From the old sentry, I have to transfer all the projects. But the solution from this site did not help. https://github.com/getsentry/self-hosted/issues/793

**Comment by aminvakil** [comment] 2022-04-19 11:33
Is error the same?

Because from the log you have pasted there is:
```
 json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)
```
which shows your json is malformed and sentry cannot import it because of that.

Have you tried following the exact commands from this page: https://develop.sentry.dev/self-hosted/backup/#quick-backup

**Comment by chadwhitacre** [comment] 2022-04-19 15:03
Possible duplicate of https://github.com/getsentry/self-hosted/issues/1322?

**Comment by miraslav** [comment] 2022-04-20 04:47
> Possible duplicate of #1322?

Yes, the problem is identical to the one you mentioned. But in the same thread I don't see a solution to the problem.

**Comment by miraslav** [comment] 2022-04-20 05:58
Ok, how I can resolve that error?
```
File "/usr/local/lib/python3.8/site-packages/django/core/serializers/json.py", line 73, in Deserializer
    raise DeserializationError() from exc
django.core.serializers.base.DeserializationError
```

**Comment by onmomo** [comment] 2022-04-26 06:55
![Screen Shot 2022-04-26 at 08 51 53](https://user-images.githubusercontent.com/1713109/165239786-fad0c104-a3ab-4487-8b47-50c23afde7dd.png)
The sentry export command generated an invalid json for me
```
root@sentry-web-55cd99ffd9-628vf:/# sentry export -> export.json
```
resulted in the following
```
06:15:02 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
06:15:10 [INFO] sentry.plugins.github: apps-not-configured
[
{
  "model": "sites.site",
  "pk": 1,
  "fields": {
    "domain": "example.com",
    "name": "example.com"
  }
},
....
```
Removing the log messages in the beginning of the file, fixed the `json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)` error.

**Comment by chadwhitacre** [comment] 2022-04-29 20:27
> Yes, the problem is identical to the one you mentioned.

Okay, I'm closing this in favor of #1322. I've copied the recent comments over there.

**Closed by chadwhitacre** 2022-04-29 20:27 UTC
Labels: Type: Support Request
