### ISSUE TITLE
Error "The organization you were looking for was not found." when trying to access issues/* from Crons `Recent Check-Ins`

### ISSUE THREAD

**Issue by thenav56** [getsentry/self-hosted#3281] opened 2024-08-21 04:50 UTC
### Self-Hosted Version

24.7.0

### CPU Architecture

x86_64

### Docker Version

27.1.2

### Docker Compose Version

2.29.1

### Steps to Reproduce

1. Install the sentry as the document specified.
2. Setup cron monitoring
3. Wait for error
4. Go to Crons -> Cron Monitor Details
5. Click on any issues under `Recent Check-Ins`
6. This will go to `/issues/<issue-id>/` which will throw this error `The organization you were looking for was not found.`

### Expected Result

The link should forward to `/organizations/<organization-alias>/issues/<issue-id>/`

![Image](https://github.com/user-attachments/assets/891c3e72-31aa-4a1d-bb86-40199c6cf1db)

### Actual Result

![Image](https://github.com/user-attachments/assets/8fa6e46f-743e-4368-8dd5-e87437fe727a)

![Image](https://github.com/user-attachments/assets/0b2ad39e-de00-4739-bebc-a3f29f0bd3c3)

**Comment by hubertdeng123** [comment] 2024-08-22 22:02
Seems to be a duplicate of https://github.com/getsentry/sentry/issues/75675, so going to close

**Closed by hubertdeng123** 2024-08-22 22:02 UTC
Labels: Waiting for: Product Owner
