### ISSUE TITLE
build.version is unknown

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/self-hosted#3261] opened 2024-08-12 16:19 UTC
### Self-Hosted Version

24.7.1 unknwon

### CPU Architecture

unknown

### Docker Version

unknown

### Docker Compose Version

unknown

### Steps to Reproduce

Reported on Twitter here: https://x.com/anny_goerl/status/1822911040281362748

### Expected Result

Build identifier is not unknown

### Actual Result

Build identifier is unknown

**Comment by aldy505** [comment] 2024-08-13 12:28
Not an actual issue that's messing up with anything. Also duplicate of https://github.com/getsentry/self-hosted/issues/3165, https://github.com/getsentry/self-hosted/issues/2925

**Closed by aldy505** 2024-08-13 12:28 UTC
Labels: Waiting for: Product Owner

**Comment by joshuarli** [comment] 2024-08-13 23:08
https://github.com/getsentry/sentry/pull/76139  This should reduce the confusion!
