### ISSUE TITLE
Session Replay is not working properly

### ISSUE THREAD

**Issue by mercury7720** [getsentry/self-hosted#2573] opened 2023-11-14 02:57 UTC
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

23.0.1

### Docker Compose Version

2.23.0

### Steps to Reproduce

we  running Sentry 23.9.1 on an instance with 8 cores and 32GB of memory. We have enabled the session replay feature, but after running for some time, the data collection stops at a certain point. Restarting with docker-compose up --force-recreate -d resolves the issue temporarily, but it eventually occurs again.

It's worth noting that I have observed that the data is actually being collected, but it is not displayed in the web console. After restarting the service, it appears normally.

If you need more logs to investigate the issue, please let me know. Thank you.

### Expected Result

- 

### Actual Result

<img width="755" alt="image" src="https://github.com/getsentry/self-hosted/assets/43591953/b7ec692c-8f50-4ff5-8eab-6dcb3bcc0681">

- After restarting the service, the data is displayed correctly in the console.
<img width="312" alt="image" src="https://github.com/getsentry/self-hosted/assets/43591953/8d846903-fb31-4153-86cf-34cf989b0bb8">

**Comment by hubertdeng123** [comment] 2023-11-15 20:07
Looks to be a duplicate of https://github.com/getsentry/self-hosted/issues/2379

Please chime in there instead!

**Closed by hubertdeng123** 2023-11-15 20:07 UTC
Labels: Waiting for: Product Owner
