### ISSUE TITLE
memory leak in Sentry 22.4.0?

### ISSUE THREAD

**Issue by mmcnl** [getsentry/self-hosted#1431] opened 2022-04-26 16:25 UTC
### Version

22.4.0

### Steps to Reproduce

1. upgraded from 22.1.0 to 22.4.0

### Expected Result

Memory usage remains stable (as it has for months with 22.1.0)

### Actual Result

Immediately after upgrading to Sentry 22.4.0, we started seeing increased memory usage in our Sentry VM. Memory usage had been stable for months with the previous version (22.1.0). There are no other significant processes running on the VM besides Sentry. Restarting clears the excess memory usage but the leak immediately begins again after docker restart.
![image](https://user-images.githubusercontent.com/1498727/165346823-b5488fd7-04be-48a2-9575-85bd4b817aa6.png)

**Comment by chadwhitacre** [comment] 2022-04-26 18:36
Dupe of https://github.com/getsentry/self-hosted/issues/1394, @mmcnl?

**Comment by chadwhitacre** [comment] 2022-04-26 18:38
Yeah, calling it.

**Closed by chadwhitacre** 2022-04-26 18:38 UTC
Labels: Type: Support Request

**Comment by mmcnl** [comment] 2022-04-26 18:41
> Dupe of #1394, @mmcnl?

Yes, looks very similar. Thanks for looking into it @chadwhitacre ! :)
