### ISSUE TITLE
The configure sdk screen is empty when creating a project

### ISSUE THREAD

**Issue by onepredict-lbm** [getsentry/self-hosted#2070] opened 2023-04-06 04:11 UTC
### Self-Hosted Version

23.4.0.dev0

### CPU Architecture

x86_64

### Docker Version

23.0.2

### Docker Compose Version

2.17.2

### Steps to Reproduce

1. “I installed Sentry self-hosted and installed Sentry by running the install.sh script and docker compose up -d”
2. "After installation, I created a project and the configure sdk screen was empty”
3. “I removed everything related to Sentry with docker compose down --volumes and docker volume rm and reinstalled it, but this problem still occurred”

### Expected Result

“Currently the sdk screen is empty. In another environment installed with the same version, the sdk configure screen appears correctly”
"Currently the example is ios, but this phenomenon occurs in all languages"

### Actual Result

![image](https://user-images.githubusercontent.com/127291063/230270122-0fff404e-699e-49ff-b21f-597474cb73bb.png)

**Comment by hubertdeng123** [comment] 2023-04-06 18:06
I'm getting this too, seems to be an issue that has been introduced recently

**Comment by hubertdeng123** [comment] 2023-04-06 18:27
Dropped a line internally, the team in charge of this change is now aware of this issue

**Comment by hubertdeng123** [comment] 2023-04-06 18:49
closing this as a duplicate of https://github.com/getsentry/sentry/issues/46993

**Closed** 2023-04-06 18:49 UTC
Labels: Type: Support Request
