### ISSUE TITLE
No Crash Free Sessions and Crash Free Users after autoupgrade to 24.1.0

### ISSUE THREAD

**Issue by duq3r** [getsentry/self-hosted#2981] opened 2024-04-18 06:55 UTC
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

We are trying to see the values but after the update we get 
![image](https://github.com/getsentry/sentry/assets/102025826/f314d278-92cc-4304-8f52-147160049515)

### How are you getting stuck?

Tried adding variable to config.py
SENTRY_RELEASE_HEALTH = "sentry.release_health.metrics.MetricsReleaseHealthBackend"
SENTRY_RELEASE_MONITOR = "sentry.release_health.release_monitor.metrics.MetricReleaseMonitorBackend"
and started getting zero values on this 
![image](https://github.com/getsentry/sentry/assets/102025826/77fad185-dd6d-44fa-8d93-89ecbe97d8ae)

Also tried to upgrade to version 24.4.0 and have the same problem.
![image](https://github.com/getsentry/sentry/assets/102025826/2fdfbf81-51c0-44fe-9894-b41fdf78e83b)
exept we started to get information about the releases.

So in the moment we get only issues and release information but no Crash Free Sessions and Crash Free Users.

Any ideas?

### Where in the product are you?

Projects - Project Details

### Version

24.1.0 tried also upgrading to 24.4.0 (same issue)

**Comment by hubertdeng123** [comment] 2024-04-19 16:54
closing as duplicate of https://github.com/getsentry/self-hosted/issues/2814

**Closed by hubertdeng123** 2024-04-19 16:54 UTC
Labels: Waiting for: Product Owner

**Comment by duq3r** [comment] 2024-04-19 21:23
Snuba was ok with no problems like in other threads. To solve the problem we had to deploy a new server and migrate the configuration there from the updated old server. That way we got working Crash Free Sessions. The old server we will keep for some time for archive data and then will delete it.
