### ISSUE TITLE
Getting error "The organization you were looking for was not found." when trying to access session replays

### ISSUE THREAD

**Issue by alkanna** [getsentry/self-hosted#2291] opened 2023-07-24 12:19 UTC
### Self-Hosted Version

23.7.0

### CPU Architecture

x86_64

### Docker Version

20.10.22, build 3a2c30b

### Docker Compose Version

v2.16.0

### Steps to Reproduce

Not really sure.
I was initially in 23.3, tried to upgrade to 23.7.0 but migrations failed due to a pending issue regarding migrations.
I managed to upgrade by going back to 23.5 -> 23.6 -> 23.7.0

### Expected Result

Able to access replays through the frontend

### Actual Result

I had an issue initially where replays were not showing up at all, but then enabled the corresponding feature flag in the sentry.config.py file, and after restarting the stack a few times replays started showing up.
However, I get the error message `The organization you were looking for was not found.` when trying to access a replay.

I see this as well in the console :

![CleanShot 2023-07-24 at 14 18 18](https://github.com/getsentry/self-hosted/assets/30343764/5bb974b0-675c-49d5-8d07-0355b78251d8)

**Comment by alkanna** [comment] 2023-07-24 12:51
It looks like the organizations/**teamName**/replays is missing, as it tries to access directly organizations/replays. I might be mistaken though I don't really know what the spec is on this endpoint.

**Comment by alkanna** [comment] 2023-07-24 12:55
This might be the issue : https://github.com/getsentry/sentry/pull/52933/files

**Comment by xliee** [comment] 2023-07-24 13:53
It looks like that pool request is the cause, i dont know what was the point of that pr but the actual self-host version looks broken.
When you access the replays list (in https://example.com/organizations/{organization_slug}/replays) 
and click one of the replays, it redirects you to, `https://example.com/replays/1461d5f133fa4e8d8914b607b314efcb/...`
there appears this error
![image](https://github.com/getsentry/self-hosted/assets/40280035/679c4c8c-1605-4ffc-8afd-1e0f9a3cda0c)

The correct url should indeed be `https://example.com/organizations/sentry/replays/1461d5f133fa4e8d8914b607b314efcb/...`
![image](https://github.com/getsentry/self-hosted/assets/40280035/5ca8808c-191d-4d92-984b-c0c00293fed6)

The `organizations/${organization.slug}/` is missing (https://github.com/getsentry/sentry/pull/52933/files#diff-deb3934bfd12ee1ede62177d72424cfe226a9a3a15d97feb36588b9e3f8ebbba)

**Comment by hubertdeng123** [comment] 2023-07-24 21:37
Thanks for bringing this up. Looks like it is being investigated already.

**Comment by bruno-garcia** [comment] 2023-07-24 22:09
We have a fix merged in. Asked on this ticket for folks to validate it: 

* https://github.com/getsentry/sentry/issues/53431#issuecomment-1648691959

But we'll need to get a new CalVer release out with a patch. @hubertdeng123 once it's valiated, what's the process to get a patch out?

**Comment by alkanna** [comment] 2023-07-24 23:44
Did a quick test on latest commit, it seems to be working fine now 😄

**Closed** 2023-07-25 16:39 UTC
Labels: Type: Bug, Waiting for: Product Owner

**Comment by xliee** [comment] 2023-07-26 14:05
You can pull getsentry/sentry:nightly with `docker pull getsentry/sentry:nightly` and restart the containers or just run `install.sh`

**Comment by hubertdeng123** [comment] 2023-07-26 18:11
This fix should've gone out with version 23.7.1. Thanks folks for your patience.
