### ISSUE TITLE
Unable to restore Sentry backup successfully

### ISSUE THREAD

**Issue by stepan8608** [getsentry/self-hosted#2540] opened 2023-11-02 12:54 UTC
### Self-Hosted Version

23.10.1

### CPU Architecture

x86_64

### Docker Version

 24.0.2

### Docker Compose Version

1.25.3

### Steps to Reproduce

1. I created backup.json with backup.sh script 
2. I'm trying to restore it using restore.sh and getting an error

### Expected Result

recovery should be successful

### Actual Result

When I run the restore.sh I get an error
`RpcImportError(
        kind: Unknown,
        on: InstanceID(model: 'sentry.userip'),
        reason: Unknown internal error occurred: get() returned more than one UserIP -- it returned 2!
)
`
![sentry](https://github.com/getsentry/self-hosted/assets/105638163/e87f1807-a0b0-46fc-bf10-6fc92e318c2b)

**Comment by hubertdeng123** [comment] 2023-11-03 21:07
Looks to be a duplicate of https://github.com/getsentry/self-hosted/issues/2468, so I'm going to close this

**Closed by hubertdeng123** 2023-11-03 21:07 UTC
Labels: Waiting for: Product Owner
