### ISSUE TITLE
Error while update 21.10.0 > 21.11.0

### ISSUE THREAD

**Issue by jakubenglicky** [getsentry/self-hosted#1184] opened 2021-12-02 20:44 UTC
### Version

21.10.0

### Steps to Reproduce

1. checkout to tag 21.11.0
2. install.sh

### Expected Result

Update to v21.11.0

### Actual Result

Installation is complete, but while instalation i've get this message:

```
/usr/local/lib/python3.8/site-packages/sentry/utils/email/list_resolver.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
20:30:54 [INFO] sentry.plugins.github: apps-not-configured
```

**Comment by chadwhitacre** [comment] 2021-12-02 20:47
Thanks @jakubenglicky. This is a duplicate of https://github.com/getsentry/self-hosted/issues/1162. The warning is harmless and should be gone now. :)

**Closed by chadwhitacre** 2021-12-02 20:47 UTC
Labels: Status: Untriaged
