### ISSUE TITLE
Why does docker-compose up-d report errors pull access denied for sentry-cleanup-self-hosted-local, repository does not exist or may require 'docker login': denied: requested access to the resource i…？？

### ISSUE THREAD

**Issue by chenqiang915** [getsentry/self-hosted#3036] opened 2024-05-09 09:06 UTC
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Normal download image installation

### How are you getting stuck?

![20240509-170528](https://github.com/getsentry/sentry/assets/67944136/5447e715-616a-4bb9-b785-105dade7a13c)

### Where in the product are you?

Unknown

**Comment by aldy505** [comment] 2024-05-10 10:21
Hello, a few questions:

1. Did you do `sudo ./install.sh` and `sudo docker compose up -d` in order? Or did you just do `docker compose up -d`?
2. Assuming you're from China, do you happen to access Docker Hub through some sort of proxy? If yes, can you pull each of the Docker images beforehand, and disables the proxy after everything's pulled? Should be: 
   ```bash
   images=(
     "getsentry/sentry:24.4.2"
     "getsentry/snuba:24.4.2"
     "getsentry/relay:24.4.2"
     "getsentry/symbolicator:24.4.2"
     "getsentry/vroom:24.4.2"
     "tianon/exim4"
     "memcached:1.6.26-alpine"
     "redis:6.2.14-alpine"
     "postgres:14.11-alpine"
     "confluentinc/cp-zookeeper:7.6.1"
     "confluentinc/cp-kafka:7.6.1"
     "altinity/clickhouse-server:21.8.13.1.altinitystable"
     "ghcr.io/maxmind/geoipupdate:v6.1.0"
     "busybox"
     "getsentry/sentry-cli"
     "jq"
   )
   for i in "${images[@]}"; do
     sudo docker pull "$i"
   done
   ```
   I don't know how you'd be able to enable/disable your proxy. You'll have to figure that out on your own.

**Comment by chenqiang915** [comment] 2024-05-11 02:30
> 您好，请教几个问题：
> 
> 1. 你按顺序做了`sudo ./install.sh`吗`sudo docker compose up -d`？还是你刚刚做了`docker compose up -d`？
> 2. 假设您来自中国，您是否碰巧通过某种代理访问 Docker Hub？如果是，您可以预先拉取每个 Docker 映像，并在拉取所有内容后取消代理吗？应该：
>    ```shell
>    images=(
>      "getsentry/sentry:24.4.2"
>      "getsentry/snuba:24.4.2"
>      "getsentry/relay:24.4.2"
>      "getsentry/symbolicator:24.4.2"
>      "getsentry/vroom:24.4.2"
>      "tianon/exim4"
>      "memcached:1.6.26-alpine"
>      "redis:6.2.14-alpine"
>      "postgres:14.11-alpine"
>      "confluentinc/cp-zookeeper:7.6.1"
>      "confluentinc/cp-kafka:7.6.1"
>      "altinity/clickhouse-server:21.8.13.1.altinitystable"
>      "ghcr.io/maxmind/geoipupdate:v6.1.0"
>      "busybox"
>      "getsentry/sentry-cli"
>      "jq"
>    )
>    for i in "${images[@]}"; do
>      sudo docker pull "$i"
>    done
>    
>    # Then run `sudo ./install.sh` and `sudo docker compose up -d` after that.
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    我不知道你如何启用/取消代理。你必须自己解决这个问题。

我是按照以下顺序执行的
sudo ./install.sh
sudo docker compose up -d

**Comment by chenqiang915** [comment] 2024-05-11 02:35
> 您好，请教几个问题：
> 
> 1. 你按顺序做了`sudo ./install.sh`吗`sudo docker compose up -d`？还是你刚刚做了`docker compose up -d`？
> 2. 假设您来自中国，您是否碰巧通过某种代理访问 Docker Hub？如果是，您可以预先拉取每个 Docker 映像，并在拉取所有内容后取消代理吗？应该：
>    ```shell
>    images=(
>      "getsentry/sentry:24.4.2"
>      "getsentry/snuba:24.4.2"
>      "getsentry/relay:24.4.2"
>      "getsentry/symbolicator:24.4.2"
>      "getsentry/vroom:24.4.2"
>      "tianon/exim4"
>      "memcached:1.6.26-alpine"
>      "redis:6.2.14-alpine"
>      "postgres:14.11-alpine"
>      "confluentinc/cp-zookeeper:7.6.1"
>      "confluentinc/cp-kafka:7.6.1"
>      "altinity/clickhouse-server:21.8.13.1.altinitystable"
>      "ghcr.io/maxmind/geoipupdate:v6.1.0"
>      "busybox"
>      "getsentry/sentry-cli"
>      "jq"
>    )
>    for i in "${images[@]}"; do
>      sudo docker pull "$i"
>    done
>    
>    # Then run `sudo ./install.sh` and `sudo docker compose up -d` after that.
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    我不知道你如何启用/取消代理。你必须自己解决这个问题。

*
Similar to this configuration BASE_IMAGE not recognized, default to pull the vroom-cleanup-self-hosted-local, but in fact docker.hub does not have this mirroring, so directly report pull access denied for vroom-cleanup-self-hosted-local, repository does not exist or may require'docker login ': denied: requested access to the resource is

**Comment by aldy505** [comment] 2024-05-11 02:38
> Similar to this configuration BASE_IMAGE not recognized, default to pull the vroom-cleanup-self-hosted-local, but in fact docker.hub does not have this mirroring, so directly report pull access denied for vroom-cleanup-self-hosted-local, repository does not exist or may require'docker login ': denied: requested access to the resource is

Yes, some of the containers should be built by the `Dockerfile` provided on each directory. All you need to do is just pull the base image as I've listed before. After you pull every of those Docker image, you should disable your Docker proxy mirroring in order for your server not to pull new images from the Docker mirror.

**Comment by chenqiang915** [comment] 2024-05-11 02:42
> > Similar to this configuration BASE_IMAGE not recognized, default to pull the vroom-cleanup-self-hosted-local, but in fact docker.hub does not have this mirroring, so directly report pull access denied for vroom-cleanup-self-hosted-local, repository does not exist or may require'docker login ': denied: requested access to the resource is
> 
> Yes, some of the containers should be built by the `Dockerfile` provided on each directory. All you need to do is just pull the base image as I've listed before. After you pull every of those Docker image, you should disable your Docker proxy mirroring in order for your server not to pull new images from the Docker mirror.

My/etc/docker/daemon.json only has the following content, and no docker proxy is configured
{
  "data-root": "/data/docker"
}

**Comment by chenqiang915** [comment] 2024-05-11 02:53
> Hello, a few questions:
> 
> 1. Did you do `sudo ./install.sh` and `sudo docker compose up -d` in order? Or did you just do `docker compose up -d`?
> 2. Assuming you're from China, do you happen to access Docker Hub through some sort of proxy? If yes, can you pull each of the Docker images beforehand, and disables the proxy after everything's pulled? Should be:
>    ```shell
>    images=(
>      "getsentry/sentry:24.4.2"
>      "getsentry/snuba:24.4.2"
>      "getsentry/relay:24.4.2"
>      "getsentry/symbolicator:24.4.2"
>      "getsentry/vroom:24.4.2"
>      "tianon/exim4"
>      "memcached:1.6.26-alpine"
>      "redis:6.2.14-alpine"
>      "postgres:14.11-alpine"
>      "confluentinc/cp-zookeeper:7.6.1"
>      "confluentinc/cp-kafka:7.6.1"
>      "altinity/clickhouse-server:21.8.13.1.altinitystable"
>      "ghcr.io/maxmind/geoipupdate:v6.1.0"
>      "busybox"
>      "getsentry/sentry-cli"
>      "jq"
>    )
>    for i in "${images[@]}"; do
>      sudo docker pull "$i"
>    done
>    
>    # Then run `sudo ./install.sh` and `sudo docker compose up -d` after that.
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    I don't know how you'd be able to enable/disable your proxy. You'll have to figure that out on your own.

I seem to have solved this problem. My local environment umask is 027, which causes the directory permissions of my git clone code file to be incorrect. I feel your reply

**Comment by aldy505** [comment] 2024-05-11 02:58
So.. did the installation process finished successfully?

**Comment by chenqiang915** [comment] 2024-05-11 03:06
> 那么..安装过程成功完成了吗？

The test host was successful, and I am ready to try it in production.

**Comment by ngudbhav** [comment] 2024-05-11 12:17
We are also facing this issue.

We are running Sentry on Elastic Beanstalk, and the thing is we cannot configure much of the behaviour of the Docker platform. Even if I use `./install.sh`, EB will still remove the already built images and then run `docker compose up -d` which will try to pull everything again.
Now the issue for us is intermittent. If it fails once, I run `docker image prune` and then restart the deployment only to see it succeed.

**Comment by aldy505** [comment] 2024-05-12 04:48
> We are also facing this issue.
> 
> We are running Sentry on Elastic Beanstalk, and the thing is we cannot configure much of the behaviour of the Docker platform. Even if I use `./install.sh`, EB will still remove the already built images and then run `docker compose up -d` which will try to pull everything again. Now the issue for us is intermittent. If it fails once, I run `docker image prune` and then restart the deployment only to see it succeed.

@ngudbhav I don't think that's something we can help either. The self-hosted sentry is aimed for a plain old VM with regular Docker installed.

**Comment by pquerner** [comment] 2024-05-13 16:44
Duplicate of 2641

**Comment by aldy505** [comment] 2024-05-20 10:01
I got this error a while ago on a Debian server while migrating from 24.4.2 to 24.5.0. What I did was:

1. Run `sudo ./install.sh`, got "pull access denied..."
2. Run `sudo apt update && sudo apt upgrade -y`, it turns out there's an update on Docker.
3. Run `sudo docker compose down`, to make sure no container is running.
4. Run `sudo ./install.sh` again, then directly do `sudo docker compose up -d`.

I don't know what caused this, but probably this is a Docker issue, not a specific self-hosted issue.

*PS. My Docker is not rootless, so I need to use `sudo` for executing Docker commands.

**Comment by nicolasThal** [comment] 2024-06-26 13:35
Hi,

I encountered a similar issue : 

I was in version `24.1.0` and I wanted to upgrade it.
After following the documentation protocol (`install.sh`, then `docker compose up -d`), I had the same issue.

I tested it on multiple version between 24.1.2 and 24.6.0.

Each time I noticed that the image `sentry-self-hosted-local` was missing from my computer.

Even when I launch the `install.sh` in the version `24.1.0` then in another version, the image is missing.

To solve my issue, I had to checkout the `24.1.0` version, launch the `install.sh` script, then checkout in the version `24.1.2` and launch `docker compose up -d`.

I do not know if my modification can help you solve the issue.

**Comment by iulian0512** [comment] 2024-08-16 18:41
occurs also in 24.8.0

**Comment by shawe** [comment] 2024-08-17 14:01
> occurs also in 24.8.0, i solved it by installing on a fresh machine then manually copied the missing docker images.

Happens to me too, can you explain what exactly do?

**Comment by pquerner** [comment] 2024-08-17 14:03
git clone again and restart over. Either in the same directory (delete first) or a new one.

**Comment by shawe** [comment] 2024-08-17 14:04
> git clone again and restart over. Either in the same directory (delete first) or a new one.

I clone it for first time some minutes ago only. Really is this needed?

**Comment by pquerner** [comment] 2024-08-17 14:07
For me that helped.
I had a finished installation and upgrade was impossible because of this issue. I deleted the folder, git clone again (same folder) - checked out same version (that I had previously installed) and then it worked (I could even upgrade to a newer version then).

If that doesnt fix it, then I dont know what can help you, sorry.

**Comment by silentsee** [comment] 2024-09-10 07:33
The 24.1.2 release will change the memcached backend from django.core.cache.backends.memcached.MemcachedCache to django.core.cache.backends.memcached.PyMemcacheCache. This will require changing the CACHES setting in your sentry.conf.py file in a manner similar to what is seen [here](https://github.com/getsentry/self-hosted/commit/9936376f4e933781feaae85e0071ef72c7f1c03f). In particular, the OPTIONS API for PyMemcacheCache is different from that of MemcachedCache, and may require changes depending on how it has been configured.

**Comment by aldy505** [comment] 2024-09-10 07:37
Seems like everyone got this fixed already. I'm going to close the issue. If you (readers from the future) are experiencing this and don't find any solution that fits you, feel free to create a new issue.

**Closed by aldy505** 2024-09-10 07:37 UTC
Labels: Waiting for: Product Owner
