### ISSUE TITLE
ip issus when using a self-hosted sentry server

### ISSUE THREAD

**Issue by ljwlaji** [getsentry/self-hosted#1144] opened 2021-11-11 05:15 UTC
### Problem Statement

I have created a self-host sentry.io server though docker image, my host server will change it's IP address when it restart every time. 
and when I using the docker-compose up -d command after the server was started, the IP address on website won't change with the host server ip -- it just keep as the first install.
how can I edit the IP address on website?
I have tried to edit onpremiseDir/sentry/config.yml to the new IP address and run command 
docker-compose down && docker-compose up -d 
but it doesn't work.
server os : centos 8.3
docker version : 19.03
docker-compose version: 1.29
![image](https://user-images.githubusercontent.com/16899528/141241419-2f31bdf5-8be3-48c4-ab27-edd0c835f3a3.png)

**Comment by chadwhitacre** [comment] 2021-11-12 22:24
Can you help me define better steps to reproduce your problem?

> I have created a self-host sentry.io server though docker image, my host server will change it's IP address when it restart every time.

You're using the normal `install.sh` installation method, yes?

So ... 

## Steps

1. Install via ./install.sh
2. Inspect IP address ... how, exactly?
3. Shut down sentry with `docker compose down`
4. Start up sentry with `docker compose up -d`
5. Inspect IP address as in step (2)

## Expected

IP address is the same in step (5) as step (2)

## Actual 

IP address differs between steps (5) and (2).

-----

Something like that?

From your screenshot it looks like what you're after is an IP address listed in the documentation ... can you search the Sentry codebase for that documentation page to see where the IP address is coming from and trace it through the system that way to understand how to influence it?

**Comment by chadwhitacre** [comment] 2021-11-23 22:52
Closing for lack of engagement.

**Closed by chadwhitacre** 2021-11-23 22:52 UTC
Labels: Status: Needs More Information

**Comment by ljwlaji** [comment] 2021-11-29 05:32
sloved by re-install thx!
