### ISSUE TITLE
Index corruption when upgrade to 22.1.0 from 21.12.0

### ISSUE THREAD

**Issue by aamarques** [getsentry/self-hosted#1269] opened 2022-01-24 09:54 UTC
### Version

22.1.0

### Steps to Reproduce

git fetch
git checkout 22.1.0
and
SENTRY_IMAGE=getsentry/sentry:22.1.0 ./install.sh

### Expected Result

Completed instalation without error

### Actual Result

`Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py:551: DeprecatedSettingWarning: The SENTRY_URL_PREFIX setting is deprecated. Please use SENTRY_OPTIONS['system.url-prefix'] instead.
  warnings.warn(DeprecatedSettingWarning(old, "SENTRY_OPTIONS['%s']" % new))
09:43:11 [INFO] sentry.plugins.github: apps-not-configured
Running migrations for default
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, nodestore, sentry, sessions, sites, social_auth
Running migrations:
  Applying sentry.0249_add_avatar_type_back... OK
  Applying sentry.0250_backfill_popularity... OK
  Applying sentry.0251_sentryappavatar_sentryapp_not_unique... OK
  Applying sentry.0252_code_mapping_cascade_delete... OK
  Applying sentry.0253_add_widget_type... OK
  Applying sentry.0254_org_integration_grace_period_end... OK
  Applying sentry.0255_delete_code_mappings_with_no_integration... OK
  Applying sentry.0256_create_docintegration_table... OK
  Applying sentry.0257_add_target_id_and_type_to_integrationfeature... OK
  Applying sentry.0258_create_docintegrationavatar_table... OK
  Applying sentry.0259_delete_codeowners_and_code_mappings_with_no_integration... OK
  Applying sentry.0260_backfill_integrationfeature... OK
  Applying sentry.0261_prepare_remove_sentry_app_column... OK
  Applying sentry.0262_drop_sentry_app_from_integrationfeature... OK
  Applying sentry.0263_remove_not_null_integrationfeature... OK
  Applying sentry.0264_use_booleanfield_docintegration... OK
  Applying sentry.0265_add_userrole... OK
  Applying sentry.0266_add_dashboard_widget_detail_field... OK
Creating missing DSNs
Correcting Group.num_comments counter
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 78, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
psycopg2.errors.InternalError_: right sibling's left-link doesn't match: block 833 links to 153 instead of expected 756 in index "sentry_groupedmessage_project_id_status_last_s_6b8195a7_idx"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 78, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
psycopg2.errors.InternalError_: InternalError_('right sibling\'s left-link doesn\'t match: block 833 links to 153 instead of expected 756 in index "sentry_groupedmessage_project_id_status_last_s_6b8195a7_idx"\n')
SQL:
        UPDATE sentry_groupedmessage SET num_comments = (
            SELECT COUNT(*) from sentry_activity
            WHERE type = %s and group_id = sentry_groupedmessage.id
        )

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 188, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py", line 100, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py", line 67, in _upgrade
    call_command("sentry.runner.commands.repair.repair")
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 155, in call_command
    command.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/repair.py", line 88, in repair
    fix_group_counters()
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/repair.py", line 57, in fix_group_counters
    cursor.execute(
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 500, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 78, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
django.db.utils.InternalError: InternalError_('right sibling\'s left-link doesn\'t match: block 833 links to 153 instead of expected 756 in index "sentry_groupedmessage_project_id_status_last_s_6b8195a7_idx"\n')
SQL:
        UPDATE sentry_groupedmessage SET num_comments = (
            SELECT COUNT(*) from sentry_activity
            WHERE type = %s and group_id = sentry_groupedmessage.id
        )

1
An error occurred, caught SIGERR on line 12
Cleaning up...`

**Comment by chadwhitacre** [comment] 2022-01-24 15:19
Yikes! Looks bad. SO suggests you have a corrupt index for some reason? Tips to fix over there ...

https://stackoverflow.com/questions/49307292/error-in-postgresql-right-siblings-left-link-doesnt-match-block-5-links-to-8

**Comment by ZedLove** [comment] 2022-01-25 21:16
I also have a deployment that is broken because of this error. I believe this was encountered during a migration, possibly just before [267](https://github.com/getsentry/sentry/blob/master/src/sentry/migrations/0267_sentry_release_version_btree.py). 

The error in this case was 
```
/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py:551: DeprecatedSettingWarning: The SENTRY_URL_PREFIX setting is deprecated. Please use SENTRY_OPTIONS['system.url-prefix'] instead.
  warnings.warn(DeprecatedSettingWarning(old, \"SENTRY_OPTIONS['%s']\" % new))
07:11:26 [INFO] sentry.plugins.github: apps-not-configured
* Unknown config option found: 'slack.legacy-app'
Running migrations for default
\u001b[36;1mOperations to perform:\u001b[0m
\u001b[1m  Apply all migrations: \u001b[0madmin, auth, contenttypes, nodestore, sentry, sessions, sites, social_auth
\u001b[36;1mRunning migrations:\u001b[0m
  Applying sentry.0264_use_booleanfield_docintegration...\u001b[32;1m OK\u001b[0m
  Applying sentry.0265_add_userrole...\u001b[32;1m OK\u001b[0m
  Applying sentry.0266_add_dashboard_widget_detail_field...\u001b[32;1m OK\u001b[0m
Creating missing DSNs
Correcting Group.num_comments counter
Traceback (most recent call last):
  File \"/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py\", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py\", line 78, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
psycopg2.errors.InternalError_: missing chunk number 0 for toast value 752679 in pg_toast_2619


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File \"/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py\", line 84, in _execute
    return self.cursor.execute(sql, params)
  File \"/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py\", line 77, in inner
    raise_the_exception(self.db, e)
  File \"/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py\", line 75, in inner
    return func(self, *args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py\", line 18, in inner
    return func(self, *args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py\", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File \"/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py\", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py\", line 78, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
psycopg2.errors.InternalError_: InternalError_('missing chunk number 0 for toast value 752679 in pg_toast_2619\
')
SQL:
        UPDATE sentry_groupedmessage SET num_comments = (
            SELECT COUNT(*) from sentry_activity
            WHERE type = %s and group_id = sentry_groupedmessage.id
        )


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File \"/usr/local/bin/sentry\", line 8, in <module>
    sys.exit(main())
  File \"/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py\", line 188, in main
    func(**kwargs)
  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 829, in __call__
    return self.main(*args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 782, in main
    rv = self.invoke(ctx)
  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 610, in invoke
    return callback(*args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/click/decorators.py\", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py\", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 610, in invoke
    return callback(*args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/click/decorators.py\", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py\", line 100, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)
  File \"/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py\", line 67, in _upgrade
    call_command(\"sentry.runner.commands.repair.repair\")
  File \"/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py\", line 155, in call_command
    command.invoke(ctx)
  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 610, in invoke
    return callback(*args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/click/decorators.py\", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py\", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 610, in invoke
    return callback(*args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/sentry/runner/commands/repair.py\", line 88, in repair
    fix_group_counters()
  File \"/usr/local/lib/python3.8/site-packages/sentry/runner/commands/repair.py\", line 57, in fix_group_counters
    cursor.execute(
  File \"/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py\", line 500, in execute
    return real_execute(self, sql, params)
  File \"/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py\", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File \"/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py\", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File \"/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py\", line 84, in _execute
    return self.cursor.execute(sql, params)
  File \"/usr/local/lib/python3.8/site-packages/django/db/utils.py\", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File \"/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py\", line 84, in _execute
    return self.cursor.execute(sql, params)
  File \"/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py\", line 77, in inner
    raise_the_exception(self.db, e)
  File \"/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py\", line 75, in inner
    return func(self, *args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py\", line 18, in inner
    return func(self, *args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py\", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File \"/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py\", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py\", line 78, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
django.db.utils.InternalError: InternalError_('missing chunk number 0 for toast value 752679 in pg_toast_2619\
')
SQL:
        UPDATE sentry_groupedmessage SET num_comments = (
            SELECT COUNT(*) from sentry_activity
            WHERE type = %s and group_id = sentry_groupedmessage.id
        )
```

**Comment by chadwhitacre** [comment] 2022-01-25 21:38
Bummer. 😕 I've surface internally ... 🤞

**Comment by ZedLove** [comment] 2022-01-25 22:07
Following the steps suggested here got sentry up and running again: https://stackoverflow.com/questions/49307292/error-in-postgresql-right-siblings-left-link-doesnt-match-block-5-links-to-8/49315992#49315992

**Comment by chadwhitacre** [comment] 2022-01-26 13:10
Is it possible that you are on RDS and were force-upgraded to Postgres 10?

See #1097 for more on that.

**Comment by chadwhitacre** [comment] 2022-01-26 13:21
> Following the steps suggested here got sentry up and running again:

Sweet, if my hypothesis is correct then this means that Sentry runs fine on Postgres 12. 😎

**Comment by ZedLove** [comment] 2022-01-26 16:19
> Is it possible that you are on RDS and were force-upgraded to Postgres 12?
> 
> See #1097 for more on that.

In our case, we are using Postgres 9.6, which I believe is the default for Sentry 22.1.0

**Comment by chadwhitacre** [comment] 2022-01-26 16:47
Okay, but are you on RDS? They were going to start force-upgrading people on January 18.

**Comment by ZedLove** [comment] 2022-01-26 18:07
We are not using RDS, postgres is using a docker volume. Sentry is running via `docker-compose` in EC2

**Comment by chadwhitacre** [comment] 2022-01-26 19:17
Hrm, another fantastic theory shot down by the facts. 🤔

Anyway, I'm glad you found a fix. That might be as far as we're able to get here. We're aware of [an index corruption issue related to `glibc`](https://postgresql.verite.pro/blog/2018/08/27/glibc-upgrade.html) but that seems unlikely to be the culprit, since the Postgres image we're using hasn't changed.

> I checked docker images and PostgreSQL versions 9.6 - 11 are using glibc 2.24, based on Debian 9 (stretch), starting PostgreSQL version 12, it is glibc 2.31, based on Debian 11 (bullseye). To move to PostgreSQL version 12 simple move data and pg_upgrade won't be enough and people will have to reindex.

I'm thinking I will close this for now. If anyone has additional info on a root cause, let's reopen to discuss a fix.

**Closed by chadwhitacre** 2022-01-26 19:17 UTC
Labels: Type: Support Request
