### ISSUE TITLE
Project IDs are changed after restoring from a backup

### ISSUE THREAD

**Issue by max-mycarly** [getsentry/self-hosted#2921] opened 2024-03-22 11:50 UTC
### Self-Hosted Version

24.3.0

### CPU Architecture

x86_64

### Docker Version

25.0.3

### Docker Compose Version

2.25.0

### Steps to Reproduce

Create several projects in sentry.
Project ID 1
DSN: https://HASH-1@sentry.domain.com/1

Project ID 2
DSN: https://HASH-2@sentry.domain.com/2

Project ID 3
DSN: https://HASH-3@sentry.domain.com/3

Project ID 4
DSN: https://HASH-4@sentry.domain.com/4

Delete one project. So you end up like this:

Project ID 1
DSN: https://HASH-1@sentry.domain.com/1

Project ID 2
DSN: https://HASH-2@sentry.domain.com/2

Project ID 4
DSN: https://HASH-4@sentry.domain.com/4

Create a backup.
```shell
cd $SENTRY_HOME;
scripts/backup.sh
``` 

Setup a new blank sentry instance and restore the backup.json
```shell
cd $SENTRY_HOME;
scripts/restore.sh
``` 

### Expected Result

After restoring the backup i would expect to have the same project again

Project ID 1
DSN: https://HASH-1@sentry.domain.com/1

Project ID 2
DSN: https://HASH-2@sentry.domain.com/2

Project ID 4
DSN: https://HASH-4@sentry.domain.com/4

### Actual Result

But after restoring the backup, project ids are not taken from the backup.json but created new.

Project ID 1
DSN: https://HASH-1@sentry.domain.com/1

Project ID 2
DSN: https://HASH-2@sentry.domain.com/2

Project ID 3
DSN: https://HASH-4@sentry.domain.com/3

It look like the projects are imported in the correct order but with a new auto-increment of the project id.
This breaks all DSN after the deleted project(s)
You have to than re-deploy the new DSN(s) to all of your projects.

Sentry is, after restoring a backup, not in the same state as before the backup.

**Comment by azaslavsky** [comment] 2024-03-25 18:42
This is a duplicate of https://github.com/getsentry/self-hosted/issues/2678. The fix is at https://github.com/getsentry/sentry/pull/67621, and should be merged in the next day or two. In the meantime, I'll mark this bug as a duplicate and continue tracking at #2678.

Thank you for the reminder to take a look at that bug (which had slipped from my todo list)! :)

**Closed** 2024-03-25 18:42 UTC
Labels: duplicate
