### ISSUE TITLE
Minimum requirements check fail when using docker compose v2.0.1

### ISSUE THREAD

**Issue by jsanagustin** [getsentry/self-hosted#1166] opened 2021-11-22 19:28 UTC
### Version

21.11.10

### Steps to Reproduce

./install.sh

### Expected Result

install script completes successfully

### Actual Result

```
$ ./install.sh
▶ Parsing command line ...

▶ Setting up error handling ...

▶ Checking minimum requirements ...
FAIL: Expected minimum docker-compose version to be 1.28.0 but found Docker Compose version v2.0.1

$ docker-compose --version
Docker Compose version v2.0.1

$ cat /etc/*-release
Rocky Linux release 8.4 (Green Obsidian)
```

**Comment by chadwhitacre** [comment] 2021-11-22 23:03
Duplicate of https://github.com/getsentry/self-hosted/issues/1132. Can you read that over and comment if you think we should reopen?

**Closed by chadwhitacre** 2021-11-22 23:03 UTC
Labels: Status: Untriaged

**Comment by jsanagustin** [comment] 2021-11-23 04:48
> Duplicate of #1132. Can you read that over and comment if you think we should reopen?

Yes, that looks to be the same problem I'm having.

In the last post you made on that issue, you seem to indicate that docker compose comes packaged with docker engine, which is not the case. At least, not when installing docker via docker's CentOS repository as detailed [here](https://docs.docker.com/engine/install/centos/#install-using-the-repository). After installing docker from their repo, I followed their instructions to install compose, as detailed [here](https://docs.docker.com/compose/install/#install-compose-on-linux-systems), substituting v2.0.1 instead of 1.29.2.
