### ISSUE TITLE
Tracked PHP issues are not getting marked as "New"

### ISSUE THREAD

**Issue by Physikbuddha** [getsentry/self-hosted#2026] opened 2023-03-13 07:35 UTC
### How do you use Sentry?

Self-hosted/on-premise

### Version

3.14.0

### Steps to Reproduce

Preamble:
This is my first time using Sentry, so I have no experience whatsoever about what is supposed to happen when you track an error from an actual project. The issue I am experiencing does not occurr on the `internal` project, where Sentry tracks its own errors, so I am suspecting the Sentry PHP SDK and reporting it here.

What I am experiencing: I am able to set up a PHP instance with the Sentry SDK and report issues to the Sentry server just fine.
But: All reported issues are not flagged as "new" on the Sentry server, and therefore no alert is created and reported at all.

I tried setting up a super simple PHP project with a Composer requirement just for `"sentry/sdk": "^3.3"`, and an `index.php` that's instantly throwing an Exception.

### Expected Result

From what I understand, the reported issues should be tracked within Sentry as "New", and an alert should be dispatched according to my rules set up in the Alerts sheet in Sentry.

### Actual Result

Issues are tracked just fine, and I can see all information (stacktrace, server infos, client infos, etc.) on the issue detail page.

But although this was the very first tracked issue in a freshly created project on a freshly installed Sentry server, it is not marked as "New":
![2023-03-13 08_25_52-Window](https://user-images.githubusercontent.com/8708554/224635500-1130022a-accb-47d3-9afb-de54c14fb6ee.png)

No alerts are dispatched for the test project as well. From what I understand, Sentry should be able to dispatch alerts just fine, as this happened for the `internal` project a while ago:
![2023-03-13 08_26_53-Window](https://user-images.githubusercontent.com/8708554/224635745-3b53fce1-f602-4c96-8d9c-5326eeac6117.png)

Using the most recent Sentry version 23.2.0, but also tried downgrading one version to 23.1.1 without success.

Is this a bug within the PHP SDK, or a misconfiguration on my side? I can't find anything related in the config.

**Comment by hubertdeng123** [comment] 2023-03-14 20:04
I think this may have something to do with snuba offsets as seen [here](https://github.com/getsentry/self-hosted/issues/1982). Can you check the offsets for `snuba-post-processor` group in kafka and report back?

**Comment by Physikbuddha** [comment] 2023-03-16 14:39
Thanks @hubertdeng123 for looking into this.

You helped me solving my original issue, but I'm left with another related problem now.
Let me explain:

While I was fiddling around with the PHP SDK three days ago, I accidentally sent a full envelope request to the `/store` endpoint. Since then, issues were getting marked as New with a lag of 1. By that, I mean that the _second last_ issue was processed (marked as New) when a new issue was reported to Sentry.

After some looking and research, I found [this post](https://github.com/getsentry/self-hosted/issues/478#issuecomment-666254392) and looked into the offsets. The `snuba-post-processor` offset was indeed lagging 1 behind. However, I tried setting the `current offset` to the `log end offset` by running `kafka-consumer-groups --bootstrap-server 127.0.0.1:9092 --group snuba-post-processor --topic events --reset-offsets --to-latest --execute`, but it had no effect. I verified that Kafka increased the current offset by 1, setting the lag to zero.

But as soon as the next issue went in, the lag was back to 1 again. I tried the same thing a few more times, but with no success.

Now that you asked me to check the offsets (again), I tried a more destructive approach and deleted the Docker volumes for Kafka and Clickhouse. And guess what: my original issue is solved. All issues from the PHP SDK are marked as new, just as they should.

However, I'm still faced by that "lag of 1" problem; it didn't get solved by resetting the Kafka/Clickhouse volumes. Is there anything I can do about that?

Since I'm still running a test/sandbox/playground instance of Sentry, it's not too big of a deal. I will destroy this and install a new Sentry instance eventually. But it might be helpful for others or me in the future to know what happened and how I can solve it.

Running `kafka-consumer-groups --bootstrap-server 127.0.0.1:9092 --group snuba-post-processor -describe` currently gives me this info:

```
GROUP                TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
snuba-post-processor events          0          6               7               1               rdkafka-8cc768cf-14c5-4079-8540-6c375e75e742 /172.31.0.26    rdkafka
snuba-post-processor transactions    0          -               0               -               rdkafka-702d1232-984b-4ae5-a266-3148f105ed8c /172.31.0.23    rdkafka
```

Running `kafka-consumer-groups --bootstrap-server 127.0.0.1:9092 --group snuba-post-processor --topic events --reset-offsets --to-latest --execute` seems to reset the issue:

```
GROUP                TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
snuba-post-processor events          0          7               7               0               rdkafka-8cc768cf-14c5-4079-8540-6c375e75e742 /172.31.0.26    rdkafka
snuba-post-processor transactions    0          -               0               -               rdkafka-702d1232-984b-4ae5-a266-3148f105ed8c /172.31.0.23    rdkafka
```

But as soon as the next issue flies in, the lag goes back to 1 again:
```
GROUP                TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
snuba-post-processor events          0          7               8               1               rdkafka-8cc768cf-14c5-4079-8540-6c375e75e742 /172.31.0.26    rdkafka
snuba-post-processor transactions    0          -               0               -               rdkafka-702d1232-984b-4ae5-a266-3148f105ed8c /172.31.0.23    rdkafka
```

**Comment by hubertdeng123** [comment] 2023-03-17 23:06
I've taken another opportunity to look into this issue. It seems like it's a regression that happened sometime between 22.10.0  till 23.3.0. It seems like there is no lag in 22.10.0. I'm going to continue investigating this but for now, please follow along here:
https://github.com/getsentry/self-hosted/issues/1982

Going to close this as this seems to be a duplicate and follow up there

**Closed by hubertdeng123** 2023-03-17 23:06 UTC
Labels: Type: Support Request
