### ISSUE TITLE
Login Redirect Problem

### ISSUE THREAD

**Issue by mohamedsamirspot** [getsentry/self-hosted#3473] opened 2024-12-16 09:39 UTC
### Self-Hosted Version

24.11.2

### CPU Architecture

x86_64

### Docker Version

27.4.0

### Docker Compose Version

v2.31.0

### Machine Specification

- [x] My system meets the minimum system requirements of Sentry

### Steps to Reproduce

git clone
./install.sh
update sentry/config.yml (mail configuration and system.url-prefix)
docker-compose up -d
login 
entering login credentials and mfa

### Expected Result

go to login page

### Actual Result

redirect to login page again

and the login page inspect give me

Refused to execute script from 'https://sentry.paymobsolutions.com/auth/login/paymob/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
Uncaught (in promise) ChunkLoadError: Loading chunk vendors-node_modules_emotion_react_jsx-runtime_dist_emotion-react-jsx-runtime_browser_esm_js--1f88a8 failed.
(error: https://sentry.paymobsolutions.com/_assets/chunks/vendors-node_modules_emotion_react_jsx-runtime_dist_emotion-react-jsx-runtime_browser_esm_js--1f88a8.b41be41ae296d09c51d4.js)
    at _.f.j (jsonp chunk loading:27:18)
    at ensure chunk:6:28
    at Array.reduce (<anonymous>)
    at _.e (ensure chunk:5:56)
    at e (index.tsx:73:31)
    at index.tsx:84:1
    at app.js:2:969
    at app.js:2:973
Refused to execute script from 'https://sentry.paymobsolutions.com/auth/login/paymob/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
Refused to execute script from 'https://sentry.paymobsolutions.com/auth/login/paymob/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
Refused to execute script from 'https://sentry.paymobsolutions.com/auth/login/paymob/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
Uncaught (in promise) ChunkLoadError: Loading chunk app_bootstrap_index_tsx failed.
(error: https://sentry.paymobsolutions.com/_assets/chunks/app_bootstrap_index_tsx.6b2bd37124aa38bf3f01.js)
    at _.f.j (jsonp chunk loading:27:18)
    at ensure chunk:6:28
    at Array.reduce (<anonymous>)
    at _.e (ensure chunk:5:56)
    at e (index.tsx:74:27)
    at index.tsx:84:1
    at app.js:2:969
    at app.js:2:973

**Comment by anthony-launay** [comment] 2024-12-16 14:12
Hi, same problem on our side

**Comment by Tom-jm03** [comment] 2024-12-16 15:16
This seems to be somehow related to two-factor auth. When I remove my 2fa from my account, the first login succeeds but as soon as I enable 2fa again, I'm getting redirected again.
You can disable 2fa for your account in the sentry shell (`sentry shell`) with the following code:

```python
from sentry.users.models.user import User, Authenticator

user = User.objects.get(email="your sentry account email")

Authenticator.objects.filter(user=user).delete()
```
This will allow you to login. If your organization has two-factor required, you will have to disable this as well, or you can only log in once.

**Comment by aldy505** [comment] 2024-12-17 02:28
I can't seem to reproduce this on a non-super admin user, both using http and https. My instance is behind a reverse proxy per [this haproxy config](https://develop.sentry.dev/self-hosted/experimental/reverse-proxy/#haproxy).

For everyone here: do you have any custom reverse proxy setup on top of the Sentry instance deployment? Usually that's the case when facing the MIME type mismatch/error.

**Comment by IdahoPL** [comment] 2024-12-17 11:30
> For everyone here: do you have any custom reverse proxy setup on top of the Sentry instance deployment? Usually that's the case when facing the MIME type mismatch/error.

My HAProxy config is quite vanilla and a problem with 2FA on 24.11.2 is present: https://pastebin.com/B2k5PGnZ

**Comment by mohamedsamirspot** [comment] 2024-12-17 11:34
> I can't seem to reproduce this on a non-super admin user, both using http and https. My instance is behind a reverse proxy per [this haproxy config](https://develop.sentry.dev/self-hosted/experimental/reverse-proxy/#haproxy).
> 
> For everyone here: do you have any custom reverse proxy setup on top of the Sentry instance deployment? Usually that's the case when facing the MIME type mismatch/error.

Yes i have, but the problem appears with me either accessing it from the reverse proxy through the domain tls or even accessing the sentry server ip with port 9000 directly without tls

**Comment by danielsawan** [comment] 2024-12-18 19:44
I have the same issue. I can no longer authenticate on Sentry since the last update. I have 2FA enabled, and I access Sentry through an Nginx reverse proxy.

**Comment by mohamedsamirspot** [comment] 2024-12-19 11:26
i found this temporary solution

docker exec -it sentry-self-hosted-web-1 bash
cd /usr/src/sentry/src/sentry/templates/sentry
apt update
apt install vim
vim layout.html
revert the changes of this from here https://github.com/getsentry/sentry/commit/595e9324c6b76f45dbd7afb10ff1ed2c155a4048

exit
docker restart sentry-self-hosted-web-1

**Comment by BYK** [comment] 2024-12-19 19:00
Hi all, apologies for the issue and our delayed response. @mohamedsamirspot's solution seems safe for now so if you need immediate access, you can try that.

We are now actively working on a diagnosis and fix.

**Comment by aldy505** [comment] 2024-12-20 03:48
For those that don't want to execute @mohamedsamirspot's solution above, you can try replacing your `SENTRY_IMAGE=getsentry/sentry:24.12.0` with `SENTRY_IMAGE=getsentry/sentry:3568f2fbe8c0f2008a7c7dfa2afa1b91160f0e55` on your `.env` file: https://github.com/getsentry/self-hosted/blob/6ba735824a6fc5780083b1f339c82fade81a98cd/.env#L9

Then, make sure to re-run the `./install.sh` script.

**Comment by nhayhoc** [comment] 2024-12-20 05:57
```

> For those that don't want to execute [@mohamedsamirspot](https://github.com/mohamedsamirspot)'s solution above, you can try replacing your `SENTRY_IMAGE=getsentry/sentry:24.12.0` with `SENTRY_IMAGE=getsentry/sentry:3568f2fbe8c0f2008a7c7dfa2afa1b91160f0e55` on your `.env` file:
> 
> [self-hosted/.env](https://github.com/getsentry/self-hosted/blob/6ba735824a6fc5780083b1f339c82fade81a98cd/.env#L9)
> 
> Line 9 in [6ba7358](/getsentry/self-hosted/commit/6ba735824a6fc5780083b1f339c82fade81a98cd)
> 
>  SENTRY_IMAGE=getsentry/sentry:24.12.0 
> Then, make sure to re-run the `./install.sh` script.

#SENTRY_IMAGE=getsentry/sentry:nightly
SENTRY_IMAGE=getsentry/sentry:3568f2fbe8c0f2008a7c7dfa2afa1b91160f0e55
SNUBA_IMAGE=getsentry/snuba:nightly
RELAY_IMAGE=getsentry/relay:nightly
SYMBOLICATOR_IMAGE=getsentry/symbolicator:nightly
VROOM_IMAGE=getsentry/vroom:nightly

and re-run the ./install.sh script and docker compose up -d
but still error

https://sentry.hide.org/organizations/sentry/issues/

app.js:1 
 GET https://sentry.hide.org/_static/dist/sentry/chunks/vendors-node_modules…t_emotion-react-jsx-runtime_browser_esm_js--1f88a8.05251cb….js net::ERR_ABORTED 404 (Not Found)
issues/:1 Refused to execute script from 'https://sentry.hide.org/_static/dist/sentry/chunks/vendors-node_modules…t_emotion-react-jsx-runtime_browser_esm_js--1f88a8.05251cb….js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
app.js:1 Uncaught (in promise) ChunkLoadError: Loading chunk vendors-node_modules_emotion_react_jsx-runtime_dist_emotion-react-jsx-runtime_browser_esm_js--1f88a8 failed.
(error: https://sentry.hide.org/_static/dist/sentry/chunks/vendors-node_modules…t_emotion-react-jsx-runtime_browser_esm_js--1f88a8.05251cb….js)
    at _.f.j (app.js:1:95835)
    at app.js:1:1481
    at Array.reduce (<anonymous>)
    at _.e (app.js:1:1460)
    at e (app.js:2:512)
    at app.js:2:964
    at app.js:2:969
    at app.js:2:973
app.js:1 
 GET https://sentry.hide.org/_static/dist/sentry/chunks/vendors-node_modules…_modules_query-string_index_js-node_modules-e4450d.c6c640b….js net::ERR_ABORTED 404 (Not Found)
issues/:1 Refused to execute script from 'https://sentry.hide.org/_static/dist/sentry/chunks/vendors-node_modules…_modules_query-string_index_js-node_modules-e4450d.c6c640b….js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
app.js:1 
 GET https://sentry.hide.org/_static/dist/sentry/chunks/app_bootstrap_index_tsx.8447983….js net::ERR_ABORTED 404 (Not Found)
issues/:1 Refused to execute script from 'https://sentry.hide.org/_static/dist/sentry/chunks/app_bootstrap_index_tsx.8447983….js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
app.js:1 Uncaught (in promise) ChunkLoadError: Loading chunk app_bootstrap_index_tsx failed.
(error: https://sentry.hide.org/_static/dist/sentry/chunks/app_bootstrap_index_tsx.8447983….js)
    at _.f.j (app.js:1:95835)
    at app.js:1:1481
    at Array.reduce (<anonymous>)
    at _.e (app.js:1:1460)
    at e (app.js:2:825)
    at app.js:2:964
    at app.js:2:969
    at app.js:2:973
app.js:1 
 GET https://sentry.hide.org/_static/dist/sentry/chunks/app_bootstrap_initializeMain_tsx.9737ae8….js net::ERR_ABORTED 404 (Not Found)
issues/:1 Refused to execute script from 'https://sentry.hide.org/_static/dist/sentry/chunks/app_bootstrap_initializeMain_tsx.9737ae8….js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

**Comment by BYK** [comment] 2024-12-20 20:07
@nhayhoc we just merged another, more comprehensive fix for the issue which should now resolve the core problem. The image tag is `fd99887982f76d67d6957f6acc06b8da6f8a91de`, so `getsentry/sentry:fd99887982f76d67d6957f6acc06b8da6f8a91de` will be the new image name.

In addition, to fix the JS issues, we landed a small patch to the `nginx.conf` file in the self-hosted repo. You should be easily apply that manually while we coordinate a new hotfix release (24.12.2).

**Comment by aldy505** [comment] 2024-12-20 22:42
I'm going to reopen this issue until people confirmed that the new image tag works.

Your `.env` should be:
```bash
SENTRY_IMAGE=getsentry/sentry:fd99887982f76d67d6957f6acc06b8da6f8a91de
SNUBA_IMAGE=getsentry/snuba:24.12.0
RELAY_IMAGE=getsentry/relay:24.12.0
SYMBOLICATOR_IMAGE=getsentry/symbolicator:24.12.0
VROOM_IMAGE=getsentry/vroom:24.12.0
```

Then, make sure to re-run `./install.sh` script.

**Comment by bashgeek** [comment] 2024-12-21 07:50
Hooray, I can login again with the mentioned image.

**Comment by BYK** [comment] 2024-12-21 12:50
@aldy505 I confirmed that with the latest Sentry image _and_ the amended nginx config in this repo, things are back to normal. Since we also got an independent confirmation from @bashgeek, I'm gonna close the issue.

Quite sure there's one last instance of a missing `__initialData` in the 2FA callback that causes the issue without the nginx patch so I'll bake that in later on.

I'll try to cut a patch release today.

**Closed by BYK** 2024-12-21 12:50 UTC
Labels: Type: Bug

**Comment by alekseyp** [comment] 2024-12-22 02:31
I'm now running `24.12.1` and getting 

```
Uncaught (in promise) TypeError: (intermediate value) is not iterable
    at C (app_actionCreators_pageFilters_tsx-app_actionCreators_redirectToProject_tsx-app_actionCreator-16ee7b.ea3c729d29e7fa083105.js:1:1)
    at nf (initializeApp.tsx:12:3)
    at R (initializeMain.tsx:15:3)
```

when 2FA enabled

**Comment by BYK** [comment] 2024-12-22 11:32
@alekseyp does it prevent you from logging in?

I've identified one last piece that needs fixing but cut the release before that as I was able to confirm they were enough to fix the login issues.

**Comment by alekseyp** [comment] 2024-12-22 19:58
Yes it does prevent the login, since 2fa window is not shown, but I haven't tried disabling 2FA via cli yet. Will try tomorrow.

**Comment by BYK** [comment] 2024-12-22 20:45
@alekseyp sorry to hear that. Can you verify that you have the `nginx.conf` update also applied and loaded? I was able to login to our test instance for self-hosted which also uses 2FA.

**Comment by alekseyp** [comment] 2024-12-23 13:39
Confirmed that's it's using latest nginx. I don't see any asset access errors. I'm using hardware 2fa, and you probably tested with OTPs, right?

**Comment by BYK** [comment] 2024-12-23 14:41
@alekseyp ugh, you are right and the patch we just merged should fix that too.

Can you try with `getsentry/sentry:d139b578ed0ecfeca23dd69d4d98e39384ad4047` image? If that works I'll have to cut another patch release 😅

**Comment by alekseyp** [comment] 2024-12-25 14:36
@BYK confirmed, `d139b578ed0ecfeca23dd69d4d98e39384ad4047` works on hardware 2FA.

**Comment by BYK** [comment] 2024-12-25 17:48
@alekseyp would it be trouble for you to run off of that image until 25.1.0 as it would probably be challenging to cut a new release during the holiday period?

**Comment by alekseyp** [comment] 2024-12-25 22:51
I'm ok to run it until next release. 
Happy holidays!
