### ISSUE TITLE
SyntaxError: Invalid character '\u001f' in Safari 17.0

### ISSUE THREAD

**Issue by soer7022** [getsentry/self-hosted#2296] opened 2023-07-25 13:47 UTC
### Self-Hosted Version

23.8.0.dev0 c3248ce

### CPU Architecture

x86_64

### Docker Version

24.0.2

### Docker Compose Version

2.18.1

### Steps to Reproduce

Not exactly sure how to reproduce. I was trying to upgrade from 23.7.0 nightly to 23.8.0 nightly

I stashed my docker compose changes (am running a traefik load balancer in front) and git pulled, and reapplied my stash. No conflicts, no nothing.

Then I ran `sudo ./install.sh` to upgrade, as stated on https://develop.sentry.dev/self-hosted/releases/#upgrading

When the page came back on line it was just hanging on the page, telling me to disable ad blocker. Which I already did.

When I look in the console, I get the following:
![Screenshot 2023-07-25 at 15 46 26](https://github.com/getsentry/self-hosted/assets/17567175/f925adea-4737-465d-995d-2829a85294ff)
It does however work in Google Chrome.

I tried to downgrade by pulling the 23.7.0 tag. but that broke both chrome and safari.

Any ideas?

### Expected Result

I expect it to work in safari

### Actual Result

```
[Error] The Content Security Policy directive 'frame-ancestors' is ignored when delivered in a report-only policy.
[Error] The Content Security Policy 'object-src 'none'; connect-src 'self'; default-src 'none'; img-src 'self' blob: data: https://secure.gravatar.com; script-src 'self' 'unsafe-inline' 'report-sample' 'nonce-LhD73Pqg+VEjNr4g9ctkQA=='; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'; font-src 'self' data:' was delivered in report-only mode, but does not specify a 'report-to'; the policy will have no effect. Please either add a 'report-to' directive, or deliver the policy via the 'Content-Security-Policy' header.
[Log] [Wipr Extra 1.43] Not required on this domain (wipr-extra.js, line 2)
[Error] [Report Only] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (performance, line 0)
[Error] Failed to load resource: You do not have permission to access the requested resource.
[Error] SyntaxError: Invalid character '\u001f'
	(anonymous function) (app.js:1)
```

**Comment by hubertdeng123** [comment] 2023-07-25 22:02
Closing as a duplicate of https://github.com/getsentry/self-hosted/issues/2285, which has been fixed

**Closed by hubertdeng123** 2023-07-25 22:02 UTC
Labels: Waiting for: Product Owner
