### ISSUE TITLE
replay/build/npm/esm/index timestamp error

### ISSUE THREAD

**Issue by thenitai** [getsentry/self-hosted#2870] opened 2024-03-08 11:52 UTC
### Self-Hosted Version

24.3.0.dev0

### CPU Architecture

amd

### Docker Version

25.0.4

### Docker Compose Version

2.24.7

### Steps to Reproduce

loaded self-hosted sdk as per replay page

### Expected Result

working :)

### Actual Result

![2024-03-08 at 06 51 27](https://github.com/getsentry/self-hosted/assets/372121/bafb014b-2573-40c8-8038-3b7cb69688b9)

![2024-03-08 at 06 51 49](https://github.com/getsentry/self-hosted/assets/372121/7141b382-8593-4147-b2b8-0203f2013e45)

**Comment by hubertdeng123** [comment] 2024-03-11 22:03
Could you give some more details here? Have you upgraded to the latest version of the javascript SDK that you're using? When does this error occur?

**Comment by thenitai** [comment] 2024-03-12 19:36
> Could you give some more details here? Have you upgraded to the latest version of the javascript SDK that you're using? When does this error occur?

Hi,

Yes, we are on the latest main branch. We use the SDK with a statement in the sentry.conf.py file:
```
JS_SDK_LOADER_DEFAULT_SDK_URL = "https://browser.sentry-cdn.com/%s/bundle.tracing.replay.min.js"
```
I don't know when the error occurs. It's being logged in our Sentry instance.

For the record, including or not including the above line in the sentry.conf file doesn't get the relay option to work. That just never works :(

**Comment by thenitai** [comment] 2024-03-14 16:12
> Got it, is this an error that is logged to your internal project in Sentry?

Yep, hence the screenshot :)

**Comment by thenitai** [comment] 2024-03-19 17:36
> Now that I think of it, this may be related to this issue here:
> 
> [getsentry/sentry#22715](https://github.com/getsentry/sentry/issues/22715)
> 
> > For the record, including or not including the above line in the sentry.conf file doesn't get the relay option to work. That just never works :(
> 
> Does the error show up if you omit this?
> 
> ```
> JS_SDK_LOADER_DEFAULT_SDK_URL = "https://browser.sentry-cdn.com/%s/bundle.tracing.replay.min.js"
> ```

Yep, the error is gone when the line is omitted.

**Comment by hubertdeng123** [comment] 2024-03-20 22:40
In that case, this issue should be closed as a duplicate of the one above. There is a community submitted solution if you are interested in giving that a shot:
https://github.com/getsentry/sentry/issues/22715#issuecomment-926385843

**Closed by hubertdeng123** 2024-03-20 22:40 UTC
Labels: Waiting for: Product Owner

**Comment by thenitai** [comment] 2024-03-21 01:05
> In that case, this issue should be closed as a duplicate of the one above. There is a community submitted solution if you are interested in giving that a shot: [getsentry/sentry#22715 (comment)](https://github.com/getsentry/sentry/issues/22715#issuecomment-926385843)

No, it's not a duplicate! The issue is that the library throws an error when it is included!

But hey, I'm just reporting.
