### ISSUE TITLE
Sentry Replay works for a few hours and then no longer saves data.

### ISSUE THREAD

**Issue by billni** [getsentry/self-hosted#2555] opened 2023-11-08 09:44 UTC
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

The replay function is enabled for sentry deployed in self_hosted mode. But after working normally, the replay no longer saves data. Restart the entire sentry, and the data will be saved, but after a few hours of work, the data will not be saved. What is the cause of this and how can it be fixed?

### Expected Result

to save data.

### Actual Result

no save data

### Product Area

Replays

### Version

Sentry 23.5.1

**Comment by billni** [comment] 2023-11-09 08:59
In addition, the replays_replayrecordingsegment data is saved in postgres, and the relevant records can be found, but the relevant records are not displayed on the web page.

**Comment by azaslavsky** [comment] 2023-11-09 21:42
Can you please provide the information listed on [this](https://github.com/getsentry/self-hosted/issues/new?assignees=&labels=&projects=&template=problem-report.yml) form (CPU architecture, Sentry/Docker version, etc)? It's a bit difficult to debug this issue otherwise.

**Comment by billni** [comment] 2023-11-21 06:19
> Can you please provide the information listed on [this](https://github.com/getsentry/self-hosted/issues/new?assignees=&labels=&projects=&template=problem-report.yml) form (CPU architecture, Sentry/Docker version, etc)? It's a bit difficult to debug this issue otherwise.
(1) cpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-26xx v3
Stepping:              2
CPU MHz:               2299.996
BogoMIPS:              4599.99
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0,1

(2)Docker version 24.0.4, build 3713ee1
(3) sentry version:
<img width="861" alt="sentry" src="https://github.com/getsentry/self-hosted/assets/2441899/55aaa3db-9e11-47e8-b35d-25900840c3be">

**Comment by hubertdeng123** [comment] 2023-11-22 21:30
This is a duplicate of https://github.com/getsentry/self-hosted/issues/2379

We are aware of this, but haven't been able to prioritize this. Closing as duplicate

**Closed by hubertdeng123** 2023-11-22 21:30 UTC
Labels: Waiting for: Product Owner
