### ISSUE TITLE
No option to disable django admin page

### ISSUE THREAD

**Issue by cement-cloud** [getsentry/self-hosted#1922] opened 2023-01-18 17:46 UTC
### Self-Hosted Version

Sentry 22.4.0

### CPU Architecture

x86_64

### Docker Version

20.10.12

### Docker Compose Version

1.29.2

### Steps to Reproduce

https://forum.sentry.io/t/sentry-django-admin-portal/12787

1.) ADMIN_ENABLED option not found in sentry.conf.py
2.) Adding ADMIN_ENABLED = False in sentry.conf.py has no effect. 
3.) I would like to completely disable this login page. 

### Expected Result

ADMIN_ENABLED = False in sentry.conf.py disables the https://sentry.mydomain.com/admin/login/?next=/admin portal login. 

### Actual Result

Adding ADMIN_ENABLED = False in sentry.conf.py has no effect.

**Comment by hubertdeng123** [comment] 2023-01-18 23:04
Seems to be a duplicate of https://github.com/getsentry/self-hosted/issues/1039

**Comment by hubertdeng123** [comment] 2023-01-18 23:05
Can you comment there? Closing this as a duplicate

**Comment by hubertdeng123** [comment] 2023-01-18 23:06
This doesn't seem to be very high priority, although it definitely still seems to be an issue.

**Closed by hubertdeng123** 2023-01-18 23:05 UTC
Labels: Type: Support Request
