### ISSUE TITLE
Install Script | Migrations are failing

### ISSUE THREAD

**Issue by LvckyAPI** [getsentry/self-hosted#2746] opened 2024-01-29 09:35 UTC
### Environment

Self Hosted

### Steps to Reproduce

Upgrade from 24.1.0 to 24.1.1

### Expected Result

Migrations are running without problems.

### Actual Result

```bash
  File "/usr/local/lib/python3.10/site-packages/django/core/cache/__init__.py", line 49, in create_connection
    raise InvalidCacheBackendError(
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django.core.cache.backends.memcached.MemcachedCache': Module "django.core.cache.backends.memcached" does not define a "MemcachedCache" attribute/class
Error in install/set-up-and-migrate-database.sh:4.
'$dcr web upgrade --noinput' exited with status 1
-> ./install.sh:main:34
--> install/set-up-and-migrate-database.sh:source:4
```

[Sentry-LOG.txt](https://github.com/getsentry/sentry/files/14082350/Sentry-LOG.txt)

### Product Area

Unknown

**Comment by hubertdeng123** [comment] 2024-01-29 19:04
duplicate of https://github.com/getsentry/self-hosted/issues/2728

**Closed by hubertdeng123** 2024-01-29 19:04 UTC
