### ISSUE TITLE
Missing Discover Icon

### ISSUE THREAD

**Issue by JonPurvis** [getsentry/self-hosted#3323] opened 2024-09-12 10:47 UTC
### Self-Hosted Version

24.8.0

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.29.2

### Steps to Reproduce

1. Go to Dashboard
2. Look at Discover Link in menu
3. You should see a dot instead of an icon

I'm running on an Errors Only Sentry instance, not sure if that has any bearing.

### Expected Result

In previous versions of Sentry, this is a telescope.

### Actual Result

![Image](https://github.com/user-attachments/assets/0b877956-6699-4785-a4e6-ab8ab0c120db)

**Comment by hubertdeng123** [comment] 2024-09-13 22:14
Thanks for reporting this! I believe this regression was introduced when we reworked the sidebar for Sentry

**Comment by aldy505** [comment] 2024-09-17 02:29
Just dug around. This is not a bug, see this line:

https://github.com/getsentry/sentry/blob/fa5c96d58debe2db4f3b1c8896f6944988d73904/static/app/components/sidebar/index.tsx#L243

Compared to the previous change that has `<IconTelescope>` component on it:

https://github.com/getsentry/sentry/blob/ccb3c648d0d065bfe84840d1956fb0a9f5ab3544/static/app/components/sidebar/index.tsx#L236

**Comment by ryan953** [comment] 2024-12-11 00:02
cc @gggritso who made that sidebar update

**Comment by JonPurvis** [comment] 2024-12-11 01:03
@gggritso please could you fix the icon, it's bugging me more than it should be 😆 😢

**Comment by gggritso** [comment] 2024-12-11 19:25
@JonPurvis wow that _is_ annoying! Yes, I'll fix this. 

> I'm running on an Errors Only Sentry instance, not sure if that has any bearing.

This is very helpful 👍🏻

**Comment by gggritso** [comment] 2024-12-11 21:21
@JonPurvis fix will be in the next release of `self-hosted`! Thanks for raising this 👍🏻

**Closed** 2024-12-11 21:20 UTC
