### ISSUE TITLE
Error in bootstrap-snuba.sh:3.

### ISSUE THREAD

**Issue by piotranon** [getsentry/self-hosted#1876] opened 2022-12-21 09:27 UTC
### Self-Hosted Version

22.12.0

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

2.12.2

### Steps to Reproduce

Start an install with `./install.sh`

### Expected Result

Installation succesfull

#### Logs
- sentry install logs: https://pastebin.com/raw/67UB5THS
- docker compose logs: https://pastebin.com/raw/vg9DLzz9

#### Other Logs
- clickhouse https://pastebin.com/raw/SMnByNAn
- zookeper https://pastebin.com/raw/HrpBnFUY
- kafka empty
- redis https://pastebin.com/raw/uaih5YNK

#### Started Containers
![image](https://user-images.githubusercontent.com/40769535/208873494-4ed94f6f-5651-46d3-a920-d57ca350ef5a.png)

#### System Info
Ram: 7.75G
Disk: 31G (used 6,4G)

**Comment by hubertdeng123** [comment] 2022-12-21 18:00
This seems to be a duplicate of the issue here so closing this.
https://github.com/getsentry/self-hosted/issues/1876. 

Can you follow up there and see if that's helpful?

**Closed by hubertdeng123** 2022-12-21 18:00 UTC
Labels: Status: Untriaged

**Comment by piotranon** [comment] 2022-12-21 22:09
> This seems to be a duplicate of the issue here so closing this. #1876.
> 
> Can you follow up there and see if that's helpful?

Can you provide the issue id because you linked my issue.

**Comment by hubertdeng123** [comment] 2022-12-21 22:11
ah yes, sorry it is https://github.com/getsentry/self-hosted/issues/1828
