### ISSUE TITLE
Increased CPU usage with 21.10.0

### ISSUE THREAD

**Issue by boutetnico** [getsentry/self-hosted#1141] opened 2021-11-10 08:14 UTC
### Version

21.10.0

### Steps to Reproduce

1. Install 21.9.0
2. Collect CPU metrics
3. Upgrade to 21.10.0
4. Notice an increased CPU usage

### Expected Result

CPU usage remains the same

### Actual Result

CPU usage has increased which caused AWS CPU credits balance to drop.
<img width="1343" alt="sentry-credits-usage" src="https://user-images.githubusercontent.com/973739/141075103-6493ed81-0def-4ec6-b752-1c5a090bdfc1.png">

**Comment by chadwhitacre** [comment] 2021-11-10 13:39
That's a pretty compelling graph. 😅 Which of the containers is responsible for the spike?

**Comment by chadwhitacre** [comment] 2021-11-18 15:42
@aminvakil we didn't introduce https://github.com/getsentry/symbolicator/issues/580 until after 21.10.0, correct?

**Comment by aminvakil** [comment] 2021-11-18 15:46
> @aminvakil We didn't introduce [getsentry/symbolicator#580](https://github.com/getsentry/symbolicator/issues/580) until after 21.10.0, correct?

Yes and no, it's not even merged to master yet :)
It got merged to a different branch to get tested for now.

**Comment by chadwhitacre** [comment] 2021-11-18 16:51
> It got merged to a different branch to get tested for now.

Ah, seeing that now. I wondered about the state of Symbolicator post-[#578](https://github.com/getsentry/symbolicator/pull/578) given [#580](https://github.com/getsentry/symbolicator/pull/580), but I figured you and @flub had it under control. I was right! :-)

@boutetnico I guess we still need more info on which container is consuming CPU to be able to debug further.

**Comment by renchap** [comment] 2021-11-23 14:11
I am seeing a similar behaviour after updating from 21.9.0 to 21.10.0. The server is only running Sentry.
The behaviour below does not seem related to the Sentry trafic or usage (which is not much).

General CPU usage

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/42070/143036960-f2a983a4-8706-44b0-9424-fdad8d4b1208.png">


In addition to the increased base CPU usage, I also see CPU usage spiked at various times
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/42070/143037174-733cd2d8-af8c-4171-b9f9-959fdda17722.png">

Here over the last hour
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/42070/143037331-24cb2822-8899-46af-b92c-d8398a81ef6d.png">

After investigating a bit, it looks like the spikes in CPU usage are caused by these processes:
- `/usr/local/bin//python /usr/local/bin/sentry run post-process-forwarder --commit-batch-size 1 `
- `/usr/local/bin/python /usr/local/bin/sentry run worker`

CPU usage for this process over the last hour:
<img width="539" alt="image" src="https://user-images.githubusercontent.com/42070/143039194-9f0a049a-0428-41b1-a2d3-91d75a6cef2b.png">

I have not looked at the general CPU usage increase, but those spikes are currently triggering our monitoring as CPU goes to 100% several times a day.

**Comment by renchap** [comment] 2021-11-23 17:18
@chadwhitacre after reading #1131 I checked my internal project and we also have those `SoftTimeLimitExceeded` errors, and they seem to correlate with the CPU spikes.
It looks like a job is launched periodically, uses all the CPU and then gets terminated with `SoftTimeLimitExceeded`.

**Comment by chadwhitacre** [comment] 2021-11-23 22:27
Thanks for confirming, @renchap. Let's consolidate tickets, then. Closing this one as a dupe since it was created later. See you on #1131!

**Closed by chadwhitacre** 2021-11-23 22:27 UTC
Labels: Status: Needs More Information
