### ISSUE TITLE
ZooKeeper reports unhealthy when installing Sentry on Fedora 36

### ISSUE THREAD

**Issue by jyxjjj** [getsentry/self-hosted#1677] opened 2022-08-31 17:07 UTC
### Self-Hosted Version

22.8.0

### CPU Architecture

x86_64

### Docker Version

20.10.17, build 100c701

### Docker Compose Version

2.6.0

### Steps to Reproduce

1. Run `./install.sh` in Fedora 36 - very clean environment.

### Expected Result

Sentry installed successfully.

### Actual Result

```
▶ Bootstrapping and migrating Snuba ...
Container sentry-self-hosted-zookeeper-1  Creating
Container sentry-self-hosted-redis-1  Creating
Container sentry-self-hosted-clickhouse-1  Creating
Container sentry-self-hosted-redis-1  Created
Container sentry-self-hosted-zookeeper-1  Created
Container sentry-self-hosted-kafka-1  Creating
Container sentry-self-hosted-clickhouse-1  Created
Container sentry-self-hosted-kafka-1  Created
Container sentry-self-hosted-redis-1  Starting
Container sentry-self-hosted-clickhouse-1  Starting
Container sentry-self-hosted-zookeeper-1  Starting
Container sentry-self-hosted-zookeeper-1  Started
Container sentry-self-hosted-zookeeper-1  Waiting
Container sentry-self-hosted-clickhouse-1  Started
Container sentry-self-hosted-redis-1  Started
container for service "zookeeper" is unhealthy
An error occurred, caught SIGERR on line 3
Cleaning up...

```

Always reports with zookeeper broken.

I found it due to docker default `LimitNOFILE` too large.

**Useless ways:**

1. Set it in `/etc/systemd/system/docker.service`
2. Set it via system configration
3. Set it via `ulimit -n`

Right way to fix it:

**MUST** manually set it via `dockerd` command line:

```
 --default-ulimit nproc=1024:2048 --default-ulimit nofile=20480:40960
```

```
[root@fedora sentry]# systemctl cat docker.service 
# /etc/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network-online.target docker.socket firewalld.service containerd.service
Wants=network-online.target
Requires=docker.socket containerd.service

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --default-ulimit nproc=1024:2048 --default-ulimit nofile=20480:40960
ExecReload=/bin/kill -s HUP $MAINPID
TimeoutSec=0
RestartSec=2
Restart=always

# Note that StartLimit* options were moved from "Service" to "Unit" in systemd 229.
# Both the old, and new location are accepted by systemd 229 and up, so using the old location
# to make them work for either version of systemd.
StartLimitBurst=3

# Note that StartLimitInterval was renamed to StartLimitIntervalSec in systemd 230.
# Both the old, and new name are accepted by systemd 230 and up, so using the old name to make
# this option work for either version of systemd.
StartLimitInterval=60s

# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=20480:40960
LimitNPROC=1024:2048
LimitCORE=infinity

# Comment TasksMax if your systemd version does not support it.
# Only systemd 226 and above support this option.
TasksMax=infinity

# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes

# kill only the docker process, not all processes in the cgroup
KillMode=process
OOMScoreAdjust=-500

[Install]
WantedBy=multi-user.target
```

**Comment by hubertdeng123** [comment] 2022-08-31 18:24
Sorry to hear you are having issues with our `./install.sh` script. Occasionally, the error message `container for service "zookeeper" is unhealthy` pops up during installation but usually disappears during consequent runs 😬. 

Could you give us more information in how you were able to determine that the `LimitNOFILE` as the root cause of the issue?

**Comment by jyxjjj** [comment] 2022-09-01 04:18
I ran zookeeper only, via command docker run, without any parameters, then it still unhealthy, I searched both Google and GitHub, then someone said that about ulimit, (sorry for that i cannot remember which page or link) then i tried docker run zookeeper via command /bin/bash to execute ulimit -n, it is infinity, so then i trying to reduce it to 1024, then zookeeper works. Then i trying to set the global docker settings like the things main content had said.
After that, problem solved.

**Comment by hubertdeng123** [comment] 2022-09-01 18:07
Got it, I'm glad you were able to resolve this on your own and thanks for bringing this issue up to us. Editing the `dockerd` in command line seems like a great way to remedy the issue in this scenario but it's not clear to me that this is an issue on our side versus the docker setup on your local machine. 

Ideally we'd like to be completely sure that this is an issue that will not create further regressions down the line before implementing this change, so I'll be closing this.

**Closed by hubertdeng123** 2022-09-01 18:07 UTC
Labels: Type: CI Flakiness

**Comment by aminvakil** [comment] 2022-09-02 10:56
For future reference, we have tracked this issue with much more detail in https://github.com/getsentry/self-hosted/issues/1445 .
