### ISSUE TITLE
Jira Integration Problem

### ISSUE THREAD

**Issue by mmoitatchiou** [getsentry/self-hosted#3093] opened 2024-05-28 18:57 UTC
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

https://forum.sentry.io/t/how-to-configure-jira-cloud-in-your-on-premise-sentry/6720

### Expected Result

Integrate with Jira

### Actual Result

![image](https://github.com/getsentry/sentry/assets/147549997/a7fbccd8-eed8-43e0-a95b-c7f291e9bf01)

### Product Area

Settings - Integrations

**Comment by hubertdeng123** [comment] 2024-05-30 21:38
This seems to be a duplicate issue of https://github.com/getsentry/sentry/issues/59381, is that correct?

**Comment by mmoitatchiou** [comment] 2024-05-31 14:15
Not sure, but we using jira cloud and sentry self hosted

**Comment by azaslavsky** [comment] 2024-06-03 20:03
I believe this is a duplicate of that issue. I'll reach out to the owner there, and mark this is as a dup.

**Closed** 2024-06-03 20:03 UTC
Labels: duplicate

**Comment by mmoitatchiou** [comment] 2024-06-03 20:49
The problem still exists
