### ISSUE TITLE
Sentry Queries

### ISSUE THREAD

**Issue by finoghentov** [getsentry/self-hosted#2615] opened 2023-12-01 16:22 UTC
### Self-Hosted Version

23.10.1

### CPU Architecture

x86_64

### Docker Version

20.10.16

### Docker Compose Version

2.6.0

### Steps to Reproduce

1) Added new feature: organizations:performance-database-view

### Expected Result

1) Expected that it should work, but its not working on self hosted version. But if I switch to cloud, it works perfect

### Actual Result

![image](https://github.com/getsentry/self-hosted/assets/45954128/a696a5c1-adcf-41a8-bf90-adc6acd0f74c)

**Comment by hubertdeng123** [comment] 2023-12-04 21:47
Duplicate of https://github.com/getsentry/self-hosted/issues/2545, so closing this

**Closed by hubertdeng123** 2023-12-04 21:47 UTC
Labels: Waiting for: Product Owner
