### ISSUE TITLE
Jira server  integration

### ISSUE THREAD

**Issue by zwskymoon** [getsentry/self-hosted#2157] opened 2023-05-19 08:25 UTC
### Self-Hosted Version

22.11.0

### CPU Architecture

x86_64

### Docker Version

20.10.7

### Docker Compose Version

1.29.2

### Steps to Reproduce

1.install jira server (my jira server version is 9.4.3)
2.click "Jira Server Issue" button in issue detail page.
![image](https://github.com/getsentry/self-hosted/assets/26498964/92427da1-78c3-4306-8ae7-94fc342325b4)

### Expected Result

create a jira server link.

### Actual Result

![image](https://github.com/getsentry/self-hosted/assets/26498964/72ab2df6-108b-422a-bf2f-b78f464cd8bb)

**Comment by hubertdeng123** [comment] 2023-05-22 17:45
duplicate of https://github.com/getsentry/self-hosted/issues/2153, followed up there

**Closed by hubertdeng123** 2023-05-22 17:45 UTC
Labels: Status: Untriaged
