### ISSUE TITLE
Quick backup contains irrelevant debug log entries despite correct run flags

### ISSUE THREAD

**Issue by GingerAdonis** [getsentry/self-hosted#1111] opened 2021-10-08 15:00 UTC
### Version
21.9.0

### Environment
```
OS: Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-77-generic x86_64)
Docker version 20.10.7, build 20.10.7-0ubuntu1~20.04.1
docker-compose version 1.29.2, build 5becea4c
```

### Steps to Reproduce
1. Setup Sentry with a few projects.
2. Run _Quick backup_ as mentioned [in the documentation](https://develop.sentry.dev/self-hosted/backup/).

The documentation warns about this behavior when omitting certain flags. But it still happens when I run the proper example command.

### Expected Result
Proper JSON file without extra debug log entries.

### Actual Result
JSON file which looks correct apart from a couple of debug log entries:

```
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
```

**Comment by tarak** [comment] 2023-01-19 12:34
Still seeing this on 22.12.0

**Comment by ethanhs** [comment] 2023-01-25 02:06
This is a duplicate of https://github.com/getsentry/sentry/issues/36868, which has more discussion, so I am going to close in favor of that issue.

**Closed by ethanhs** 2023-01-25 02:06 UTC
Labels: Status: Backlog
