### ISSUE TITLE
Can not install with docker-compose version v2.1.1

### ISSUE THREAD

**Issue by x2x4com** [getsentry/self-hosted#1180] opened 2021-12-01 06:15 UTC
### Version

21.11.0

### Steps to Reproduce

1. download
2. run install.sh

### Expected Result

$ ./install.sh
▶ Parsing command line ...

▶ Setting up error handling ...

▶ Checking minimum requirements ...
FAIL: Expected minimum docker-compose version to be 1.28.0 but found Docker Compose version v2.1.1

### Actual Result

+++ docker version --format '{{.Server.Version}}'
++ DOCKER_VERSION=20.10.7
++ docker compose version
+++ docker-compose --version
+++ sed 's/docker-compose version \(.\{1,\}\),.*/\1/'
++ COMPOSE_VERSION='Docker Compose version v2.1.1'
+++ docker run --rm busybox free -m
+++ awk '/Mem/ {print $2}'
++ RAM_AVAILABLE_IN_DOCKER=15537
+++ docker run --rm busybox nproc --all
++ CPU_AVAILABLE_IN_DOCKER=8
+++ ver 20.10.7
+++ echo 20.10.7
+++ awk -F. '{ printf("%d%03d%03d", $1,$2,$3); }'
+++ ver 19.03.6
+++ echo 19.03.6
+++ awk -F. '{ printf("%d%03d%03d", $1,$2,$3); }'
++ [[ 20010007 -lt 19003006 ]]
+++ ver Docker Compose version v2.1.1
+++ echo Docker Compose version v2.1.1
+++ awk -F. '{ printf("%d%03d%03d", $1,$2,$3); }'
+++ ver 1.28.0
+++ echo 1.28.0
+++ awk -F. '{ printf("%d%03d%03d", $1,$2,$3); }'
++ [[ 0001001 -lt 1028000 ]]
++ echo 'FAIL: Expected minimum docker-compose version to be 1.28.0 but found Docker Compose version v2.1.1'
FAIL: Expected minimum docker-compose version to be 1.28.0 but found Docker Compose version v2.1.1
++ exit 1
+ cleanup EXIT 1

in check-minimum-requirements.sh line 11

COMPOSE_VERSION=$(docker-compose --version | sed 's/docker-compose version \(.\{1,\}\),.*/\1/i')

but docker-compose version 2.1.1 return

Docker Compose version v2.1.1

**Comment by aminvakil** [comment] 2021-12-01 07:38
Duplicate of https://github.com/getsentry/self-hosted/issues/1132

**Closed by aminvakil** 2021-12-01 07:38 UTC
Labels: Status: Untriaged
