### ISSUE TITLE
Events taking a long time (after being registered) to show up under an alert

### ISSUE THREAD

**Issue by musabstellic** [getsentry/self-hosted#1982] opened 2023-02-23 22:17 UTC
### Self-Hosted Version

23.2.0

### CPU Architecture

x86_64

### Docker Version

23.0.1

### Docker Compose Version

1.29.2

### Steps to Reproduce

I have an out of the box installation + an nginx proxy for SSL.
I have set up a fairly basic alert to capture errors and forward them to Slack.

### Expected Result

The error should be picked up by the alert "instantly."

Is there any logging around which events are being picked up under an alert, which ones aren't, and why?

### Actual Result

Sentry is consuming errors from all our servers perfectly smoothly but the errors take a while to show up under the alerts. In some cases up to 45 minutes. Note that they are working, just taking a long time, and showing up in batches in Slack.

**Comment by hubertdeng123** [comment] 2023-02-25 01:20
This doesn't sound normal to me. The alerts should trigger instantly. If you test out the webhook via the slack integration page? Is that instant? I'd try and check your snuba/web logs to see if there's anything weird going on

**Comment by musabstellic** [comment] 2023-03-01 00:04
Based on my investigation, once an alert is triggered, it gets to Slack immediately. It's just that the alert isn't getting triggered.

Any idea what to look for within snuba/web?

**Comment by McFistyBuns** [comment] 2023-03-02 18:34
I believe I may be experiencing something similar.  Alert messages seem to be coming late for events that happened hours ago.  I'm not sure if it's relevant, but I think the snuba-post-processor offset may be off by one.  I noticed a pattern when sending test events from my web application and it seems that whenever an alert is triggered, the alert for the previous event gets sent out.  I started looking in kafka and noticed that the snuba-post-processor lag is always 1.
```
GROUP                TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
snuba-post-processor transactions    0          1               2               1               rdkafka-5917c983-9cfd-4a58-9981-9bd21324c0d2 /192.168.160.25 rdkafka
snuba-post-processor events          0          2               3               1               rdkafka-85dcb1e2-2b25-4511-aa21-9c0755bd197e /192.168.160.29 rdkafka```

This was after I went with the nuclear option in the kafka troubleshooting section.

**Comment by hubertdeng123** [comment] 2023-03-02 19:29
Thanks for the context. I've played around and am able to reproduce this, I think you're onto something @McFistyBuns I'm also noticing that on my end

**Comment by hubertdeng123** [comment] 2023-03-02 20:45
Would any of you be able to chime in to what kind of alert was created @McFistyBuns @musabstellic? To give some context, we handle two types of alerts. Issue alerts that get fired by the post process and snuba subscription alerts that uses the differences in timestamps of messages on the topic. It'd be helpful to know which umbrella your alerts are falling under.

**Comment by McFistyBuns** [comment] 2023-03-02 20:54
I'm not sure I know, to be honest.  I believe it's an issue alert.  I took the default alert that gets set up when you create a project and removed both the when and if triggers so that it would send an alert via email whenever an event came in.  Is that helpful?

**Comment by musabstellic** [comment] 2023-03-02 23:20
I am using the event alert with some filters around the event's tags. Does that help? I'm not sure what Snuba subscription alerts are.

**Comment by musabstellic** [comment] 2023-03-19 00:32
Thanks! Two follow-ups:

1. Is there an ETA on a possible fix?
2. Are there any guidelines around how to downgrade?

**Comment by hubertdeng123** [comment] 2023-03-20 17:56
So far, no promises on the ETA on a possible fix. For the guidelines for how to downgrade, you should be safe to just directly perform a downgrade since there is no hard stop between these two versions.
```
git checkout 22.12.0
./install.sh
```

**Comment by musabstellic** [comment] 2023-03-21 01:07
Sounds good, thanks @hubertdeng123!

**Comment by Physikbuddha** [comment] 2023-03-23 10:40
Wanted to test downgrading to 22.12.0, but I can't because of this issue: https://github.com/getsentry/sentry/issues/43678

I guess this wasn't fixed back in 22.12.0 already.
Should I just wait for an update then?

**Comment by hubertdeng123** [comment] 2023-04-14 20:48
Yeah :/, unfortunately I'm not sure when the team will get to this since it's on snuba's backlog.

**Comment by simPod** [comment] 2023-05-10 09:18
@hubertdeng123 is there a way to track the progress on this issue? I just noticed php sdk v3.18 is not compatible with 22.10 that we're stuck on. So this kinda starts to affect a larger scope of things.

**Comment by maylow** [comment] 2023-06-05 12:07
@hubertdeng123 do you have any update? Is there a way to track the progress on this issue?

**Comment by hubertdeng123** [comment] 2023-06-06 16:55
No updates right now. The best I can do is to ping the team involved to see if there's any progress on this

**Comment by hubertdeng123** [comment] 2023-06-07 16:32
I tested the snuba image associated with the commit in https://github.com/getsentry/snuba/pull/4297. This should resolve the issue for you all

**Comment by hubertdeng123** [comment] 2023-06-07 19:49
Going to go ahead and close this since the fix is in

**Closed by hubertdeng123** 2023-06-07 19:49 UTC
Labels: Type: Support Request, Status: Backlog
