### ISSUE TITLE
Bad Gateway Error

### ISSUE THREAD

**Issue by kokel** [getsentry/self-hosted#2256] opened 2023-07-07 09:07 UTC
### Self-Hosted Version

23.6.1

### CPU Architecture

x86_64

### Docker Version

24.0.2

### Docker Compose Version

2.18.1

### Steps to Reproduce

1. Go on Issues
2. open an issue with attachments
3. Select "All Events"

### Expected Result

Show all Events

### Actual Result

- not loading
- Browser Console show Bad Gateway  Errors:
`11:00:25.317 Uncaught (in promise) BadGatewayError: GET /api/0/issues/{issueId}/attachments/ 502
    n requestError.tsx:44
    error api.tsx:594
    wrapCallback api.tsx:292
    handleRequestError api.tsx:339
    c api.tsx:410
    request api.tsx:551
    request api.tsx:461
    requestPromise api.tsx:583
    requestPromise api.tsx:582
    h eventsTable.tsx:412
    children eventsTable.tsx:472
    render genericDiscoverQuery.tsx:299
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    h genericDiscoverQuery.tsx:268
    componentDidMount genericDiscoverQuery.tsx:168
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 2
Caused by: Error: API Request Error
    requestPromise api.tsx:580
    h eventsTable.tsx:412
    children eventsTable.tsx:472
    render genericDiscoverQuery.tsx:299
    Ja React
2 requestError.tsx:44:4
`
`11:00:25.464 Uncaught (in promise) BadGatewayError: GET /api/0/issues/{issueId}/attachments/ 502
    n requestError.tsx:44
    error api.tsx:594
    wrapCallback api.tsx:292
    handleRequestError api.tsx:339
    c api.tsx:410
    request api.tsx:551
    request api.tsx:461
    requestPromise api.tsx:583
    requestPromise api.tsx:582
    h eventsTable.tsx:412
    children eventsTable.tsx:472
    render genericDiscoverQuery.tsx:299
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    d use-sync-external-store-shim.production.min.js:10
    node_modules vendors-node_modules_echarts-for-react_lib_core_js-node_modules_echarts_core_js-node_modules_-8f444b.2ad44862f54057d91e3a.js:2
    n notifyManager.mjs:8
    node_modules vendors-node_modules_echarts-for-react_lib_core_js-node_modules_echarts_core_js-node_modules_-8f444b.2ad44862f54057d91e3a.js:2
    node_modules vendors-node_modules_echarts-for-react_lib_core_js-node_modules_echarts_core_js-node_modules_-8f444b.2ad44862f54057d91e3a.js:2
    i notifyManager.mjs:12
    node_modules vendors-node_modules_echarts-for-react_lib_core_js-node_modules_echarts_core_js-node_modules_-8f444b.2ad44862f54057d91e3a.js:2
    promise callback*k utils.mjs:296
    node_modules vendors-node_modules_echarts-for-react_lib_core_js-node_modules_echarts_core_js-node_modules_-8f444b.2ad44862f54057d91e3a.js:2
Caused by: Error: API Request Error
    requestPromise api.tsx:580
    h eventsTable.tsx:412
    children eventsTable.tsx:472
    render genericDiscoverQuery.tsx:299
    Ja React
2 requestError.tsx:44:4
`

Web Container Logs shows:
`NoneType: None
09:03:00 [WARNING] sentry.services.hybrid_cloud: Pydantic type validation error
NoneType: None
09:03:00 [WARNING] sentry.services.hybrid_cloud: Pydantic type validation error`

### Event ID

c79636f1-fbe6-4868-9ea1-22eed94324d0

**Comment by hubertdeng123** [comment] 2023-07-10 23:30
Is there any more information you can give here? When did this error start occurring? After you upgraded to 23.6.1?

**Comment by hubertdeng123** [comment] 2023-07-10 23:31
I believe `sentry.services.hybrid_cloud: Pydantic type validation error NoneType: None ` is just a warning and not harmful

**Comment by kokel** [comment] 2023-07-11 08:45
> Is there any more information you can give here? When did this error start occurring? After you upgraded to 23.6.1?

Yes, it first occurs after upgrading from 21.8.0 to 23.6.1.

> I believe `sentry.services.hybrid_cloud: Pydantic type validation error NoneType: None ` is just a warning and not harmful. It also seems like the timestamp of the web logs and browser console are mismatched?

I just don't gathered the logs at the same time. But it seems that the error only occurs on issues with attachments.

**Comment by sashamorozov** [comment] 2023-07-12 14:04
Hi, we get the same error, updating to 23.6.2 did not solve the problem, it was also on 23.6.1 and possibly earlier.

Attachments are not used

It seems that there is a problem with pagination, if there are 10-20 events, then everything works, if 100+ then 502 error

**Comment by hubertdeng123** [comment] 2023-07-12 21:07
Ah this actually does sound familiar to me. We experienced this too and bypassed this by changing our nginx config to use proxy buffering. Is this enabled in your config?

**Comment by hubertdeng123** [comment] 2023-07-12 21:08
Something like this
```
proxy_buffering off;
proxy_buffer_size          128k;
proxy_buffers              4 256k;
```

**Comment by xSwaight** [comment] 2023-07-13 14:09
I have exactly the same problem. Proxy buffering was not active, I enabled it for testing. Unfortunately, the problem persists.

**Comment by hubertdeng123** [comment] 2023-07-13 21:20
> I have exactly the same problem. Proxy buffering was not active, I enabled it for testing. Unfortunately, the problem persists.

Was this in your self-hosted nginx config? Is there by chance another nginx config for the machine? What we did was enable proxy buffering there as well to get the error to disappear.

**Comment by kokel** [comment] 2023-07-14 05:54
Thanks, with proxy buffering enabled on the nginx reverse proxy in front of sentry docker it seems to work again. I will observe it a bit longer.

**Comment by xSwaight** [comment] 2023-07-14 06:37
> Was this in your self-hosted nginx config? Is there by chance another nginx config for the machine? What we did was enable proxy buffering there as well to get the error to disappear.

Thanks for pointing that out, there was actually another nginx config active on the machine. I have now made the changes there and the problem is solved. Thanks a lot!

**Comment by sashamorozov** [comment] 2023-07-14 08:51
yes, changing the config helped, thanks!

**Comment by hubertdeng123** [comment] 2023-07-14 19:42
awesome! going to close this as resolved then

**Closed by hubertdeng123** 2023-07-14 19:42 UTC
Labels: Type: Support Request, Waiting for: Product Owner
