### ISSUE TITLE
Snuba crashing with KeyError: 'query' after upgrade

### ISSUE THREAD

**Issue by knaperek** [getsentry/self-hosted#2213] opened 2023-06-19 17:04 UTC
### Self-Hosted Version

23.5.0

### CPU Architecture

x86_64

### Docker Version

20.10.5

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. Upgraded from 21.4.1 -> 21.6.3 -> 23.5.0 (respecting the [hard stops](https://develop.sentry.dev/self-hosted/releases/#hard-stops)
2. Upgrades seem to have gone fine without problems, the last one just hanged at the very end (after saying it was successful) so I terminated it with Ctrl+C after a while

### Expected Result

All containers running without crashes.

### Actual Result

`se_snuba-subscription-consumer-transactions_1` and `se_snuba-subscription-consumer-events_1` have been constantly crashing ever since the upgrade, with `KeyError: 'query'`:
Full log (from `docker logs se_snuba-subscription-consumer-transactions_1`):
```
2023-06-19 16:48:56,870 Initializing Snuba...
2023-06-19 16:48:59,614 Snuba initialization took 2.745160829043016s
2023-06-19 16:48:59,941 Initializing Snuba...
2023-06-19 16:49:02,709 Snuba initialization took 2.768232448026538s
2023-06-19 16:49:05,722 New partitions assigned: {Partition(topic=Topic(name='snuba-transactions-commit-log'), index=0): 576}
2023-06-19 16:49:14,385 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 282, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 376, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 240, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 246, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 246, in <listcomp>
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
  File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 402, in find
    subscriptions = self.__get_subscriptions()
  File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 375, in __get_subscriptions
    for uuid, data in self.__store.all()
  File "/usr/src/snuba/snuba/subscriptions/store.py", line 68, in all
    return [
  File "/usr/src/snuba/snuba/subscriptions/store.py", line 69, in <listcomp>
    (UUID(key.decode("utf-8")), self.codec.decode(val))
  File "/usr/src/snuba/snuba/subscriptions/codecs.py", line 35, in decode
    return SubscriptionData.from_dict(data, self.entity_key)
  File "/usr/src/snuba/snuba/subscriptions/data.py", line 200, in from_dict
    query=data["query"],
KeyError: 'query'
2023-06-19 16:49:14,388 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f5ce4ca4910>...
2023-06-19 16:49:14,388 Partitions to revoke: [Partition(topic=Topic(name='snuba-transactions-commit-log'), index=0)]
2023-06-19 16:49:14,388 on_partitions_revoked crashed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 282, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 376, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 240, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 246, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 246, in <listcomp>
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
  File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 402, in find
    subscriptions = self.__get_subscriptions()
  File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 375, in __get_subscriptions
    for uuid, data in self.__store.all()
  File "/usr/src/snuba/snuba/subscriptions/store.py", line 68, in all
    return [
  File "/usr/src/snuba/snuba/subscriptions/store.py", line 69, in <listcomp>
    (UUID(key.decode("utf-8")), self.codec.decode(val))
  File "/usr/src/snuba/snuba/subscriptions/codecs.py", line 35, in decode
    return SubscriptionData.from_dict(data, self.entity_key)
  File "/usr/src/snuba/snuba/subscriptions/data.py", line 200, in from_dict
    query=data["query"],
KeyError: 'query'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 46, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 223, in on_partitions_revoked
    _close_strategy()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 161, in _close_strategy
    raise InvalidStateError(
arroyo.processing.processor.InvalidStateError: received unexpected revocation without active processing strategy
2023-06-19 16:49:14,391 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 141, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 282, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 376, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 240, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 246, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 246, in <listcomp>
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
  File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 402, in find
    subscriptions = self.__get_subscriptions()
  File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 375, in __get_subscriptions
    for uuid, data in self.__store.all()
  File "/usr/src/snuba/snuba/subscriptions/store.py", line 68, in all
    return [
  File "/usr/src/snuba/snuba/subscriptions/store.py", line 69, in <listcomp>
    (UUID(key.decode("utf-8")), self.codec.decode(val))
  File "/usr/src/snuba/snuba/subscriptions/codecs.py", line 35, in decode
    return SubscriptionData.from_dict(data, self.entity_key)
  File "/usr/src/snuba/snuba/subscriptions/data.py", line 200, in from_dict
    query=data["query"],
KeyError: 'query'
```
I assume this error may be related to https://github.com/getsentry/self-hosted/issues/1602

I've tried [nuking](https://develop.sentry.dev/self-hosted/troubleshooting/#nuclear-option) kafka already, didn't help at all.

Also tried debugging the running code, found this to be the content of the `data` dictionary in the crashing line (`query=data["query"]`):
```
{'project_id': 2, 'conditions': [['type', '=', 'error'], ['environment', '=', 'production']], 'aggregations': [['count', None, 'count']], 'time_window': 600, 'resolution': 60}
```
So apparently it is missing the `query` key. Not sure where it should come from or how to fix it though. Thanks for any hints.

**Comment by hubertdeng123** [comment] 2023-06-21 23:24
I believe this is a duplicate of this issue here, could you follow up in that issue?
https://github.com/getsentry/self-hosted/issues/2067

**Closed by hubertdeng123** 2023-06-21 23:24 UTC
