### ISSUE TITLE
Feature doesn't work projects:discard-groups

### ISSUE THREAD

**Issue by zKoz210** [getsentry/self-hosted#2619] opened 2023-12-04 09:09 UTC
### Self-Hosted Version

23.11.2

### CPU Architecture

x86_64

### Docker Version

Docker version 24.0.5, build ced0996

### Docker Compose Version

Docker Compose version v2.20.2

### Steps to Reproduce

1. I want to delete all events and not save them anymore

![image](https://github.com/getsentry/self-hosted/assets/28255085/7922bdbc-71c1-4332-958c-c0fc205fa29c)

2. It tells me that the feature is not enabled
![image](https://github.com/getsentry/self-hosted/assets/28255085/2adea973-a606-46dc-a9b2-9c6197362f2b)

3. But it has been enabled since the installation of Sentry, I also prescribed additionally to make sure that it does not work

![image](https://github.com/getsentry/self-hosted/assets/28255085/2b637e3b-19f2-4290-9633-89f2ebe07f82)

### Expected Result

You should be able to disable saving the current event view.

### Actual Result

Sentry says that the feature is disabled, although in fact the settings in the configuration are written correctly

**Comment by hubertdeng123** [comment] 2023-12-05 22:07
This is a duplicate of https://github.com/getsentry/sentry/issues/57162, so I am closing this

**Closed by hubertdeng123** 2023-12-05 22:07 UTC
Labels: Waiting for: Product Owner
