### ISSUE TITLE
JS error causing stuck on loading screen after login

### ISSUE THREAD

**Issue by prikeshsavla** [getsentry/self-hosted#2888] opened 2024-03-13 14:19 UTC
### Self-Hosted Version

24.2.0

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.21.0

### Steps to Reproduce

Clear cookies for Sentry application (To remove authentication)
Go to {{url}}/auth/login/{{organizaiton name}}
Login with Google
Enter 2FA number on Sentry
See loading screen for /organizations/cashee/projects/

I have a adblocker, but even in incognito without an adblocker this fails
Checked in both Chrome and Firefox

### Expected Result

Should have moved to the List of projects or issues

### Actual Result
<img width="699" alt="Screenshot 2024-03-13 at 7 52 50 PM" src="https://github.com/getsentry/self-hosted/assets/34878926/64ad5609-0baf-4a48-8996-47d8771153b0">

<img width="1122" alt="Screenshot 2024-03-13 at 7 44 10 PM" src="https://github.com/getsentry/self-hosted/assets/34878926/a4bd2d25-c3d2-4020-9f43-6788791ed2e4">

Stuck on a loading screen

**Comment by aldy505** [comment] 2024-03-14 01:44
Usually the problem is caused by your reverse proxy/load balancer in front of the nginx container (that forwards the port 9000). What are you using, and what's the configuration?

You might also want to try and disable that reverse proxy, and try to access Sentry directly. If the problem persist, then we can make sure that it's not caused by the reverse proxy.

**Comment by prikeshsavla** [comment] 2024-03-15 09:00
> Usually the problem is caused by your reverse proxy/load balancer in front of the nginx container (that forwards the port 9000). What are you using, and what's the configuration?
> 
> You might also want to try and disable that reverse proxy, and try to access Sentry directly. If the problem persist, then we can make sure that it's not caused by the reverse proxy.

I checked trying to access it locally it works. How do I find the difference that is causing this issue then. 
I can share the LB nginx conf if that helps


```
upstream sentry {
        server SERVER_IP:9000; # Redirect traffic to Sentry server
    }

server {
        modsecurity on;
        modsecurity_rules_file /etc/nginx/modsec/sentry.conf;
        root /var/www/html;
        server_name sentry.example.com;
        client_max_body_size 200M;
        location / {
                proxy_pass https://sentry; # Forward Traffic to upstream servers
                proxy_ssl_certificate /etc/nginx/certs/server.crt; # Location to specify crt file
                proxy_ssl_certificate_key /etc/nginx/certs/server.key; # Location to specify key file
                proxy_ssl_trusted_certificate /etc/nginx/certs/ca.crt; # Location of CA for authentication
                proxy_set_header Host $http_host; # Host header is not changed
                proxy_set_header Upgrade $http_upgrade; # Host header Upgrade
                proxy_set_header X-Forwarded-Proto https; # Request scheme HTTPS
                proxy_set_header X-Forwarded-Ssl on; # Request SSL
                proxy_buffering off; # Turn off Buffering
        }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/sentry.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/sentry.example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    access_log /var/log/nginx/sentry-access.log;
    error_log /var/log/nginx/sentry-error.log;
}



server {
    if ($host = sentry.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        server_name sentry.example.com ;

    listen 80;
    return 404; # managed by Certbot


}
```

**Comment by hubertdeng123** [comment] 2024-03-18 23:07
What does your network tab look like? Nothing is jumping out at me from the config you posted above

**Comment by prikeshsavla** [comment] 2024-03-19 02:04
Sadly I am not able to replicate the issue any more. From yesterday, it
started working for some of my colleagues, so I tried clearing cache and
now it works.

Clearing cache didn't work before, so either it was cached on CDN level or
something else causing this.

**Comment by aldy505** [comment] 2024-03-19 07:51
Since this is resolved on your end, I'll close this issue for now. Feel free to create new issue or add new comments if the problem continue.

**Closed by aldy505** 2024-03-19 07:51 UTC
Labels: Waiting for: Product Owner
