### ISSUE TITLE
Reduce container count in self-hosted

### ISSUE THREAD

**Issue by OldBucFan** [getsentry/self-hosted#2658] opened 2023-12-19 23:00 UTC
### Problem Statement

Our upgrade from 22.8.0 to 23.11.1 effectively doubled the number of containers running, requiring an increased memory allocation and thus higher cost of ownership.

### Solution Brainstorm

Could Snuba and Sentry jobs be consolidated to run on a few containers vs. dedicated per job.

**Comment by rhuddleston** [comment] 2023-12-19 23:02
Possibly an option so the snuba consumer or sentry consumer jobs can be optionally combined and consume multiple events in a single container?

**Comment by azaslavsky** [comment] 2023-12-20 00:55
We have some long term plans to do this, but it's not on the docket until at least February of next year. I'll keep this issue open for now.

**Comment by aldy505** [comment] 2023-12-20 01:33
This is a duplicate of https://github.com/getsentry/self-hosted/issues/2539 and https://github.com/getsentry/self-hosted/issues/1763

**Comment by azaslavsky** [comment] 2023-12-20 17:48
Good point - will roll this issue into those and mark as a dupe.

**Closed by azaslavsky** 2023-12-20 17:48 UTC
Labels: Waiting for: Product Owner

**Comment by rhuddleston** [comment] 2023-12-20 22:25
snuba issue: https://github.com/getsentry/snuba/issues/1670
