### ISSUE TITLE
Self-Hosted Workers documentation incorrect

### ISSUE THREAD

**Issue by LorenDorez** [getsentry/self-hosted#2089] opened 2023-04-07 18:58 UTC
### Environment

Self-Hosted

### Steps to Reproduce

The documentation located [here](https://develop.sentry.dev/self-hosted/troubleshooting/#workers) tell you to add the workers to the docker-compose.override.yml file and provides an example. However, when you do this you will get an error. 

What is the best way to add additional workers?

### Expected Result
It to work lol!

### Actual Result
`[yaml](yaml: unknown anchor 'sentry_defaults' referenced)`

**Comment by hubertdeng123** [comment] 2023-04-17 11:48
closed as duplicate of https://github.com/getsentry/self-hosted/issues/2072

**Closed by hubertdeng123** 2023-04-17 11:48 UTC
Labels: Status: Untriaged
