### ISSUE TITLE
Install script container name already in use

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/self-hosted#1856] opened 2022-12-08 17:02 UTC
### Self-Hosted Version

22.11.0

### CPU Architecture

x86

### Docker Version

20.10.17

### Docker Compose Version

2.6.0

### Steps to Reproduce

run the `./install.sh` script

sometimes, it errors out

### Expected Result

no errors

### Actual Result

```
Turning things off...
...
Container sentry-self-hosted-subscription-consumer-events-1  Created
Container sentry-self-hosted-relay-1  Created
Container sentry-self-hosted-nginx-1  Creating
Container sentry-self-hosted-nginx-1  Created
Error response from daemon: Conflict. The container name "/sentry-self-hosted-worker-1" is already in use by container "4e77d0444cb53528395a603961f9ad1c810493dfc6b23deac7533dbbc1f20658". You have to remove (or rename) that container to be able to reuse that name.
```

**Comment by ethanhs** [comment] 2022-12-12 17:58
Dupe of https://github.com/getsentry/self-hosted/issues/1547

**Closed by ethanhs** 2022-12-12 17:58 UTC
