### ISSUE TITLE
Container Process-Forwarder-Errors constant restart

### ISSUE THREAD

**Issue by devag-al** [getsentry/self-hosted#2019] opened 2023-03-08 12:49 UTC
### Self-Hosted Version

23.2.0

### CPU Architecture

X86_64

### Docker Version

20.10.23

### Docker Compose Version

1.29.2

### Steps to Reproduce

Deleted all containers (`docker-compose down` + a stop/rm on all remaning containers).

Reran `./install.sh` and `docker-compose up -d`

Checking at `docker stats`, I see container `sentry-self-hosted_post-process-forwarder-errors_1` popping up and disappearing.  It takes a high amount of CPU on each try, which is every 2-3 seconds.

### Expected Result

Container `sentry-self-hosted_post-process-forwarder-errors_1` should run non-stop and not tax CPU.

### Actual Result

```bash
$ docker stats | grep errors
CONTAINER ID   NAME                                                            CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              0.00%     936KiB / 28.69GiB     0.00%     176B / 0B         0B / 0B           2
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              0.00%     936KiB / 28.69GiB     0.00%     176B / 0B         0B / 0B           2
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              91.98%    53.64MiB / 28.69GiB   0.18%     626B / 0B         0B / 0B           2
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              91.98%    53.64MiB / 28.69GiB   0.18%     626B / 0B         0B / 0B           2
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              94.10%    86.95MiB / 28.69GiB   0.30%     716B / 0B         0B / 0B           2
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              94.10%    86.95MiB / 28.69GiB   0.30%     716B / 0B         0B / 0B           2
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              89.32%    113.1MiB / 28.69GiB   0.38%     716B / 0B         0B / 0B           2
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              89.32%    113.1MiB / 28.69GiB   0.38%     716B / 0B         0B / 0B           2
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              89.32%    113.1MiB / 28.69GiB   0.38%     716B / 0B         0B / 0B           2
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              84.62%    126.4MiB / 28.69GiB   0.43%     716B / 0B         0B / 0B           2
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              84.62%    126.4MiB / 28.69GiB   0.43%     716B / 0B         0B / 0B           2
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              33.20%    136MiB / 28.69GiB     0.46%     12.9kB / 8.3kB    0B / 0B           11
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              33.20%    136MiB / 28.69GiB     0.46%     12.9kB / 8.3kB    0B / 0B           11
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              0.18%     136MiB / 28.69GiB     0.46%     12.9kB / 8.3kB    0B / 0B           11
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              0.18%     136MiB / 28.69GiB     0.46%     12.9kB / 8.3kB    0B / 0B           11
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              0.20%     136MiB / 28.69GiB     0.46%     12.9kB / 8.3kB    0B / 0B           11
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              0.20%     136MiB / 28.69GiB     0.46%     12.9kB / 8.3kB    0B / 0B           11
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              0.20%     136MiB / 28.69GiB     0.46%     12.9kB / 8.3kB    0B / 0B           11
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              2.73%     136.2MiB / 28.69GiB   0.46%     112kB / 11.1kB    0B / 0B           11
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              2.73%     136.2MiB / 28.69GiB   0.46%     112kB / 11.1kB    0B / 0B           11
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              0.34%     136.2MiB / 28.69GiB   0.46%     113kB / 11.8kB    0B / 0B           11
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              0.34%     136.2MiB / 28.69GiB   0.46%     113kB / 11.8kB    0B / 0B           11
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              0.00%     764KiB / 28.69GiB     0.00%     90B / 0B          0B / 0B           2
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              0.00%     764KiB / 28.69GiB     0.00%     90B / 0B          0B / 0B           2
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              77.64%    42.4MiB / 28.69GiB    0.14%     266B / 0B         0B / 0B           2
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              77.64%    42.4MiB / 28.69GiB    0.14%     266B / 0B         0B / 0B           2
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              88.96%    74.1MiB / 28.69GiB    0.25%     716B / 0B         0B / 0B           2
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              88.96%    74.1MiB / 28.69GiB    0.25%     716B / 0B         0B / 0B           2
2436debc02d2   sentry-self-hosted_post-process-forwarder-errors_1              88.96%    74.1MiB / 28.69GiB    0.25%     716B / 0B         0B / 0B           2
```

(added the header for clarity)

```bash
$ docker logs sentry-self-hosted_post-process-forwarder-errors_
# [...] Those lines repeats at each run
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 192, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/run.py", line 380, in post_process_forwarder
    eventstream.run_post_process_forwarder(
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/services.py", line 127, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 303, in run_post_process_forwarder
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 175, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 206, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/synchronized.py", line 248, in poll
    message = self.__consumer.poll(timeout)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 407, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}
sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image
/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py:243: DeprecationWarning: `structlog.threadlocal` is deprecated, please use `structlog.contextvars` instead.
  WrappedDictClass = structlog.threadlocal.wrap_dict(dict)
13:05:36 [INFO] sentry.plugins.github: apps-not-configured
```

**Comment by devag-al** [comment] 2023-03-08 13:10
By copying the container's logs here, the link shown in the log pop-out to me .... so this is a no issue, the steps to fix seems clear to me !

**Comment by devag-al** [comment] 2023-03-08 14:39
Turns out what was described at the link, even tho' I was indeed installing a plugin directly in the image instead of by this script, by changing that behavior, the issue still persists.

**Comment by hubertdeng123** [comment] 2023-03-10 14:05
this is a duplicate of https://github.com/getsentry/self-hosted/issues/1894

closing this in favor of that, people have found that deleting offsets may have resolved their issues

**Closed by hubertdeng123** 2023-03-10 14:05 UTC
Labels: Type: Support Request

**Comment by artful88533** [comment] 2023-03-13 08:23
@hubertdeng123 hi!
Could you explain which consumer group and topic `post-process-forwarder-errors` use? 

Thanks in advance!

**Comment by jtraulle** [comment] 2023-03-15 18:47
Like @artful88533 I would also be interested in what consumer group and topic `post-process-forwarder-errors` use as I experience the exact same issue and other linked issue does not explain that. Thanks @hubertdeng123 .

**Comment by jtraulle** [comment] 2023-03-15 19:05
Seems like deleting  `snuba-post-processor` consumer group did the trick.

```shell
sudo docker compose down && \ # We shutdown everything, but we only want to keep Kafka running
sudo docker compose up -d kafka && \ # Zookeeper will be run too
sleep 60s && \ # Make sure our Kafka is ready to handle commands
sudo docker compose run --rm kafka kafka-consumer-groups --bootstrap-server kafka:9092 --group snuba-post-processor --delete && \  # Delete the snuba-post-processor consumer group
sleep 60s && \ # Make sure everything is commited on Kafka's side
sudo docker compose up -d # To start everything again
```

**Comment by hubertdeng123** [comment] 2023-03-15 20:09
The `post-process-forwarder-errors` uses `snuba-consumer` group and it handles the `events` topic. Looks like the `snuba-post-processor` consumer group was left behind after upgrading? That was removed [here](https://github.com/getsentry/self-hosted/pull/1759)

Thanks @jtraulle for reporting back with what helped solve it for you

**Comment by artful88533** [comment] 2023-03-16 12:35
I've found that the consumer group in `post-process-forwarder` apps is `snuba-post-processor`
https://github.com/getsentry/sentry/blob/23.3.0/src/sentry/runner/commands/run.py#L324-L325

The reason for the error for me was the high load and short `retention.ms` on topic `events`.
I've increased `--commit-batch-size 1000` and added additional partitions on the topic.
Now it works without errors)

Thank you!

**Comment by hubertdeng123** [comment] 2023-03-16 17:04
Oh darn, guess I was wrong. Didn't see that and thought it would default to `snuba-consumers` [here](https://github.com/getsentry/snuba/blob/master/snuba/cli/consumer.py#L44). Thanks for reporting back

**Comment by artful88533** [comment] 2023-03-30 11:18
@LorenDorez later I noticed that additional partitions on the topic `events` broke one of the snuba processes. 
Try to increase  `--commit-batch-size 1000` [here](https://github.com/getsentry/self-hosted/blob/23.2.0/docker-compose.yml#L328)
p.s. My version 23.2.0

**Comment by LorenDorez** [comment] 2023-03-30 13:50
@artful88533 thanks ill give that a try. We keep having this #1894 and for me its even happening on a new box thats not even being used yet so its not a load/usage issue. Going to try the commit-batch-size still but seeing as nothing is using it i dont think its going to work
