### ISSUE TITLE
Replays not found  error 

### ISSUE THREAD

**Issue by Chethanibms** [getsentry/self-hosted#3017] opened 2024-05-03 12:47 UTC
### Self-Hosted Version

getsentry/sentry:24.2.0

### CPU Architecture

x86_64

### Docker Version

latest

### Docker Compose Version

latest

### Steps to Reproduce

1. create a new self hosted instance with version 24.2.0
2. Create a react js project  and push the sentry data to self hosted instance 
3. Libraray : sentry/react": "^7.110.1 

### Expected Result

1. Replays are working fine in Sentry.io platform, once we move from sentry cloud to self hosted things started failing 

### Actual Result

![image](https://github.com/getsentry/self-hosted/assets/54358087/bd49d636-7311-4313-a0ee-7715f3956409)

**Comment by azaslavsky** [comment] 2024-05-06 22:16
Do you see any errors in your server logs (`sentry-web`) when hitting this endpoint? Does the rest of the event data show up fine?

**Comment by michellewzhang** [comment] 2024-12-10 21:49
hi @Chethanibms, is this issue still occurring for you?

**Comment by michellewzhang** [comment] 2024-12-11 22:53
closing for now; feel free to re-open if the issue is still occurring for you.

**Closed by michellewzhang** 2024-12-11 22:53 UTC
