### ISSUE TITLE
not working snuba 23.2.0 migration on clickhouse cluster version 20.3.9.70

### ISSUE THREAD

**Issue by shcherbak** [getsentry/self-hosted#2147] opened 2023-05-16 07:41 UTC
### Self-Hosted Version

23.1.0

### CPU Architecture

x86_64

### Docker Version

20.10.16

### Docker Compose Version

2.6.0

### Steps to Reproduce

install snuba 23.1.0, upgrade to 23.2.0
run snuba migrations migrate

(it is ok when using single clickhouse db)

### Expected Result

migrations applied

### Actual Result

```
runner.run_all(force=force, group=migration_group)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 179, in run_all
    self._run_migration_impl(migration_key, force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 234, in _run_migration_impl
    migration = get_group_loader(migration_key.group).load_migration(migration_id)
  File "/usr/src/snuba/snuba/migrations/groups.py", line 75, in load_migration
    module = import_module(f"{self.__module}.{migration_id}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/snuba/snuba/snuba_migrations/generic_metrics/0010_counters_aggregate_table.py", line 23, in <module>
    class Migration(migration.ClickhouseNodeMigration):
  File "/usr/src/snuba/snuba/snuba_migrations/generic_metrics/0010_counters_aggregate_table.py", line 28, in Migration
    storage_set_key = StorageSetKey.GENERIC_METRICS_COUNTERS
  File "/usr/src/snuba/snuba/clusters/storage_sets.py", line 31, in __getattr__
    raise AttributeError(attr)
AttributeError: GENERIC_METRICS_COUNTERS
```

**Comment by hubertdeng123** [comment] 2023-05-16 17:20
Seems to be a duplicate of this issue:
https://github.com/getsentry/sentry/issues/47971

Given that this isn't officially supported by us, I'm going to close this

**Closed by hubertdeng123** 2023-05-16 17:20 UTC
Labels: Type: Support Request
