### ISSUE TITLE
Clickhouse Error: Socket is not connected 

### ISSUE THREAD

**Issue by AbelHristodor** [getsentry/self-hosted#2978] opened 2024-04-19 15:39 UTC
### Self-Hosted Version

24.4.1

### CPU Architecture

x86_64

### Docker Version

26.0.1

### Docker Compose Version

2.26.1

### Steps to Reproduce

I did the following:
- `git clone <repo> && git checkout 24.4.1`
- `sudo ./install`
- `docker compose up -d`

on a fresh GCE VM with Debian 11. 4 vCPU 16GB RAM.

All other containers seems to work, but clickhouse refuses to start saying `Socket not connected`. Events are not getting received by sentry.

### Expected Result

All containers should start correctly.

### Actual Result

Clickhouse error:
```txt
2024.04.19 13:39:18.354241 [ 43 ] {} <Warning> Application: Listen [0.0.0.0]:8123 failed: Poco::Exception. Code: 1000, e.code() = 98, e.displayText() = Net Exception: Address already in use: 0.0.0.0:8123 (version 21.8.13.1.altinitystable (altinity build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
```
This error also appears for ports 9000, 9009, 9004, 9005.

and also `Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected`

Install log:
[install.log](https://github.com/getsentry/self-hosted/files/15042580/install.log)

**Comment by aldy505** [comment] 2024-04-22 01:00
The error is not really an error. Most likely it's caused by `rust-consumer` on snuba. If you want to make those disappear, you could replace every occurrence of `rust-consumer` to `consumer` on your `docker-compose.yml` file.

But, I'm going to close this as this is a duplicate of https://github.com/getsentry/snuba/issues/5707

**Closed by aldy505** 2024-04-22 01:00 UTC
Labels: Waiting for: Product Owner

**Comment by bmday** [comment] 2024-04-24 08:43
We have the same behavior. Today we updated from version 23.7.1 to 24.4.1 and received the same messages. It seems that changing rust-consumer to consumer helped us.

**Comment by AbelHristodor** [comment] 2024-04-24 08:45
I can confirm changing `rust-consumer` to `consumer` fixes the issue.

**Comment by yakky** [comment] 2024-05-09 00:22
Same here with both 24.4.0 and nightly
