### ISSUE TITLE
Cannot finish "Setup Sentry" when `mail.use-ssl` was set in the config

### ISSUE THREAD

**Issue by schettn** [getsentry/self-hosted#3186] opened 2024-07-08 05:41 UTC
### Self-Hosted Version

24.6.0

### CPU Architecture

x86_64

### Docker Version

25.0.0

### Docker Compose Version

2.25.0

### Steps to Reproduce

1. Setup a fresh sentry
2. Configure `mail` inside `sentry/config.yml` (especially `mail.use-ssl`):
3. Visit "Welcome to Sentry"
![image](https://github.com/getsentry/self-hosted/assets/52858351/17fa6d36-3a36-4a66-9ddf-f6ca0c0479b1)
4. Click `Continue`
5. See that nothing happens and look at the error 

### Expected Result

The `Continue` button should work.

### Actual Result

URL: https://sentry.cronit.io/api/0/internal/options/?query=is:required
Status: 400 Bad Request
Source: Network
Initiator: 
fetch.js:54

```json
{
    "error": "immutable_option",
    "errorDetail": {
        "option": "mail.use-ssl",
        "message": "'mail.use-ssl' cannot be changed at runtime because it is configured on disk"
    }
}
```

**Comment by hubertdeng123** [comment] 2024-07-09 23:20
Looks like a duplicate of https://github.com/getsentry/self-hosted/issues/3139. I'm going to backlog this for now until we have a chance to investigate

**Comment by schettn** [comment] 2024-07-10 06:25
The workaround is to comment out `mail.use-ssl` in `sentry/config.yml`.

**Comment by zentavr** [comment] 2024-07-18 03:40
@schettn Removed that `mail.use-ssl` from `/etc/sentry/config.yml`, restarted the pod and the issue is still there :(

**Comment by schettn** [comment] 2024-07-22 06:34
> mail.use-ssl' cannot be changed at runtime because it is configured on disk

Do you have the same error after removing it?

Maybe you have to reinstall

**Comment by schettn** [comment] 2024-07-22 13:07
I am not familiar to your setup but is `/etc/sentry/config.yml` correct?

When `/etc/sentry` is the cloned `https://github.com/getsentry/self-hosted`.. shouldn't the config path be `/etc/sentry/sentry/config.yml`?

**Comment by vanya2143** [comment] 2024-07-26 14:46
I solved this problem by using a curl request with the use-ssl parameter removed  :D 
You can simply copy the request from your browser..
Not a very good solution, but a quick one.

```curl 'http://mysuperhost.com/api/0/internal/options/?query=is:required' \
  -X 'PUT' \
  -H 'Accept-Language: en-US,en;q=0.9,uk;q=0.6' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: ....' \
  -H 'Origin: http://mysuperhost.com' \
  -H 'Referer: http://mysuperhost.com/organizations/new/' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36' \
  -H 'accept: application/json; charset=utf-8' \
  -H 'baggage: ....' \
  -H 'content-type: application/json' \
  -H 'sentry-trace: ....' \
  -H 'x-csrftoken: .....' \
  --data-raw '{"system.admin-email":"youremail","mail.username":"","mail.password":"","auth.allow-registration":false,"beacon.record_cpu_ram_usage":"false","beacon.anonymous":"true"}' \
  --insecure

```

**Comment by IanWoodard** [comment] 2024-07-29 22:00
Thanks @vanya2143, going to backlog this again, but feel free to use this as a short-term solution!

**Comment by tiwj** [comment] 2024-09-09 09:58
Can confirm your solution @vanya2143 . Simply did it directly from the browser (Edge).

1. Open Developer Console F12
2. Open Network tab
3. Repeat failing request
4. Select request from the list
5. Right Click "Edit and send..."
6. Remove "mail.use-ssl":false from body
7. Resend > 200
8. Reload page

**Comment by cconrad** [comment] 2024-10-31 15:39
I can confirm that this still exists in 24.10.0.

**Comment by aldy505** [comment] 2024-11-12 06:26
Documented this here: https://github.com/getsentry/self-hosted/pull/3368

Going to close this issue.

**Closed by aldy505** 2024-11-12 06:26 UTC
Labels: Type: Bug, Waiting for: Product Owner
