### ISSUE TITLE
 Commit hash is not displayed, always unknown

### ISSUE THREAD

**Issue by zKoz210** [getsentry/self-hosted#2925] opened 2024-03-29 08:19 UTC
### Self-Hosted Version

24.3.0

### CPU Architecture

x86_64

### Docker Version

Docker version 24.0.5, build ced0996

### Docker Compose Version

Docker Compose version v2.20.2

### Steps to Reproduce

Upgrade Sentry 23.12.1 to 24.3.0

### Expected Result

Git Hash Commit 

### Actual Result

<img width="289" alt="image" src="https://github.com/getsentry/self-hosted/assets/28255085/4008eb70-da77-466f-9fa0-6657be71d7cb">

**Comment by azaslavsky** [comment] 2024-04-01 20:30
This is occurring on our dogfood instance as well. I'll look around internally for what could be causing it, perhaps we change how our python wheels are published.

**Comment by joshuarli** [comment] 2024-08-13 22:56
dupe of https://github.com/getsentry/self-hosted/issues/3165

**Closed by joshuarli** 2024-08-13 22:56 UTC
