### ISSUE TITLE
Error in install/ensure-relay-credentials.sh

### ISSUE THREAD

**Issue by ltzmax** [getsentry/self-hosted#2241] opened 2023-06-27 16:32 UTC
### Self-Hosted Version

23.6.1

### CPU Architecture

aarch64

### Docker Version

24.0.2, build cb74dfc

### Docker Compose Version

2.18.1

### Steps to Reproduce

1. cd into selfhosted folder after downloading.
2. ./install.sh
3. wait.

### Expected Result

installing.

### Actual Result

It stops here and i have no idea why. its first time installing!
```py
▶ Ensuring Relay credentials ...
relay/config.yml already exists, skipped creation.
 relay Pulling
 relay Pulled
 Network sentry-self-hosted_default  Creating
 Network sentry-self-hosted_default  Created
exec /bin/bash: exec format error
Error in install/ensure-relay-credentials.sh:29.
'$creds generate --stdout > "$RELAY_CREDENTIALS_JSON".tmp' exited with status 1
-> ./install.sh:main:26
--> install/ensure-relay-credentials.sh:source:29

Cleaning up...
```

**Comment by hubertdeng123** [comment] 2023-06-28 17:19
Hey there, thanks for writing in! This is likely due to the lack of support for arm64 in self-hosted Sentry. The issue is a duplicate of 
https://github.com/getsentry/self-hosted/issues/1585 so I will go ahead and close this.

**Closed by hubertdeng123** 2023-06-28 17:19 UTC
Labels: Status: Untriaged, Waiting for: Product Owner
