### ISSUE TITLE
Setting up notifications in Sentry on-premise for MS teams

### ISSUE THREAD

**Issue by Evgeniy-Izotov** [getsentry/self-hosted#2794] opened 2024-02-15 09:43 UTC
### Self-Hosted Version

23.2.0

### CPU Architecture

x86_64

### Docker Version

23.0.1

### Docker Compose Version

2.16.0

### Steps to Reproduce

Is it possible to set up notifications in Sentry on-premis for MS Teams and what is the best way to do this? Is integration like Sentry Saas possible?
Thank you!

### Expected Result

Notifications in MS Teams from Sentry (on-premis)

### Actual Result

-

**Comment by hubertdeng123** [comment] 2024-02-16 20:19
Closing this as a duplicate of https://github.com/getsentry/self-hosted/issues/2488. We haven't been able to get to this yet!

**Closed by hubertdeng123** 2024-02-16 20:19 UTC
