### ISSUE TITLE
Slack notification delay after new issue arrived to sentry

### ISSUE THREAD

**Issue by maylow** [getsentry/self-hosted#2034] opened 2023-03-17 07:42 UTC
### Self-Hosted Version

23.3.0

### CPU Architecture

x86_64

### Docker Version

20.10.5

### Docker Compose Version

2.16.0

### Steps to Reproduce

1. Upgrade Sentry to 23.3.0
2. Create alert to send slack notification when new issue is created.
3. Send issue via sentry-cli.
4. Sentry gets an issue but not mark it as new issue for 5 minutes.
![sentry_issue](https://user-images.githubusercontent.com/11584131/225840453-d597d7b1-3253-4f81-9476-8feb4b812b98.png)

5. After 5 minutes, it gets mark new issue and send issue to slack.
<img width="502" alt="slack_info" src="https://user-images.githubusercontent.com/11584131/225840488-fee01aa8-ac7a-423c-8de0-2537c6f86ebb.png">

### Expected Result

1. Create alert to send slack notification when new issue is created.
2. Send issue via sentry-cli.
3. Sentry gets an issue, mark it as new issue and send it to slack.

### Actual Result

We have 2 versions of sentry:
1) 22.10.0 - It is working as expected. New issue send notification to slack immediately.
2) 23.3.0 - It stop working after upgrade. Issue gets mark new issue after 5 minutes.
![sentry_issue](https://user-images.githubusercontent.com/11584131/225840453-d597d7b1-3253-4f81-9476-8feb4b812b98.png)
<img width="502" alt="slack_info" src="https://user-images.githubusercontent.com/11584131/225840488-fee01aa8-ac7a-423c-8de0-2537c6f86ebb.png">

I didn't find anything wrong in logs.
Also, this sentry doesn't have real traffic since this is just testing dev sentry. We are sending there a few issues per hour.
Any help would be appreciated.

**Comment by hubertdeng123** [comment] 2023-03-17 23:08
I believe this is a duplicate of https://github.com/getsentry/self-hosted/issues/1982

The alert won't trigger immediately and the offset is lagging by 1. Can you confirm this is the case?

**Comment by hubertdeng123** [comment] 2023-03-27 15:55
thanks, closing this then since our team is aware of this and investigating

**Closed by hubertdeng123** 2023-03-27 15:55 UTC
Labels: Type: Support Request
