### ISSUE TITLE
ModuleNotFoundError: No module named 'more_itertools'

### ISSUE THREAD

**Issue by berry2012** [getsentry/self-hosted#1900] opened 2023-01-08 20:06 UTC
### Self-Hosted Version

22.12.0 Latest

### CPU Architecture

x86_64

### Docker Version

20.10.17

### Docker Compose Version

2.14.2

### Steps to Reproduce

**OS details**
```
cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Steps to reproduce**
1. Clone the repo `git clone https://github.com/getsentry/self-hosted.git`
2. Ran `./install.sh`

```
Running hooks in /etc/ca-certificates/update.d...
done.
19:57:24 [WARNING] sentry.utils.geo: Error opening GeoIP database: /geoip/GeoLite2-City.mmdb
19:57:24 [WARNING] sentry.utils.geo: Error opening GeoIP database in Rust: /geoip/GeoLite2-City.mmdb
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 192, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 28, in inner
    configure()
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 128, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/settings.py", line 153, in configure
    initialize_app(
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py", line 373, in initialize_app
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/sentry_interface_types/models.py", line 2, in <module>
    from sentry.plugins.bases.tag import TagPlugin
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/bases/__init__.py", line 1, in <module>
    from .issue import IssueTrackingPlugin  # NOQA
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/bases/issue.py", line 7, in <module>
    from sentry.plugins.base.v1 import Plugin
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/base/__init__.py", line 1, in <module>
    from .bindings import BindingManager
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/base/bindings.py", line 1, in <module>
    from sentry.plugins.providers import IntegrationRepositoryProvider, RepositoryProvider
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/providers/__init__.py", line 8, in <module>
    from .integration_repository import IntegrationRepositoryProvider
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/providers/integration_repository.py", line 12, in <module>
    from sentry.api.serializers import serialize
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/__init__.py", line 2, in <module>
    from .models import *  # NOQA
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/models/__init__.py", line 29, in <module>
    from .group import *  # noqa: F401,F403
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/models/group.py", line 67, in <module>
    from sentry.reprocessing2 import get_progress
  File "/usr/local/lib/python3.8/site-packages/sentry/reprocessing2.py", line 93, in <module>
    from sentry.deletions.defaults.group import DIRECT_GROUP_RELATED_MODELS
  File "/usr/local/lib/python3.8/site-packages/sentry/deletions/__init__.py", line 151, in <module>
    load_defaults()
  File "/usr/local/lib/python3.8/site-packages/sentry/deletions/__init__.py", line 93, in load_defaults
    from . import defaults
  File "/usr/local/lib/python3.8/site-packages/sentry/deletions/defaults/__init__.py", line 6, in <module>
    from .group import *  # noqa: F401,F403
  File "/usr/local/lib/python3.8/site-packages/sentry/deletions/defaults/group.py", line 4, in <module>
    from more_itertools import flatten
ModuleNotFoundError: No module named 'more_itertools'
Error in set-up-and-migrate-database.sh:4.
'$dcr web upgrade --noinput' exited with status 1
-> ./install.sh:main:33
--> set-up-and-migrate-database.sh:source:4

Cleaning up...
```

**Workaround**
```
pip3 install more-itertools
Run ./install.sh
```
Got the same error. 

### Expected Result

NA

### Actual Result

```
Running hooks in /etc/ca-certificates/update.d...
done.
19:57:24 [WARNING] sentry.utils.geo: Error opening GeoIP database: /geoip/GeoLite2-City.mmdb
19:57:24 [WARNING] sentry.utils.geo: Error opening GeoIP database in Rust: /geoip/GeoLite2-City.mmdb
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 192, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 28, in inner
    configure()
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 128, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/settings.py", line 153, in configure
    initialize_app(
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py", line 373, in initialize_app
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/sentry_interface_types/models.py", line 2, in <module>
    from sentry.plugins.bases.tag import TagPlugin
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/bases/__init__.py", line 1, in <module>
    from .issue import IssueTrackingPlugin  # NOQA
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/bases/issue.py", line 7, in <module>
    from sentry.plugins.base.v1 import Plugin
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/base/__init__.py", line 1, in <module>
    from .bindings import BindingManager
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/base/bindings.py", line 1, in <module>
    from sentry.plugins.providers import IntegrationRepositoryProvider, RepositoryProvider
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/providers/__init__.py", line 8, in <module>
    from .integration_repository import IntegrationRepositoryProvider
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/providers/integration_repository.py", line 12, in <module>
    from sentry.api.serializers import serialize
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/__init__.py", line 2, in <module>
    from .models import *  # NOQA
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/models/__init__.py", line 29, in <module>
    from .group import *  # noqa: F401,F403
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/models/group.py", line 67, in <module>
    from sentry.reprocessing2 import get_progress
  File "/usr/local/lib/python3.8/site-packages/sentry/reprocessing2.py", line 93, in <module>
    from sentry.deletions.defaults.group import DIRECT_GROUP_RELATED_MODELS
  File "/usr/local/lib/python3.8/site-packages/sentry/deletions/__init__.py", line 151, in <module>
    load_defaults()
  File "/usr/local/lib/python3.8/site-packages/sentry/deletions/__init__.py", line 93, in load_defaults
    from . import defaults
  File "/usr/local/lib/python3.8/site-packages/sentry/deletions/defaults/__init__.py", line 6, in <module>
    from .group import *  # noqa: F401,F403
  File "/usr/local/lib/python3.8/site-packages/sentry/deletions/defaults/group.py", line 4, in <module>
    from more_itertools import flatten
ModuleNotFoundError: No module named 'more_itertools'
Error in set-up-and-migrate-database.sh:4.
'$dcr web upgrade --noinput' exited with status 1
-> ./install.sh:main:33
--> set-up-and-migrate-database.sh:source:4

Cleaning up...
```

**Comment by berry2012** [comment] 2023-01-08 20:47
**Same error in Ubuntu**

**Docker Version**: 20.10.12
**Docker Compose version** v2.14.2

```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

```
ubuntu@ip-192-168-72-130:~/self-hosted$ python -V
Python 3.10.6
ubuntu@ip-192-168-72-130:~/self-hosted$ pip -V
pip 22.3.1 from /home/ubuntu/.local/lib/python3.10/site-packages/pip (python 3.10)
ubuntu@ip-192-168-72-130:~/self-hosted$ 

```

```
Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Started
Container sentry-self-hosted-snuba-outcomes-consumer-1  Started
Container sentry-self-hosted-snuba-sessions-consumer-1  Started
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
20:36:56 [WARNING] sentry.utils.geo: Error opening GeoIP database: /geoip/GeoLite2-City.mmdb
20:36:57 [WARNING] sentry.utils.geo: Error opening GeoIP database in Rust: /geoip/GeoLite2-City.mmdb
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 192, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 28, in inner
    configure()
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 128, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/settings.py", line 153, in configure
    initialize_app(
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py", line 373, in initialize_app
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/sentry_interface_types/models.py", line 2, in <module>
    from sentry.plugins.bases.tag import TagPlugin
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/bases/__init__.py", line 1, in <module>
    from .issue import IssueTrackingPlugin  # NOQA
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/bases/issue.py", line 7, in <module>
    from sentry.plugins.base.v1 import Plugin
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/base/__init__.py", line 1, in <module>
    from .bindings import BindingManager
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/base/bindings.py", line 1, in <module>
    from sentry.plugins.providers import IntegrationRepositoryProvider, RepositoryProvider
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/providers/__init__.py", line 8, in <module>
    from .integration_repository import IntegrationRepositoryProvider
  File "/usr/local/lib/python3.8/site-packages/sentry/plugins/providers/integration_repository.py", line 12, in <module>
    from sentry.api.serializers import serialize
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/__init__.py", line 2, in <module>
    from .models import *  # NOQA
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/models/__init__.py", line 29, in <module>
    from .group import *  # noqa: F401,F403
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/models/group.py", line 67, in <module>
    from sentry.reprocessing2 import get_progress
  File "/usr/local/lib/python3.8/site-packages/sentry/reprocessing2.py", line 93, in <module>
    from sentry.deletions.defaults.group import DIRECT_GROUP_RELATED_MODELS
  File "/usr/local/lib/python3.8/site-packages/sentry/deletions/__init__.py", line 151, in <module>
    load_defaults()
  File "/usr/local/lib/python3.8/site-packages/sentry/deletions/__init__.py", line 93, in load_defaults
    from . import defaults
  File "/usr/local/lib/python3.8/site-packages/sentry/deletions/defaults/__init__.py", line 6, in <module>
    from .group import *  # noqa: F401,F403
  File "/usr/local/lib/python3.8/site-packages/sentry/deletions/defaults/group.py", line 4, in <module>
    from more_itertools import flatten
ModuleNotFoundError: No module named 'more_itertools'
Error in set-up-and-migrate-database.sh:12.
'$dcr web upgrade' exited with status 1
-> ./install.sh:main:33
--> set-up-and-migrate-database.sh:source:12

Cleaning up...
```

**Comment by IceApriler** [comment] 2023-01-09 07:00
Same error

**Comment by chjw8016** [comment] 2023-01-09 09:21
Same error

**Comment by Hitotsubashi** [comment] 2023-01-09 09:28
Same error

**Comment by Hitotsubashi** [comment] 2023-01-09 11:03
No sentry member can help us?

**Comment by i7ak** [comment] 2023-01-09 12:19
Same error

**Comment by Cave-Johnson** [comment] 2023-01-09 12:48
Same here on Ubuntu22

Have confirmed I have valid maxmind geoip config details in the correct location

**Comment by kastyle** [comment] 2023-01-09 15:12
I rolled back to version 22.11.0, the installation went without errors

**Comment by Cave-Johnson** [comment] 2023-01-09 15:16
> I had the exact same problem after updating today. Not sure if this is the correct solution, but I did the following, and now it's working again.
> 
> I created a file "sentry/enhance-image.sh" in root directory (make sure file is executable 0755).
> 
> ![enhance-image_sh0](https://user-images.githubusercontent.com/6997013/211339514-8307dce2-10c1-48c6-8d25-85a5d203c97d.jpg)
> 
> ![enhance-image_sh01](https://user-images.githubusercontent.com/6997013/211339825-e2accccd-dfc7-40b5-87e0-7fa6a042a6ee.jpg)
> 
> Contents of file...
> 
> ```
> #!/bin/bash
> 
> # Enhance the base $SENTRY_IMAGE with additional dependencies, plugins - see https://github.com/getsentry/self-hosted#enhance-sentry-image
> # For example:
> apt-get update
> #apt-get install -y gcc libsasl2-dev python-dev libldap2-dev libssl-dev
> pip install more_itertools
> ```
> 
> then run install script again.
> 
> `./install.sh`
> 
> Enhance Sentry image => https://github.com/getsentry/self-hosted#enhance-sentry-image
> 
> I do get a warning because "_pip install more_itertools_" is being run as root....
> 
> _WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv_

nice work around, can confirm this has worked! Thanks

**Comment by hubertdeng123** [comment] 2023-01-09 15:22
Hi there, sorry that you all are experiencing issues. This seems to be a result of this [PR](https://github.com/getsentry/sentry/pull/41937) in sentry. It was reverted after our nightly images were built, so the install script is failing on master.

**Comment by hubertdeng123** [comment] 2023-01-09 17:02
Should be fixed now everyone.https://github.com/getsentry/sentry/pull/42953

**Comment by ethanhs** [comment] 2023-01-10 19:28
I'm going to go ahead and close this. Please re-run the installer if you run into issues! If you still are having problems, please open a new issue.

**Closed by ethanhs** 2023-01-10 19:28 UTC
Labels: Type: Support Request
