### ISSUE TITLE
Memcached Syntax Error

### ISSUE THREAD

**Issue by rojinebrahimi** [getsentry/self-hosted#2458] opened 2023-10-09 08:25 UTC
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

K8s

### Docker Compose Version

K8s

### Steps to Reproduce

Hi!
I have the memcached syntax issue every time I run a sentry command such as: 

```
sentry shell
```
or other similar commands:

```
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
```

I cannot figure out where might be causing the problem. Any ideas?

### Expected Result

No warnings!

### Actual Result

```
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
```

**Comment by azaslavsky** [comment] 2023-10-10 15:07
Which container is this occurring in?

**Comment by rojinebrahimi** [comment] 2023-10-10 20:45
> Which container is this occurring in?

I have tested it with the main Sentry container - the one with uWSGI running in.

**Comment by hubertdeng123** [comment] 2023-10-12 20:57
This should just be a warning, not something to worry about.

**Comment by hubertdeng123** [comment] 2023-10-12 21:01
Closing as it is a duplicate of this issue here, which exists in sentry. 

https://github.com/getsentry/sentry/issues/42137

**Closed by hubertdeng123** 2023-10-12 21:01 UTC
Labels: Waiting for: Community
