### ISSUE TITLE
Unable to fetch all project stat

### ISSUE THREAD

**Issue by ecxod** [getsentry/self-hosted#1561] opened 2022-07-03 18:31 UTC
### Version

22.6.0

### Steps to Reproduce

After I installed sentry in a virtualenv everything was fine and I could create a project via the web surface.

Then I click on the "Projects" Menu and I get a small failure message in the right bottom 

> Unable to fetch all project stats  

Then I created a second project and went on "Projects" 
it shows both Projects but again I get the 
> Unable to fetch all project stats

If I click on one of the projects I get again in the right lower corner :
> Internal error. Please try again.

![image](https://user-images.githubusercontent.com/102165928/177049733-967cae5b-e1a4-4b89-a809-4867e14acf6b.png)

Can you give a hint where to search?

### Expected Result

to have fun with sentry

### Actual Result

I can't find any logs

**Comment by ethanhs** [comment] 2022-07-05 15:15
Hi, could you please send any errors in the server logs please? You should be able to run `docker-compose logs web`.

**Comment by aminvakil** [comment] 2022-07-06 11:18
> After I installed sentry in a virtualenv everything was fine and I could create a project via the web surface.

Also can you please elaborate on installing in `virtualenv`? Can you share with us how have you installed self-hosted?

**Comment by ecx0d** [comment] 2022-07-15 23:35
> Also can you please elaborate on installing in virtualenv? Can you share with us how have you installed self-hosted?

certainly no problem

```
apt install redis virtualenv postgresql xmlsec1 libxmlsec1-dev

root@sentry:~# su - postgres
postgres@sentry:~$ psql -d template1 -U postgres
template1=#create extension citext;

postgres@sentry:~$ createdb sentrydb
postgres@sentry:~$ createuser sentry --pwprompt

template1=# GRANT ALL PRIVILEGES ON DATABASE sentrydb to sentry;
template1=# ALTER USER sentry WITH SUPERUSER;

root@sentry:~# adduser sentry
root@sentry:~# su - sentry
sentry@sentry:~$ virtualenv ~/sentry_app/
sentry@sentry:~$ source ~/sentry_app/bin/activate
(sentry_app) sentry@sentry:~$ pip install -U sentry
(sentry_app) sentry@sentry:~$ sentry init
(sentry_app) sentry@sentry:~$ vim /home/sentry/.sentry/sentry.conf.py

  DATABASES = { 
     'default': { 
      'ENGINE': 'sentry.db.postgres', 
      'NAME': 'sentrydb', 
      'USER': 'sentry', 
      'PASSWORD': 'verysecretpassword', 
      'HOST': 'localhost', 
      'PORT': '5432', 
      'AUTOCOMMIT': True, 
      'ATOMIC_REQUESTS': False, 
      } 
    }

(sentry_app) sentry@sentry:~$ sentry upgrade

root@sentry:~# apt install supervisor
root@sentry:~# vim /etc/supervisor/conf.d/sentry.conf

  [program:sentry-web] 
  directory=/home/sentry/sentry_app/ 
  environment=SENTRY_CONF=/home/sentry/.sentry 
  command=/home/sentry/sentry_app/bin/sentry run web 
  autostart=true 
  autorestart=true
  redirect_stderr=true
  user=sentry 
  stdout_logfile=syslog 
  stderr_logfile=syslog
   
  [program:sentry-worker] 
  directory=/home/sentry/sentry_app/ 
  environment=SENTRY_CONF=/home/sentry/.sentry 
  command=/home/sentry/sentry_app/bin/sentry run worker 
  autostart=true 
  autorestart=true 
  redirect_stderr=true 
  user=sentry 
  stdout_logfile=syslog 
  stderr_logfile=syslog
   
  [program:sentry-cron] 
  directory=/home/sentry/sentry_app/ 
  environment=SENTRY_CONF=/home/sentry/.sentry 
  command=/home/sentry/sentry_app/bin/sentry run cron 
  autostart=true 
  autorestart=true 
  redirect_stderr=true 
  stdout_logfile=syslog 
  stderr_logfile=syslog

root@sentry:~# supervisorctl reread
root@sentry:~# supervisorctl update
root@sentry:~# supervisorctl start all

```
Next apache proxy and certbot ...

**Comment by aminvakil** [comment] 2022-07-16 14:07
Ah, I don't know if there was a bad tutorial somewhere or anything else that gave you the idea that should do this all manually.

I understand this is a clean install, please nuke everything, database, virtualenv, nuke the machine probably :) as none of them is necessary.

All you want is to git clone this repository and run `./install.sh`.

More info:
https://develop.sentry.dev/self-hosted/#getting-started

**Comment by ecx0d** [comment] 2022-07-23 10:14
it is exactly what I do not want.

**Comment by ecx0d** [comment] 2022-07-23 11:05
> Hi, could you please send any errors in the server logs please? You should be able to run `docker-compose logs web`.

Itried, but it's a 404. fix it first please :))

**Comment by aminvakil** [comment] 2022-07-24 07:27
@ecx0d What do you want?

**Comment by tacoberu** [comment] 2022-08-11 11:59
Good day. I have the same problem.
I installed version 20.12.1 via git and using ./install.sh. I am using the official procedure using docker-composer.
The installation is successful and everything works. The problem is that I am trying to drag and drop data from another machine. I didn't find a better way than copying the volume/sentry-postrgres set.
I have the same version of sentry on both machines. The difference is that the new machine has a different version of ubuntu. Another difference is that I'm only copying volume/sentry-postgres. The other volumes are from a clean installation.
Load me correctly: /settings/sentry/members/.
But wrong: /settings/sentry/projects/ = "Oops! Something went wrong ..."

Can you direct me please?

**Comment by ethanhs** [comment] 2022-08-11 17:08
@tacoberu you may need to follow the backup and restore procedure: https://develop.sentry.dev/self-hosted/backup

**Comment by ethanhs** [comment] 2022-08-11 17:09
I'm going to close this. The solution for OP is to use the official installer. If anyone runs into the same problem, please open a new issue.

**Closed by ethanhs** 2022-08-11 17:09 UTC
Labels: Type: Support Request

**Comment by tacoberu** [comment] 2022-08-11 21:02
@ethanhs 
Export and import failed on different error.
I solved my problem by recopying all volumes (not just for postgres).
