### ISSUE TITLE
No module named 'ldap'

### ISSUE THREAD

**Issue by husim0** [getsentry/self-hosted#1163] opened 2021-11-22 11:41 UTC
### Version

21.11.0

### Steps to Reproduce

1. Add `sentry-ldap-auth` to `sentry/requirements.txt` file
2. Add `apt update && apt install -y gcc libsasl2-dev libldap2-dev libssl-dev` to `sentry/entrypoint.sh` (in order to be able to build ldap plugin)
3. Run `./install.sh`

### Expected Result

I expect to `./install.sh` script to work successfully without any error

### Actual Result

```
[...]
Unpacking libsasl2-modules:amd64 (2.1.27+dfsg-1+deb10u1) ...
Setting up libsasl2-modules:amd64 (2.1.27+dfsg-1+deb10u1) ...
Setting up binutils-common:amd64 (2.31.1-16) ...
Setting up libgomp1:amd64 (8.3.0-6) ...
Setting up libldap-common (2.4.47+dfsg-3+deb10u6) ...
Setting up libsasl2-modules-db:amd64 (2.1.27+dfsg-1+deb10u1) ...
Setting up libasan5:amd64 (8.3.0-6) ...
Setting up libmpfr6:amd64 (4.0.2-1) ...
Setting up libquadmath0:amd64 (8.3.0-6) ...
Setting up libmpc3:amd64 (1.1.0-1) ...
Setting up libatomic1:amd64 (8.3.0-6) ...
Setting up libsasl2-2:amd64 (2.1.27+dfsg-1+deb10u1) ...
Setting up libmpx2:amd64 (8.3.0-6) ...
Setting up libubsan1:amd64 (8.3.0-6) ...
Setting up libisl19:amd64 (0.20-2) ...
Setting up libbinutils:amd64 (2.31.1-16) ...
Setting up cpp-8 (8.3.0-6) ...
Setting up libcc1-0:amd64 (8.3.0-6) ...
Setting up liblsan0:amd64 (8.3.0-6) ...
Setting up libitm1:amd64 (8.3.0-6) ...
Setting up binutils-x86-64-linux-gnu (2.31.1-16) ...
Setting up libtsan0:amd64 (8.3.0-6) ...
Setting up libldap-2.4-2:amd64 (2.4.47+dfsg-3+deb10u6) ...
Setting up binutils (2.31.1-16) ...
Setting up libldap2-dev:amd64 (2.4.47+dfsg-3+deb10u6) ...
Setting up libsasl2-dev (2.1.27+dfsg-1+deb10u1) ...
Setting up libgcc-8-dev:amd64 (8.3.0-6) ...
Setting up cpp (4:8.3.0-1) ...
Setting up gcc-8 (8.3.0-6) ...
Setting up gcc (4:8.3.0-1) ...
Processing triggers for libc-bin (2.28-10) ...
!! Configuration error: ConfigurationError("ModuleNotFoundError: No module named 'ldap'")
1
An error occurred, caught SIGERR on line 12
Cleaning up...
```

**Comment by chadwhitacre** [comment] 2021-11-22 22:37
https://pypi.org/project/sentry-ldap-auth/ > https://github.com/banno/getsentry-ldap-auth

Ask over there? 🤔

**Comment by chadwhitacre** [comment] 2021-11-23 22:49
Is this a dupe of https://github.com/getsentry/self-hosted/issues/882, perhaps?

**Comment by sblaisot** [comment] 2021-12-13 21:33
This issue is that entrypoint has

```
req_file="/etc/sentry/requirements.txt"
plugins_dir="/data/custom-packages"
checksum_file="$plugins_dir/.checksum"

if [[ -s "$req_file" ]] && ! cat "$req_file" | grep '^[^#[:space:]]' | shasum -s -c "$checksum_file" 2>/dev/null; then
    echo "Installing additional dependencies..."
    mkdir -p "$plugins_dir"
    pip install --user -r "$req_file"
    cat "$req_file" | grep '^[^#[:space:]]' | shasum > "$checksum_file"
    echo ""
fi
```

and I bet there is a `.checksum` file from previous version so your python modules in `requirements.txt` are not installed.

Either you find and delete that `.checksum` file in sentry-data docker volume or you can change slightly your `requirements.txt` file to have a different checksum

**Comment by sblaisot** [comment] 2021-12-13 21:33
`.checksum` file was, for me, located in `/var/lib/docker/volumes/sentry-data/_data/custom-packages/.checksum`
Removing that file did the trick

**Comment by chadwhitacre** [comment] 2021-12-13 23:01
Thanks for sharing, @sblaisot. Closing here, @husim0 let us know if this doesn't work for you.

**Closed by chadwhitacre** 2021-12-13 23:01 UTC
Labels: Type: Support Request

**Comment by husim0** [comment] 2021-12-15 08:57
Hello, I had no `.checksum` but removing `/var/lib/docker/volumes/sentry-data/_data/custom-packages/lib` folder seems to do the trick. Thank you !
