### ISSUE TITLE
Snuba commit log off by 1

### ISSUE THREAD

**Issue by ryantam626** [getsentry/self-hosted#2185] opened 2023-06-05 20:42 UTC
### Self-Hosted Version

23.5.2

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

2.12.2

### Steps to Reproduce

1. clone repo
2. SENTRY_IMAGE=getsentry/sentry:23.5.2 ./install.sh
3. configure a project on self hosted sentry
4. start capturing something under this new project
5. poke around inside kafka container
```
docker exec -it sentry-self-hosted-kafka-1 bash
# within the kafka container shell
kafka-consumer-groups --bootstrap-server 127.0.0.1:9092 --all-groups  -describe
kafka-consumer-groups --bootstrap-server 127.0.0.1:9092 --group snuba-consumers -describe
kafka-console-consumer -bootstrap-server 127.0.0.1:9092 -topic snuba-commit-log -from-beginning
```

### Expected Result

I expect the `snuba-commit-log` topic to be closely matching `events` topic (`snuba-consumers` consumer group).

### Actual Result

`snuba-commit-log` topic and `events` topic (`snuba-consumers` consumer group) seem to be consistently off by 1.

Picture illustrating the issue:
![image](https://github.com/getsentry/self-hosted/assets/8895126/477e2684-0347-45d5-b790-c2459375e9ff)

edit: Coming back to re-read this the next day, I think I have the wrong understanding of what offset means, I took it as "what's the latest work a consumer have consumed/done", when in reality it seems to be "where to look for the next message when they are available", in that case, point 2 and 3 are wrong - the `snuba-post-processor` consumer group for `events` should have its current offset advanced to 8, seeing as commit log for 7 is published, and post processor should be done with the work in offset 7. (I have updated the image accordingly)

**Comment by ryantam626** [comment] 2023-06-05 20:51
Related: #1982 - this is flagged in the issue itself, I believe this is the underlying root cause of the issue.
Related: #478 - this consistent lag of 1 could manifest itself as "Offset Out of Range" error, imagine this sequence of events
1. event 1 captured at time A
2. event 1 processed by snuba at time B
3. event 1 commit log NOT generated at time B
4. event 1 not processed by post processor because of commit log lag
5. event 2 captured at time C (in which kafka retention has lapsed)
6. event 2 processed by snuba at time D
7. event 1 commit log generated at time D (because lag)
8. event 1 now attempted to be processed by post processor (since commit log is now present)
9. offset related to event 1 is no longer in kafka => "Offset Out of Range" error

**Comment by ryantam626** [comment] 2023-06-05 20:57
Snuba image used for reference: getsentry/snuba@sha256:6fbc77b9390cea5f3869337172666818f2fa752446ad4bf5652bd626ce6918df

**Comment by hubertdeng123** [comment] 2023-06-06 16:54
Hey there @ryantam626. Yeah, this is an issue that we've noticed for a while now 😔. The best I can do right now is to ping the team that owns snuba for an update, but other than that I've found the commit that broke things if you'd like to dig around yourself. This does seem to be a duplicate of the issue #1982 that you linked above. If you'd like to you can follow up there

**Closed by hubertdeng123** 2023-06-06 16:54 UTC
Labels: Status: Untriaged, Waiting for: Product Owner

**Comment by ryantam626** [comment] 2023-06-06 19:16
Yes sorry, I only noticed the related issue after I opened this.

I will follow up there in the quoted issue if I find anything interesting, I am currently hacking around and looking for clues.
