### ISSUE TITLE
Wrong webhook url validation

### ISSUE THREAD

**Issue by DoubleBoba** [getsentry/self-hosted#2307] opened 2023-07-28 05:31 UTC
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Create a custom internal integration
2. As as webhook URL specify URL with a first level domain like in my case: `http://mm-redirector/redirect-to-mattermost`
3. Save changes

### Expected Result

Custom integration is created successfully

### Actual Result

Validation failed with "Enter a valid URL" message. This URL is totally valid. I have another container running alongside Sentry's cluster with my custom Mattermost integration. So I can and want to access it using the docker domain which is just "mm-redirector". But validation doesn't allow it.

### Product Area

Settings - Integrations

**Comment by hubertdeng123** [comment] 2023-08-01 06:03
Are there logs that can tell us more information about what error the validator is throwing? Seems weird that this is happening but that would help us out a lot in determining the root cause

**Comment by DoubleBoba** [comment] 2023-08-02 02:29
@hubertdeng123 
Where can I see validator logs?

**Comment by hubertdeng123** [comment] 2023-08-03 22:19
Just tested, I can reproduce this myself. I think it's the way how self-hosted is set up, this is not an issue on SaaS. Probably some issue with using django `URLField`

**Comment by hubertdeng123** [comment] 2023-08-03 22:25
Code for URLValidator here:
https://github.com/django/django/blob/main/django/core/validators.py#L69

So, for this to work would need a custom implementation of `URLField` for self-hosted. Otherwise, as a temporary workaround I think you can edit the postgres database to change the webhook url.

**Comment by Christinarlong** [comment] 2024-12-11 23:22
Closing as it looks like there's a workaround currently, but for a fix the team is currently understaffed so we won't be able to prioritize.

**Closed by Christinarlong** 2024-12-11 23:22 UTC
Labels: Type: Bug
