### ISSUE TITLE
Cannot upgrade due to problems with PostgreSQL

### ISSUE THREAD

**Issue by maximal** [getsentry/self-hosted#1216] opened 2021-12-21 15:45 UTC
### Version

I cannot remember the version I upgrade from, but not too old (a month or so).

Unfortunately I cannot see the version I had (Sentry not starting at all). But I do upgrades quite often: once or twice a month.

### Steps to Reproduce

See the logs below. Have I lost all the data?

### Expected Result

`./install.sh` goes fine and do the upgrade and migrations.

### Actual Result

`DEBUG=1 ./install.sh` gives:
```
+++ basename ./install.sh
++ [[ install.sh = \i\n\s\t\a\l\l\.\s\h ]]
+++ dirname ./install.sh
++ cd ./install/
++ [[ -f ../.env.custom ]]
+++ realpath ../.env
++ _ENV=/srv/dev.website.com/sentry-onpremise/.env
+++ mktemp
++ t=/tmp/tmp.FQUOYyPESw
++ export -p
++ set -a
++ . /srv/dev.website.com/sentry-onpremise/.env
+++ COMPOSE_PROJECT_NAME=sentry-self-hosted
+++ SENTRY_EVENT_RETENTION_DAYS=90
+++ SENTRY_BIND=9000
+++ SENTRY_IMAGE=getsentry/sentry:nightly
+++ SNUBA_IMAGE=getsentry/snuba:nightly
+++ RELAY_IMAGE=getsentry/relay:nightly
+++ SYMBOLICATOR_IMAGE=getsentry/symbolicator:nightly
+++ WAL2JSON_VERSION=latest
++ set +a
++ . /tmp/tmp.FQUOYyPESw
+++ declare -x DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
+++ declare -x DEBUG=1
+++ declare -x FQDN=az.website.com
+++ declare -x GIT_CEILING_DIRECTORIES=/:/etc:/home:/home/maximal:/home/maximal/projects
+++ declare -x HOME=/home/maximal
+++ declare -x LANG=C.UTF-8
+++ declare -x LOGNAME=maximal
+++ declare -x 'LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
+++ declare -x MOTD_SHOWN=pam
+++ declare -x 'MYSQL_PS1=[\R:\m]\ \h:\d>\_'
+++ declare -x OLDPWD=/srv/dev.website.com/sentry-onpremise
+++ declare -x PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
+++ declare -x PWD=/srv/dev.website.com/sentry-onpremise/install
+++ declare -x SHELL=/usr/bin/zsh
+++ declare -x SHLVL=2
+++ declare -x 'SSH_CLIENT=176.59.2.38 59771 22'
+++ declare -x 'SSH_CONNECTION=176.59.2.38 59771 91.219.30.181 22'
+++ declare -x SSH_TTY=/dev/pts/0
+++ declare -x TERM=xterm-256color
+++ declare -x USER=maximal
+++ declare -x XDG_RUNTIME_DIR=/run/user/1000
+++ declare -x XDG_SESSION_CLASS=user
+++ declare -x XDG_SESSION_ID=47927
+++ declare -x XDG_SESSION_TYPE=tty
++ rm /tmp/tmp.FQUOYyPESw
++ unset t
++ '[' '' = true ']'
++ _group='▶ '
++ _endgroup=
+++ docker compose version
+++ echo docker-compose
++ dc_base=docker-compose
++ dc='docker-compose --ansi never --env-file /srv/dev.website.com/sentry-onpremise/.env'
++ dcr='docker-compose --ansi never --env-file /srv/dev.website.com/sentry-onpremise/.env run --rm'
++ SENTRY_CONFIG_PY=../sentry/sentry.conf.py
++ SENTRY_CONFIG_YML=../sentry/config.yml
++ STOP_TIMEOUT=60
+ source parse-cli.sh
++ echo '▶ Parsing command line ...'
▶ Parsing command line ...
++ SKIP_USER_PROMPT=
++ MINIMIZE_DOWNTIME=
++ SKIP_COMMIT_CHECK=
++ ((  0  ))
++ echo ''

+ source check-latest-commit.sh
++ echo '▶ Checking for latest commit ... '
▶ Checking for latest commit ... 
++ [[ -d ../.git ]]
++ [[ 0 != 1 ]]
+++ git branch
+++ sed -n '/\* /s///p'
++ [[ master == \m\a\s\t\e\r ]]
+++ git rev-parse HEAD
+++ cut -f1
++++ git rev-parse --abbrev-ref '@{u}'
++++ sed 's/\// /g'
+++ git ls-remote origin master
++ [[ 28e413c5dd04e1170ee8201dd5e11b9b3165b65d != 28e413c5dd04e1170ee8201dd5e11b9b3165b65d ]]
++ echo ''

+ source error-handling.sh
++ echo '▶ Setting up error handling ...'
▶ Setting up error handling ...
++ DID_CLEAN_UP=0
++ trap_with_arg cleanup ERR INT TERM EXIT
++ func=cleanup
++ shift
++ for sig in "$@"
++ trap 'cleanup ERR $LINENO' ERR
++ for sig in "$@"
++ trap 'cleanup INT $LINENO' INT
++ for sig in "$@"
++ trap 'cleanup TERM $LINENO' TERM
++ for sig in "$@"
++ trap 'cleanup EXIT $LINENO' EXIT
++ echo ''

+ source check-minimum-requirements.sh
++ echo '▶ Checking minimum requirements ...'
▶ Checking minimum requirements ...
+++ dirname ./install.sh
++ source ./_min-requirements.sh
+++ MIN_DOCKER_VERSION=19.03.6
+++ MIN_COMPOSE_VERSION=1.28.0
+++ MIN_RAM_HARD=3800
+++ MIN_RAM_SOFT=7800
+++ MIN_CPU_HARD=2
+++ MIN_CPU_SOFT=4
+++ docker version --format '{{.Server.Version}}'
++ DOCKER_VERSION=20.10.12
+++ ver 20.10.12
+++ echo 20.10.12
+++ awk -F. '{ printf("%d%03d%03d", $1,$2,$3); }'
+++ ver 19.03.6
+++ echo 19.03.6
+++ awk -F. '{ printf("%d%03d%03d", $1,$2,$3); }'
++ [[ 20010012 -lt 19003006 ]]
++ docker compose version
+++ docker-compose version
+++ head -n1
+++ sed -E 's/^.* version:? v?([0-9.]+),?.*$/\1/'
++ COMPOSE_VERSION=1.29.2
+++ ver 1.29.2
+++ echo 1.29.2
+++ awk -F. '{ printf("%d%03d%03d", $1,$2,$3); }'
+++ ver 1.28.0
+++ echo 1.28.0
+++ awk -F. '{ printf("%d%03d%03d", $1,$2,$3); }'
++ [[ 1029002 -lt 1028000 ]]
+++ docker run --rm busybox nproc --all
++ CPU_AVAILABLE_IN_DOCKER=6
++ [[ 6 -lt 2 ]]
++ [[ 6 -lt 4 ]]
+++ docker run --rm busybox free -m
+++ awk '/Mem/ {print $2}'
++ RAM_AVAILABLE_IN_DOCKER=16264
++ [[ 16264 -lt 3800 ]]
++ [[ 16264 -lt 7800 ]]
+++ docker run --rm busybox grep -c 'Common KVM processor' /proc/cpuinfo
+++ :
++ IS_KVM=0
++ [[ 0 -eq 0 ]]
+++ docker run --rm busybox grep -c sse4_2 /proc/cpuinfo
++ SUPPORTS_SSE42=6
++ [[ 6 -eq 0 ]]
++ echo ''

+ source create-docker-volumes.sh
++ echo '▶ Creating volumes for persistent storage ...'
▶ Creating volumes for persistent storage ...
+++ docker volume create --name=sentry-clickhouse
++ echo 'Created sentry-clickhouse.'
Created sentry-clickhouse.
+++ docker volume create --name=sentry-data
++ echo 'Created sentry-data.'
Created sentry-data.
+++ docker volume create --name=sentry-kafka
++ echo 'Created sentry-kafka.'
Created sentry-kafka.
+++ docker volume create --name=sentry-postgres
++ echo 'Created sentry-postgres.'
Created sentry-postgres.
+++ docker volume create --name=sentry-redis
++ echo 'Created sentry-redis.'
Created sentry-redis.
+++ docker volume create --name=sentry-symbolicator
++ echo 'Created sentry-symbolicator.'
Created sentry-symbolicator.
+++ docker volume create --name=sentry-zookeeper
++ echo 'Created sentry-zookeeper.'
Created sentry-zookeeper.
++ echo ''

+ source ensure-files-from-examples.sh
++ echo '▶ Ensuring files from examples ...'
▶ Ensuring files from examples ...
++ ensure_file_from_example ../sentry/sentry.conf.py
++ [[ -f ../sentry/sentry.conf.py ]]
++ echo '../sentry/sentry.conf.py already exists, skipped creation.'
../sentry/sentry.conf.py already exists, skipped creation.
++ ensure_file_from_example ../sentry/config.yml
++ [[ -f ../sentry/config.yml ]]
++ echo '../sentry/config.yml already exists, skipped creation.'
../sentry/config.yml already exists, skipped creation.
++ ensure_file_from_example ../symbolicator/config.yml
++ [[ -f ../symbolicator/config.yml ]]
++ echo '../symbolicator/config.yml already exists, skipped creation.'
../symbolicator/config.yml already exists, skipped creation.
++ ensure_file_from_example ../sentry/requirements.txt
++ [[ -f ../sentry/requirements.txt ]]
++ echo '../sentry/requirements.txt already exists, skipped creation.'
../sentry/requirements.txt already exists, skipped creation.
++ echo ''

+ source generate-secret-key.sh
++ echo '▶ Generating secret key ...'
▶ Generating secret key ...
++ grep -xq 'system.secret-key: '\''!!changeme!!'\''' ../sentry/config.yml
++ echo ''

+ source replace-tsdb.sh
++ echo '▶ Replacing TSDB ...'
▶ Replacing TSDB ...
++ replace_tsdb
++ [[ -f ../sentry/sentry.conf.py ]]
++ grep -xq 'SENTRY_TSDB = "sentry.tsdb.redissnuba.RedisSnubaTSDB"' ../sentry/sentry.conf.py
++ echo ''

+ source update-docker-images.sh
++ echo '▶ Fetching and updating Docker images ...'
▶ Fetching and updating Docker images ...
++ docker-compose --ansi never --env-file /srv/dev.website.com/sentry-onpremise/.env pull -q --ignore-pull-failures
++ grep -v -- -self-hosted-local
Some service image(s) must be built from source by running:
	docker-compose build sentry-cleanup snuba-transactions-cleanup snuba-cleanup symbolicator-cleanup
++ docker pull getsentry/sentry:nightly
nightly: Pulling from getsentry/sentry
Digest: sha256:3226f8e22997ffa56881bd90625fe542e3599ec276762eaa4012c5984ccb57a7
Status: Image is up to date for getsentry/sentry:nightly
docker.io/getsentry/sentry:nightly
++ echo ''

+ source build-docker-images.sh
++ echo '▶ Building and tagging Docker images ...'
▶ Building and tagging Docker images ...
++ echo ''

++ docker-compose --ansi never --env-file /srv/dev.website.com/sentry-onpremise/.env build --force-rm
smtp uses an image, skipping
memcached uses an image, skipping
redis uses an image, skipping
postgres uses an image, skipping
zookeeper uses an image, skipping
kafka uses an image, skipping
clickhouse uses an image, skipping
geoipupdate uses an image, skipping
snuba-api uses an image, skipping
snuba-consumer uses an image, skipping
snuba-outcomes-consumer uses an image, skipping
snuba-sessions-consumer uses an image, skipping
snuba-transactions-consumer uses an image, skipping
snuba-replacer uses an image, skipping
snuba-subscription-consumer-events uses an image, skipping
snuba-subscription-consumer-transactions uses an image, skipping
symbolicator uses an image, skipping
web uses an image, skipping
cron uses an image, skipping
worker uses an image, skipping
ingest-consumer uses an image, skipping
post-process-forwarder uses an image, skipping
subscription-consumer-events uses an image, skipping
subscription-consumer-transactions uses an image, skipping
relay uses an image, skipping
nginx uses an image, skipping
Building snuba-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 9525d381e60f
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 26c8cdd205bf
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> 9725dc73e0fa
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> d23f560c411f
Successfully built d23f560c411f
Successfully tagged snuba-cleanup-self-hosted-local:latest
Building snuba-transactions-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 9525d381e60f
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 26c8cdd205bf
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> 9725dc73e0fa
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> d23f560c411f
Successfully built d23f560c411f
Successfully tagged snuba-cleanup-self-hosted-local:latest
Building symbolicator-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 2f0543dbb84f
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 91420afffef6
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> 9b23274a15f6
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> cd897c6dc2d9
Successfully built cd897c6dc2d9
Successfully tagged symbolicator-cleanup-self-hosted-local:latest
Building sentry-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> af51bc6758e9
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 4c3ff893c8c3
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> a88f80ff1eea
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 09a37c587b6c
Successfully built 09a37c587b6c
Successfully tagged sentry-cleanup-self-hosted-local:latest
++ echo ''

++ echo 'Docker images built.'
Docker images built.
++ echo ''

+ source turn-things-off.sh
++ echo '▶ Turning things off ...'
▶ Turning things off ...
++ [[ -n '' ]]
++ docker-compose --ansi never --env-file /srv/dev.website.com/sentry-onpremise/.env down -t 60 --rmi local --remove-orphans
Removing sentry-self-hosted_snuba-subscription-consumer-transactions_1 ... 
Removing sentry-self-hosted_snuba-consumer_1                           ... 
Removing sentry-self-hosted_snuba-transactions-consumer_1              ... 
Removing sentry-self-hosted_snuba-api_1                                ... 
Removing sentry-self-hosted_snuba-outcomes-consumer_1                  ... 
Removing sentry-self-hosted_snuba-sessions-consumer_1                  ... 
Removing sentry-self-hosted_snuba-subscription-consumer-events_1       ... 
Removing sentry-self-hosted_snuba-replacer_1                           ... 
Removing sentry-self-hosted_memcached_1                                ... 
Removing sentry-self-hosted_postgres_1                                 ... 
Removing sentry-self-hosted_symbolicator_1                             ... 
Removing sentry-self-hosted_smtp_1                                     ... 
Removing sentry-self-hosted_kafka_1                                    ... 
Removing sentry-self-hosted_zookeeper_1                                ... 
Removing sentry-self-hosted_clickhouse_1                               ... 
Removing sentry-self-hosted_redis_1                                    ... 
Removing sentry-self-hosted_snuba-sessions-consumer_1                  ... done
Removing sentry-self-hosted_snuba-transactions-consumer_1              ... done
Removing sentry-self-hosted_snuba-api_1                                ... done
Removing sentry-self-hosted_snuba-outcomes-consumer_1                  ... done
Removing sentry-self-hosted_redis_1                                    ... done
Removing sentry-self-hosted_kafka_1                                    ... done
Removing sentry-self-hosted_memcached_1                                ... done
Removing sentry-self-hosted_zookeeper_1                                ... done
Removing sentry-self-hosted_symbolicator_1                             ... done
Removing sentry-self-hosted_postgres_1                                 ... done
Removing sentry-self-hosted_snuba-subscription-consumer-transactions_1 ... done
Removing sentry-self-hosted_snuba-subscription-consumer-events_1       ... done
Removing sentry-self-hosted_smtp_1                                     ... done
Removing sentry-self-hosted_snuba-consumer_1                           ... done
Removing sentry-self-hosted_snuba-replacer_1                           ... done
Removing sentry-self-hosted_clickhouse_1                               ... done
Removing network sentry-self-hosted_default
++ echo ''

+ source set-up-zookeeper.sh
++ echo '▶ Setting up Zookeeper ...'
▶ Setting up Zookeeper ...
+++ docker-compose --ansi never --env-file /srv/dev.website.com/sentry-onpremise/.env run --rm zookeeper bash -c 'ls 2>/dev/null -Ubad1 -- /var/lib/zookeeper/data/version-2 | wc -l | tr -d [:space:]'
Creating network "sentry-self-hosted_default" with the default driver
Creating sentry-self-hosted_zookeeper_run ... 
Creating sentry-self-hosted_zookeeper_run ... done
++ ZOOKEEPER_SNAPSHOT_FOLDER_EXISTS=1
++ [[ 1 -eq 1 ]]
+++ docker-compose --ansi never --env-file /srv/dev.website.com/sentry-onpremise/.env run --rm zookeeper bash -c 'ls 2>/dev/null -Ubad1 -- /var/lib/zookeeper/log/version-2/* | wc -l | tr -d [:space:]'
Creating sentry-self-hosted_zookeeper_run ... 
Creating sentry-self-hosted_zookeeper_run ... done
++ ZOOKEEPER_LOG_FILE_COUNT=3
+++ docker-compose --ansi never --env-file /srv/dev.website.com/sentry-onpremise/.env run --rm zookeeper bash -c 'ls 2>/dev/null -Ubad1 -- /var/lib/zookeeper/data/version-2/* | wc -l | tr -d [:space:]'
Creating sentry-self-hosted_zookeeper_run ... 
Creating sentry-self-hosted_zookeeper_run ... done
++ ZOOKEEPER_SNAPSHOT_FILE_COUNT=3
++ cd ..
++ [[ 3 -gt 0 ]]
++ [[ 3 -eq 0 ]]
++ cd install
++ echo ''

+ source install-wal2json.sh
++ echo '▶ Downloading and installing wal2json ...'
▶ Downloading and installing wal2json ...
++ FILE_TO_USE=../postgres/wal2json/wal2json.so
+++ uname -m
++ ARCH=x86_64
++ FILE_NAME=wal2json-Linux-x86_64-glibc.so
++ [[ latest == \l\a\t\e\s\t ]]
+++ docker_curl https://api.github.com/repos/getsentry/wal2json/releases/latest
+++ docker run --rm -e http_proxy -e https_proxy -e HTTPS_PROXY -e no_proxy -e NO_PROXY curlimages/curl:7.77.0 https://api.github.com/repos/getsentry/wal2json/releases/latest
+++ grep '"tag_name":'
+++ sed -E 's/.*"([^"]+)".*/\1/'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
								 Dload  Upload   Total   Spent    Left  Speed
100  5417  100  5417    0     0  20076      0 --:--:-- --:--:-- --:--:-- 20137
++ VERSION=0.0.2
++ [[ ! -n 0.0.2 ]]
++ mkdir -p ../postgres/wal2json
++ '[' '!' -f ../postgres/wal2json/0.0.2/wal2json-Linux-x86_64-glibc.so ']'
++ cp ../postgres/wal2json/0.0.2/wal2json-Linux-x86_64-glibc.so ../postgres/wal2json/wal2json.so
++ echo ''

+ source bootstrap-snuba.sh
++ echo '▶ Bootstrapping and migrating Snuba ...'
▶ Bootstrapping and migrating Snuba ...
++ docker-compose --ansi never --env-file /srv/dev.website.com/sentry-onpremise/.env run --rm snuba-api bootstrap --no-migrate --force
Creating sentry-self-hosted_zookeeper_1 ... 
Creating sentry-self-hosted_clickhouse_1 ... 
Creating sentry-self-hosted_redis_1      ... 
Creating sentry-self-hosted_redis_1      ... done
Creating sentry-self-hosted_clickhouse_1 ... done
Creating sentry-self-hosted_zookeeper_1  ... done
Creating sentry-self-hosted_kafka_1      ... 
Creating sentry-self-hosted_kafka_1      ... done
Creating sentry-self-hosted_snuba-api_run ... 
Creating sentry-self-hosted_snuba-api_run ... done
2021-12-21 15:34:05,256 Attempting to connect to Kafka (attempt 0)...
2021-12-21 15:34:05,300 Connected to Kafka on attempt 0
2021-12-21 15:34:05,301 Creating Kafka topics...
++ docker-compose --ansi never --env-file /srv/dev.website.com/sentry-onpremise/.env run --rm snuba-api migrations migrate --force
Creating sentry-self-hosted_snuba-api_run ... 
Creating sentry-self-hosted_snuba-api_run ... done
Finished running migrations
++ echo ''

+ source create-kafka-topics.sh
++ echo '▶ Creating additional Kafka topics ...'
▶ Creating additional Kafka topics ...
+++ docker-compose --ansi never --env-file /srv/dev.website.com/sentry-onpremise/.env run --rm kafka kafka-topics --list --bootstrap-server kafka:9092
++ EXISTING_KAFKA_TOPICS='__consumer_offsets
cdc
event-replacements
event-replacements-legacy
events
events-subscription-results
ingest-attachments
ingest-events
ingest-sessions
ingest-transactions
metrics-subscription-results
outcomes
scheduled-subscriptions-events
scheduled-subscriptions-metrics
scheduled-subscriptions-sessions
scheduled-subscriptions-transactions
sessions-subscription-results
snuba-commit-log
snuba-metrics
snuba-metrics-commit-log
snuba-queries
snuba-sessions-commit-log
'ransactions-subscription-results
++ NEEDED_KAFKA_TOPICS='ingest-attachments ingest-transactions ingest-events'
++ for topic in $NEEDED_KAFKA_TOPICS
++ echo '__consumer_offsets
cdc
event-replacements
event-replacements-legacy
events
events-subscription-results
ingest-attachments
ingest-events
ingest-sessions
ingest-transactions
metrics-subscription-results
outcomes
scheduled-subscriptions-events
scheduled-subscriptions-metrics
scheduled-subscriptions-sessions
scheduled-subscriptions-transactions
sessions-subscription-results
snuba-commit-log
snuba-metrics
snuba-metrics-commit-log
snuba-queries
snuba-sessions-commit-log
'ransactions-subscription-results
++ grep -wq ingest-attachments
++ for topic in $NEEDED_KAFKA_TOPICS
++ echo '__consumer_offsets
cdc
event-replacements
event-replacements-legacy
events
events-subscription-results
ingest-attachments
ingest-events
ingest-sessions
ingest-transactions
metrics-subscription-results
outcomes
scheduled-subscriptions-events
scheduled-subscriptions-metrics
scheduled-subscriptions-sessions
scheduled-subscriptions-transactions
sessions-subscription-results
snuba-commit-log
snuba-metrics
snuba-metrics-commit-log
snuba-queries
snuba-sessions-commit-log
'ransactions-subscription-results
++ grep -wq ingest-transactions
++ for topic in $NEEDED_KAFKA_TOPICS
++ echo '__consumer_offsets
cdc
event-replacements
event-replacements-legacy
events
events-subscription-results
ingest-attachments
ingest-events
ingest-sessions
ingest-transactions
metrics-subscription-results
outcomes
scheduled-subscriptions-events
scheduled-subscriptions-metrics
scheduled-subscriptions-sessions
scheduled-subscriptions-transactions
sessions-subscription-results
snuba-commit-log
snuba-metrics
snuba-metrics-commit-log
snuba-queries
snuba-sessions-commit-log
'ransactions-subscription-results
++ grep -wq ingest-events
++ echo ''

+ source upgrade-postgres.sh
++ echo '▶ Ensuring proper PostgreSQL version ...'
▶ Ensuring proper PostgreSQL version ...
+++ docker volume ls -q --filter name=sentry-postgres
++ [[ -n sentry-postgres ]]
+++ docker run --rm -v sentry-postgres:/db busybox cat /db/PG_VERSION
++ [[ 9.6 == \9\.\5 ]]
++ echo ''

+ source set-up-and-migrate-database.sh
++ echo '▶ Setting up / migrating database ...'
▶ Setting up / migrating database ...
++ [[ -n '' ]]
++ [[ 0 == 1 ]]
++ docker-compose --ansi never --env-file /srv/dev.website.com/sentry-onpremise/.env run --rm web upgrade
Creating sentry-self-hosted_memcached_1 ... 
Creating sentry-self-hosted_postgres_1  ... 
Creating sentry-self-hosted_symbolicator_1 ... 
Creating sentry-self-hosted_smtp_1         ... 
Creating sentry-self-hosted_snuba-replacer_1 ... 
Creating sentry-self-hosted_snuba-subscription-consumer-events_1 ... 
Creating sentry-self-hosted_snuba-sessions-consumer_1            ... 
Creating sentry-self-hosted_snuba-transactions-consumer_1        ... 
Creating sentry-self-hosted_snuba-subscription-consumer-transactions_1 ... 
Creating sentry-self-hosted_snuba-outcomes-consumer_1                  ... 
Creating sentry-self-hosted_snuba-api_1                                ... 
Creating sentry-self-hosted_snuba-consumer_1                           ... 
Creating sentry-self-hosted_postgres_1                                 ... done
Creating sentry-self-hosted_memcached_1                                ... done
Creating sentry-self-hosted_smtp_1                                     ... done
Creating sentry-self-hosted_symbolicator_1                             ... done
Creating sentry-self-hosted_snuba-replacer_1                           ... done
Creating sentry-self-hosted_snuba-sessions-consumer_1                  ... done
Creating sentry-self-hosted_snuba-transactions-consumer_1              ... done
Creating sentry-self-hosted_snuba-subscription-consumer-transactions_1 ... done
Creating sentry-self-hosted_snuba-outcomes-consumer_1                  ... done
Creating sentry-self-hosted_snuba-subscription-consumer-events_1       ... done
Creating sentry-self-hosted_snuba-api_1                                ... done
Creating sentry-self-hosted_snuba-consumer_1                           ... done

ERROR: for web  Container "f5499e97519a" is unhealthy.
Encountered errors while bringing up the project.
+++ cleanup ERR 12
+++ [[ 0 -eq 1 ]]
+++ DID_CLEAN_UP=1
+++ [[ ERR != \E\X\I\T ]]
+++ echo 'An error occurred, caught SIGERR on line 12'
An error occurred, caught SIGERR on line 12
+++ [[ -n '' ]]
+++ echo 'Cleaning up...'
Cleaning up...
+++ [[ -z '' ]]
+++ docker-compose --ansi never --env-file /srv/dev.website.com/sentry-onpremise/.env stop -t 60
+ cleanup EXIT 1
+ [[ 1 -eq 1 ]]
+ return 0
```

I even cannot start Sentry:
```
Starting sentry-self-hosted_redis_1                ... done
Starting sentry-self-hosted_clickhouse_1           ... done
Starting sentry-self-hosted_symbolicator_1         ... done
Starting sentry-self-hosted_zookeeper_1            ... done
Starting sentry-self-hosted_memcached_1            ... done
Creating sentry-self-hosted_symbolicator-cleanup_1 ... done
Starting sentry-self-hosted_smtp_1                 ... done
Starting sentry-self-hosted_postgres_1             ... done
Creating sentry-self-hosted_geoipupdate_1          ... done
Starting sentry-self-hosted_kafka_1                ... done
Starting sentry-self-hosted_snuba-subscription-consumer-events_1       ... done
Starting sentry-self-hosted_snuba-subscription-consumer-transactions_1 ... done
Creating sentry-self-hosted_snuba-cleanup_1                            ... done
Starting sentry-self-hosted_snuba-transactions-consumer_1              ... done
Starting sentry-self-hosted_snuba-sessions-consumer_1                  ... done
Starting sentry-self-hosted_snuba-consumer_1                           ... done
Starting sentry-self-hosted_snuba-replacer_1                           ... done
Starting sentry-self-hosted_snuba-api_1                                ... done
Creating sentry-self-hosted_snuba-transactions-cleanup_1               ... done
Starting sentry-self-hosted_snuba-outcomes-consumer_1                  ... done

ERROR: for web  Container "f5499e97519a" is unhealthy.

ERROR: for sentry-cleanup  Container "f5499e97519a" is unhealthy.

ERROR: for subscription-consumer-transactions  Container "f5499e97519a" is unhealthy.

ERROR: for worker  Container "f5499e97519a" is unhealthy.

ERROR: for cron  Container "f5499e97519a" is unhealthy.

ERROR: for post-process-forwarder  Container "f5499e97519a" is unhealthy.

ERROR: for subscription-consumer-events  Container "f5499e97519a" is unhealthy.

ERROR: for ingest-consumer  Container "f5499e97519a" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

Now Postgre is in loop and not starting:
```
postgres_1                                  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1                                  | 
postgres_1                                  | LOG:  database system was shut down at 2021-12-21 02:40:01 UTC
postgres_1                                  | LOG:  invalid primary checkpoint record
postgres_1                                  | LOG:  invalid resource manager ID in secondary checkpoint record
postgres_1                                  | PANIC:  could not locate a valid checkpoint record
postgres_1                                  | LOG:  startup process (PID 33) was terminated by signal 6: Aborted
postgres_1                                  | LOG:  aborting startup due to startup process failure
postgres_1                                  | LOG:  database system is shut down
```

**Comment by chadwhitacre** [comment] 2021-12-21 18:29
This is definitely a dupe of #1211, which may itself be a duplicate of #1178.

**Closed by chadwhitacre** 2021-12-21 18:29 UTC
Labels: Status: Untriaged
