### ISSUE TITLE
24.6.0 self-hosted Web Vitals not work

### ISSUE THREAD

**Issue by ninejy-io** [getsentry/self-hosted#3187] opened 2024-07-08 10:13 UTC
### Self-Hosted Version

24.6.0

### CPU Architecture

x86_64

### Docker Version

20.10.13

### Docker Compose Version

v2.28.1

### Steps to Reproduce

./install.sh
docker-compose up -d

The functionalities under performace are not work.

![sentry_err](https://github.com/getsentry/self-hosted/assets/16144744/ec9ce77b-dd5c-4eb1-ab7c-3edc014deff9)

From saas version I found these functionalities are under Insights tab, I want to know the reason.

![sentry_saas](https://github.com/getsentry/self-hosted/assets/16144744/58d00bea-ecf0-4180-a335-884943b8dbe7)

### Expected Result

Want to use Web Vitals functionality

### Actual Result

Running migrations for default
Operations to perform:
  Apply all migrations: auth, contenttypes, feedback, hybridcloud, nodestore, replays, sentry, sessions, sites, social_auth
Running migrations:
  No migrations to apply.
Creating missing DSNs
Correcting Group.num_comments counter
09:46:25 [INFO] sentry.outboxes: Executing outbox replication backfill
09:46:25 [INFO] sentry.outboxes: Processing sentry.ControlOutboxs...
09:46:25 [INFO] sentry.outboxes: Processing sentry.RegionOutboxs...
09:46:25 [INFO] sentry.outboxes: done

▶ Setting up GeoIP integration ...
Setting up IP address geolocation ...
IP address geolocation database already exists.
IP address geolocation is not configured for updates.
See https://develop.sentry.dev/self-hosted/geolocation/ for instructions.
Error setting up IP address geolocation.

-----------------------------------------------------------------

You're all done! Run the following command to get Sentry running:

  docker-compose up -d

-----------------------------------------------------------------

**Comment by aldy505** [comment] 2024-07-08 13:01
Marking this as a duplicate of https://github.com/getsentry/self-hosted/issues/3145, add these feature flags on the `sentry.conf.py` then re-run `install.sh` script:

```py
"organizations:performance-insights",
"organizations:insights-addon-modules",
"projects:span-metrics-extraction-addons",
```

**Closed by aldy505** 2024-07-08 13:01 UTC
Labels: Waiting for: Product Owner
