### ISSUE TITLE
sentry.models.userip.MultipleObjectsReturned: get() returned more than one UserIP -- it returned 2!

### ISSUE THREAD

**Issue by L-U-C-K-Y** [getsentry/self-hosted#2437] opened 2023-09-29 11:12 UTC
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

Docker version 24.0.6, build ed223bc

### Docker Compose Version

Docker version 24.0.6, build ed223bc

### Steps to Reproduce

1. create backup on one system with scripts ./scripts/backup
2. Copy ./sentry/backup.json in old system
3. Past ./sentry/backup.json in new system
4. restore backup on another system with scripts ./scripts/restore

### Expected Result

Migration should work

### Actual Result

I am unable to perform a migration from one system to another system.

Here is the full log:

```bash
 Container sentry-self-hosted-clickhouse-1  Created
 Container sentry-self-hosted-symbolicator-1  Created
 Container sentry-self-hosted-memcached-1  Created
 Container sentry-self-hosted-zookeeper-1  Created
 Container sentry-self-hosted-kafka-1  Created
 Container sentry-self-hosted-vroom-1  Created
 Container sentry-self-hosted-postgres-1  Created
 Container sentry-self-hosted-redis-1  Created
 Container sentry-self-hosted-snuba-transactions-consumer-1  Created
 Container sentry-self-hosted-smtp-1  Created
 Container sentry-self-hosted-snuba-consumer-1  Created
 Container sentry-self-hosted-snuba-replacer-1  Created
 Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Created
 Container sentry-self-hosted-snuba-outcomes-consumer-1  Created
 Container sentry-self-hosted-snuba-sessions-consumer-1  Created
 Container sentry-self-hosted-snuba-api-1  Created
 Container sentry-self-hosted-snuba-subscription-consumer-events-1  Created
 Container sentry-self-hosted-smtp-1  Starting
 Container sentry-self-hosted-memcached-1  Starting
 Container sentry-self-hosted-redis-1  Starting
 Container sentry-self-hosted-symbolicator-1  Starting
 Container sentry-self-hosted-postgres-1  Starting
 Container sentry-self-hosted-zookeeper-1  Starting
 Container sentry-self-hosted-clickhouse-1  Starting
 Container sentry-self-hosted-smtp-1  Started
 Container sentry-self-hosted-clickhouse-1  Started
 Container sentry-self-hosted-postgres-1  Started
 Container sentry-self-hosted-symbolicator-1  Started
 Container sentry-self-hosted-zookeeper-1  Started
 Container sentry-self-hosted-zookeeper-1  Waiting
 Container sentry-self-hosted-redis-1  Started
 Container sentry-self-hosted-memcached-1  Started
 Container sentry-self-hosted-zookeeper-1  Healthy
 Container sentry-self-hosted-kafka-1  Starting
 Container sentry-self-hosted-kafka-1  Started
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-api-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-outcomes-consumer-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-subscription-consumer-events-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-consumer-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-sessions-consumer-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-vroom-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-transactions-consumer-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-replacer-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Starting
 Container sentry-self-hosted-snuba-subscription-consumer-events-1  Started
 Container sentry-self-hosted-snuba-outcomes-consumer-1  Started
 Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Started
 Container sentry-self-hosted-snuba-consumer-1  Started
 Container sentry-self-hosted-snuba-replacer-1  Started
 Container sentry-self-hosted-vroom-1  Started
 Container sentry-self-hosted-snuba-sessions-consumer-1  Started
 Container sentry-self-hosted-snuba-api-1  Started
 Container sentry-self-hosted-snuba-transactions-consumer-1  Started
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 193, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/backup.py", line 120, in import_global
    import_in_global_scope(
  File "/usr/local/lib/python3.8/site-packages/sentry/backup/imports.py", line 246, in import_in_global_scope
    return _import(src, ImportScope.Global, flags=flags, printer=printer)
  File "/usr/local/lib/python3.8/site-packages/sentry/backup/imports.py", line 143, in _import
    written = o.write_relocation_import(scope, flags)
  File "/usr/local/lib/python3.8/site-packages/sentry/models/userip.py", line 80, in write_relocation_import
    (userip, created) = self.__class__.objects.get_or_create(
  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 160, in override
    return original_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 160, in override
    return original_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
sentry.models.userip.MultipleObjectsReturned: get() returned more than one UserIP -- it returned 2!
Error in scripts/_lib.sh:69.
'$dc run --rm -T web import global /etc/sentry/backup.json' exited with status 1
-> ./scripts/restore.sh:main:4
--> scripts/_lib.sh:restore:69

Cleaning up...
```

**Comment by azaslavsky** [comment] 2023-10-02 22:55
Are you importing into a clean database? When you run install.sh on target system, are you doing so while setting the `--skip-user-creation` flag set?

If you are still having issues after confirming the above, would it be possible to produce a minimal reproduction of the JSON (sanitized, of course!) that causes this bug? You should be able to look at the JSON file in question, and identify a pair of "sentry.userip" entries that share the same `user` field. It may look something like this:

```

{
  "model": "sentry.userip",
  "pk": 1,
  "fields": {
    "user": 31,
    "ip_address": "127.0.0.1",
    "country_code": null,
    "region_code": null,
    "first_seen": "2023-09-24T17:12:11.220Z",
    "last_seen": "2023-09-24T17:12:11.228Z"
  }
},
{
  "model": "sentry.userip",
  "pk": 1,
  "fields": {
    "user": 31, // <- NOTE that this is the same `user` as above!
    "ip_address": "127.0.0.2",
    "country_code": null,
    "region_code": null,
    "first_seen": "2023-09-24T17:12:11.220Z",
    "last_seen": "2023-09-24T17:12:11.228Z"
  }
},
```

**Comment by max-mycarly** [comment] 2023-10-16 15:05
I can confirm this issue.
The generated backup.json (Sentry 23.9.1) contains several entries for different users.
```
...
{
  "model": "sentry.userip",
  "pk": 340,
  "fields": {
    "user": 7,
    "ip_address": "127.0.0.1",
    "country_code": "DE",
    "region_code": "BY",
    "first_seen": "2023-08-07T05:49:40.356Z",
    "last_seen": "2023-08-07T05:49:40.352Z"
  }
},
{
  "model": "sentry.userip",
  "pk": 341,
  "fields": {
    "user": 5,
    "ip_address": "127.0.0.1",
    "country_code": "DE",
    "region_code": null,
    "first_seen": "2023-08-09T16:33:40.376Z",
    "last_seen": "2023-08-09T16:33:40.364Z"
  }
},
{
  "model": "sentry.userip",
  "pk": 342,
  "fields": {
    "user": 5,
    "ip_address": "127.0.0.2",
    "country_code": "DE",
    "region_code": null,
    "first_seen": "2023-08-10T06:46:18.630Z",
    "last_seen": "2023-08-10T10:50:42.272Z"
  }
},
{
  "model": "sentry.userip",
  "pk": 343,
  "fields": {
    "user": 5,
    "ip_address": "127.0.0.3",
    "country_code": "DE",
    "region_code": null,
    "first_seen": "2023-08-10T07:02:13.888Z",
    "last_seen": "2023-08-10T09:00:10.904Z"
  }
}
...
```
restore.sh fails with before mentioned error as long as you do not manually remove the "duplicate" "sentry.userip" entries.
In my example all but one entry for "user": 5

**Comment by azaslavsky** [comment] 2023-10-16 17:22
Are you restoring onto a clean database? A "global" restore assumes a clean database (no existing users). If you just want the users or orgs, and are okay with existing data being potentially mutated, you can do `sentry import users <PATH_TO_IMPORT> --merge_users` or `sentry import organizations <PATH_TO_IMPORT> --merge_users`.

**Comment by max-mycarly** [comment] 2023-10-17 06:01
Yes, we are trying to restore the backup into a fresh install on a blank instance.

1. git pull ...
2. install.sh  --skip-user-creation
3. restore.sh

Thats all

**Comment by azaslavsky** [comment] 2023-10-17 15:43
Are you able to connect to the postgres instance directly? Can you tell me how many entries you have in the `auth_user` and `sentry_userip` tables? My suspicion is that you have only `admin@localhost` in your `auth_user` table?

**Comment by max-mycarly** [comment] 2023-10-18 09:10
I did a new test today. I created a new backup.json (Sentry 23.10.0) and tried to restore it into a fresh Sentry 23.10.0.
Unfortunately, the error still occurs.

As you requested i connected to the postgres instance before restore:
```
psql (14.5 (Debian 14.5-2.pgdg110+2))
Type "help" for help.

postgres=# SELECT * FROM auth_user;
 id | password | last_login | username | first_name | email | is_staff | is_active | is_superuser | is_managed | is_sentry_app | is_password_expired | last_password_
change | flags | session_nonce | date_joined | last_active | avatar_type | avatar_url | is_unclaimed
----+----------+------------+----------+------------+-------+----------+-----------+--------------+------------+---------------+---------------------+---------------
-------+-------+---------------+-------------+-------------+-------------+------------+--------------
(0 rows)


postgres=# SELECT * FROM sentry_userip;
 id | ip_address | country_code | region_code | first_seen | last_seen | user_id
----+------------+--------------+-------------+------------+-----------+---------
(0 rows)
```

Error output at the end
```
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 195, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/backup.py", line 239, in import_global
    import_in_global_scope(
  File "/usr/local/lib/python3.8/site-packages/sentry/backup/imports.py", line 340, in import_in_global_scope
    return _import(
  File "/usr/local/lib/python3.8/site-packages/sentry/backup/imports.py", line 211, in _import
    do_write()
  File "/usr/local/lib/python3.8/site-packages/sentry/backup/imports.py", line 191, in do_write
    written = o.write_relocation_import(scope, flags)
  File "/usr/local/lib/python3.8/site-packages/sentry/models/userip.py", line 82, in write_relocation_import
    (userip, created) = self.__class__.objects.get_or_create(
  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 160, in override
    return original_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 160, in override
    return original_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
sentry.models.userip.MultipleObjectsReturned: get() returned more than one UserIP -- it returned 2!
Error in scripts/_lib.sh:69.
'$dc run --rm -T web import global /etc/sentry/backup.json' exited with status 1
-> ./scripts/restore.sh:main:4
--> scripts/_lib.sh:restore:69

Cleaning up...
```

**Comment by azaslavsky** [comment] 2023-10-19 15:36
Any luck with connecting to the database directly to query those tables? I suspect this is a bug in the global backup/restore script, but I'll need more information to publish a fix.

**Comment by max-mycarly** [comment] 2023-10-19 16:12
Sure, both tables are empty.

```
psql (14.5 (Debian 14.5-2.pgdg110+2))
Type "help" for help.

postgres=# SELECT * FROM auth_user;
 id | password | last_login | username | first_name | email | is_staff | is_active | is_superuser | is_managed | is_sentry_app | is_password_expired | last_password_
change | flags | session_nonce | date_joined | last_active | avatar_type | avatar_url | is_unclaimed
----+----------+------------+----------+------------+-------+----------+-----------+--------------+------------+---------------+---------------------+---------------
-------+-------+---------------+-------------+-------------+-------------+------------+--------------
(0 rows)

postgres=# SELECT * FROM sentry_userip;
 id | ip_address | country_code | region_code | first_seen | last_seen | user_id
----+------------+--------------+-------------+------------+-----------+---------
(0 rows)
```

**Comment by azaslavsky** [comment] 2023-10-23 21:50
I am working on a fix for this, tracked by its duplicate at https://github.com/getsentry/self-hosted/issues/2468. I will close this as a dupe.

**Closed by azaslavsky** 2023-10-23 21:50 UTC
