### ISSUE TITLE
There are no web, nginx, or relay container in Docker.

### ISSUE THREAD

**Issue by elkon028** [getsentry/self-hosted#3396] opened 2024-10-25 06:50 UTC
### Self-Hosted Version

24.10.0

### CPU Architecture

x86_64

### Docker Version

Docker version 27.3.1, build ce12230

### Docker Compose Version

Docker Compose version v2.29.7

### Steps to Reproduce

```sh
git clone git@github.com:getsentry/self-hosted.git
cd self-hosted
git checkout 24.10.0
# cp .geoipupdate.lock GeoIP.conf GeoLite2-City.mmdb --> self-hosted/geoip/
cp /opt/backup/geoip/* ./geoip/

./install.sh
```

### Expected Result

```sh
docker ps -a

CONTAINER ID   IMAGE                                              COMMAND                   CREATED          STATUS                        PORTS                                                             NAMES
5525d8e7fcc9   getsentry/snuba:24.10.0                            "./docker_entrypoint…"   28 minutes ago   Exited (0) 21 minutes ago                                                                       sentry-self-hosted-snuba-api-1
ffccb4275263   memcached:1.6.26-alpine                            "docker-entrypoint.s…"   28 minutes ago   Exited (0) 21 minutes ago                                                                       sentry-self-hosted-memcached-1
06b1b3c8a271   getsentry/symbolicator:24.10.0                     "/bin/bash /docker-e…"   28 minutes ago   Exited (137) 20 minutes ago                                                                     sentry-self-hosted-symbolicator-1
0bf35c0b7d6c   tianon/exim4                                       "docker-entrypoint.s…"   28 minutes ago   Exited (0) 21 minutes ago                                                                       sentry-self-hosted-smtp-1
ad5fe54fd12d   postgres:14.11                                     "docker-entrypoint.s…"   28 minutes ago   Exited (0) 21 minutes ago                                                                       sentry-self-hosted-postgres-1
07661ac6dceb   confluentinc/cp-kafka:7.6.1                        "/etc/confluent/dock…"   28 minutes ago   Exited (143) 21 minutes ago                                                                     sentry-self-hosted-kafka-1
0e8049555840   redis:6.2.14-alpine                                "docker-entrypoint.s…"   28 minutes ago   Exited (0) 21 minutes ago                                                                       sentry-self-hosted-redis-1
58f76e243cf8   clickhouse-self-hosted-local                       "/entrypoint.sh"          28 minutes ago   Exited (0) 21 minutes ago                                                                       sentry-self-hosted-clickhouse-1
b749e8686dbd   portainer/portainer-ce:linux-amd64-2.21.4-alpine   "/portainer"              5 hours ago      Up 14 minutes                 8000/tcp, 9443/tcp, 0.0.0.0:9090->9000/tcp, [::]:9090->9000/tcp   portainer
```

Why there are no web, nginx, or relay containers in Docker?
open http://127.0.0.1:9000 ERR_CONNECTION_REFUSED
```sh
lsof -nP -i4 | grep LISTEN
systemd-r    669 systemd-resolve   14u  IPv4    5450      0t0  TCP 127.0.0.53:53 (LISTEN)
nginx        826            root   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        826            root   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        827             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        827             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        828             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        828             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        829             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        829             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        830             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        830             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        831             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        831             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        832             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        832             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        833             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        833             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        834             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        834             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        835             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        835             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        837             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        837             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        839             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        839             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        841             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        841             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        842             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        842             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        843             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        843             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        844             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        844             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        845             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        845             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        846             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        846             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        847             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        847             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        848             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        848             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        849             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        849             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        850             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        850             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        851             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        851             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        853             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        853             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
nginx        854             www   10u  IPv4   14780      0t0  TCP *:888 (LISTEN)
nginx        854             www   11u  IPv4   14781      0t0  TCP *:80 (LISTEN)
sshd         917            root    3u  IPv4 5115305      0t0  TCP *:22 (LISTEN)
redis-ser    936           redis    6u  IPv4   28709      0t0  TCP 127.0.0.1:6379 (LISTEN)
sendmail-   2697            root    4u  IPv4   20340      0t0  TCP 127.0.0.1:25 (LISTEN)
sendmail-   2697            root    5u  IPv4   20341      0t0  TCP 127.0.0.1:587 (LISTEN)
BT-Panel  397566            root    5u  IPv4 2974875      0t0  TCP *:8888 (LISTEN)
cupsd     433327            root    7u  IPv4 4539271      0t0  TCP 127.0.0.1:631 (LISTEN)
code-384f 446131            root    9u  IPv4 4687781      0t0  TCP 127.0.0.1:38657 (LISTEN)
fastapi   447872            root    9u  IPv4 4690481      0t0  TCP 127.0.0.1:8000 (LISTEN)
python    447884            root    9u  IPv4 4690481      0t0  TCP 127.0.0.1:8000 (LISTEN)
docker-pr 632729            root    4u  IPv4 5179796      0t0  TCP *:9090 (LISTEN)
```

### Actual Result

[sentry_install_log-2024-10-25_13-57-13.txt](https://github.com/user-attachments/files/17517245/sentry_install_log-2024-10-25_13-57-13.txt)

**Comment by aminvakil** [comment] 2024-10-25 11:09
Because of the change you have made in this Dockerfile, or maybe you haven't used this repository, but this line is broken.
```
#5 [2/2] RUN set -x   && sed -i 's|http://deb.debian.org|https://mirrors.aliyun.com/debian|g' /etc/apt/sources.list   && sed -i 's|http://security.debian.org|https://mirrors.aliyun.com/debian-security|g' /etc/apt/sources.list   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq   && apt-get clean   && rm -rf /var/lib/apt/lists/*
#5 0.141 + sed -i s|http://deb.debian.org|https://mirrors.aliyun.com/debian|g /etc/apt/sources.list
#5 0.142 sed: can't read /etc/apt/sources.list: No such file or directory
```

**Comment by aldy505** [comment] 2024-11-12 06:28
Looks like a duplicate of this https://github.com/getsentry/self-hosted/issues/3410

Closing this one as it's resolved from the other issue.

**Closed by aldy505** 2024-11-12 06:28 UTC
Labels: Waiting for: Community
